### ISSUE TITLE
🐞 - demo components URL query params parsing error

### ISSUE THREAD

**Issue by ElioLooiz** [Tinkoff/taiga-ui#1011]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Description

If you share a link to a demo component page with someone like this:
https://taiga-ui.dev/components/input-phone/API?tuiMode=null&countryCode=%2B7 (just copied from the address bar of the browser as usual)

It will parse "7" as countryCode parameter but expected value is "+7". As a result, the demonstrated component will behave incorrectly.
For example in InputPhone (video)

https://user-images.githubusercontent.com/58699230/142011414-e8636f40-b3f2-45b4-a837-d6a7a5eb5058.mp4

### Angular version

idk

### Taiga UI version

idk

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I believe it also parses `false` as `"false"` making it truthy. We should fix that and also it probably doesn't make sense to store `tuiMode=null` as it is the default.
