### ISSUE TITLE
🐞 - tuiOverscroll is not working with macOS scroll inertia

### ISSUE THREAD

**Issue by VictorienTardif** [Tinkoff/taiga-ui#1015]
### Which @taiga-ui/* package(s) are the source of the bug?

cdk

### Description

When you scroll over a `div` with `tuiOverscroll` to `all` and then move the cursor outside of this `div`, the scroll inertia make the page scrolling. 

This is a very confusing behavior. 

See:

https://user-images.githubusercontent.com/3167791/142235827-28ae672d-46f3-4dcb-8bc1-9d275e1d2eb7.mp4

### Angular version

12.2.4

### Taiga UI version

2.21.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
@vladimirpotekhin can you take a look? I worry though, that there nothing we can do since most work is handled by native CSS rule.

**Comment by vladimirpotekhin** [comment]
I can't reproduce it with trackpad. @VictorienTardif  are you using a mouse?

**Comment by VictorienTardif** [comment]
> I can't reproduce it with trackpad. @VictorienTardif are you using a mouse?

Indeed I can't reproduce neither with the trackpad nor with a standard mouse, it's happening with the Apple magic mouse. So it's a niche problem :)

**Comment by waterplea** [comment]
Ok, I suppose it's some Apple voodoo then, let's close it :)
