### ISSUE TITLE
🚀 - Add Readonly mode for InputFile 

### ISSUE THREAD

**Issue by zergunteg** [Tinkoff/taiga-ui#1027]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

Now it's impossible to show downloadable, already uploaded files without drag-n-drop box. Please, add readonly mode for InputFile or another way to show downloadable files

example: https://www.figma.com/file/mvA06tsRvujHEgeQcMsUAH/Untitled?node-id=0%3A1

**Comment by waterplea** [comment]
Closing this in favor of a new wider issue: https://github.com/Tinkoff/taiga-ui/issues/1221
