### ISSUE TITLE
🚀 - TuiAutoFocusDirective - possibility to select text inside input

### ISSUE THREAD

**Issue by andrew-belyi** [Tinkoff/taiga-ui#1030]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

cdk

### Description

Is it possible to add additional feature to `tuiAutoFocus` directive? The goal is to have focus on input and also select the whole text inside input.
Thanks!

**Comment by waterplea** [comment]
Hi. I don't think it belongs in this directive since it's just about focus. It can focus a button, for example, not an editable field. You can make your own directive matching the same selector and re-export our directive for smooth usage:
https://stackblitz.com/edit/taiga-autofocus-select

**Comment by andrew-belyi** [comment]
Thank you for advice!
