### ISSUE TITLE
🚀 - No visual feedback when pressing a button on mobile device

### ISSUE THREAD

**Issue by VictorienTardif** [Tinkoff/taiga-ui#1034]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/button

### Description

When touching a button on mobile (on mine at least, Android 10), there's no feedback. 
You can test it by opening the buttons examples: https://taiga-ui.dev/components/button
It looks like a `_pressed` class should be added if I read the code correctly but something is not working.

### Angular version

12.2.4

### Taiga UI version

2.24.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [X] Android

**Comment by VictorienTardif** [comment]
Hello, could you take a look at this issue or tell me if I'm missing something? 

I find it very confusing to have no feedback at all when touching a button a mobile and I can't believe it's the case in your interfaces is it?

**Comment by waterplea** [comment]
Yeah, that's because `mousedown` and `mouseup` are triggered instantaneously upon finger release on touch devices. We have a bigger feature to cover this:
https://github.com/TinkoffCreditSystems/taiga-ui/issues/928
I have made a small fix for buttons until this feature is implemented:
https://github.com/TinkoffCreditSystems/taiga-ui/pull/1074

**Comment by VictorienTardif** [comment]
Ok nice thank you!!

**Comment by VictorienTardif** [comment]
Hello @waterplea, I just realized that for some reason it was still not working with `appearance='flat'` and `tuiMode`. While we do have a change of background color on web, we don't have it on mobile.

See https://taiga-ui.dev/components/button/API?tuiMode=onDark&icon=tuiIconEyeClosed&appearance=flat

**Comment by waterplea** [comment]
Yes, the fix only covered "modeless" appearance. I'll reopen this issue and fix it for mode too.

**Comment by waterplea** [comment]
Fixed in 3.0
