### ISSUE TITLE
🚀 - An injection token to not hide arrow while select, multiselect, or combo-box is disabled.

### ISSUE THREAD

**Issue by EricPoul** [Tinkoff/taiga-ui#1068]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

Starting from this commit https://github.com/TinkoffCreditSystems/taiga-ui/commit/8eb4d1cb0b2f4791fe83efb6d50d7d7be42a9994 arrows are hidden if select, multiselect, or combo-box is disabled. I'd like to have a feature with that I can set up whether the arrow is hidden or not.

**Comment by waterplea** [comment]
That's a decision from internal projects design team that I'm not happy about myself. They claim it's not clear for users this way. Maybe we can revert it and hide them in the internal overrides.

**Comment by waterplea** [comment]
@EricPoul behavior is rolled back and a token is added, coming up Monday with v2.32.0
