### ISSUE TITLE
🐞 - Double click selection on number input with space thousandSeparator 

### ISSUE THREAD

**Issue by Mahakon** [Tinkoff/taiga-ui#1084]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Description

Double click selection on number input with space thousandSeparator do not select all value

<img width="185" alt="image" src="https://user-images.githubusercontent.com/31204888/145377341-2c426fe9-4c79-4be2-b1a6-008ad5658547.png">

### Angular version

13.0.2

### Taiga UI version

2.24.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
You can tripple click to select all, I don't think we should mess with native browser behavior :)
