### ISSUE TITLE
🐞 - TuiMultiSelect doesn't display an example text if multi select is not editable

### ISSUE THREAD

**Issue by eezzyybreezzyy** [Tinkoff/taiga-ui#1104]
### Which @taiga-ui/* package(s) are the source of the bug?

core, kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter-dfb4go?file=src%2Fapp%2Fapp.component.html

### Description

If multiselect is not editable then tuiTextfieldExampleText is not displayed when control is pressed

### Angular version

11.2.13

### Taiga UI version

2.26.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by alejandrocoding** [comment]
I've been looking at this for a bit, it seems a bit confusing to me, so I would appreciate a second opinion or a hand.

I see diff peaks that make the placeholder gone, those are:

- `div.input-wrapper` add a class `input-wrapper_collapsed` which sets flex to 0. (input-tag.template.html#76)
- the actual input element has the `native_hidden` class added here: `[class.native_hidden]="inputHidden"` (input-tag.template.html#85)
- placeholder pseudoselector set opacity at 0 for native class like `.native { ... &::placeholder {... opacity: 0; } }` (input-tag.style.less#234)

Removing these three ones, placeholder become visible, but ofc that is not the way to go, also shows placeholder even when not focused, overlapping with text if any. Just highlighting those points to share how far I have gotten, not saying that is the correct way to go, in fact, as I feel that is wrong way, asking if some contributor might give any insight/clue about the issue given the current information.

maybe @splincode ? Thanks 👍

**Comment by splincode** [comment]
I'm sure @waterplea know more about this.
