### ISSUE TITLE
🐞 - ERROR Error: StaticInjectorError(AppModule)[IntersectionObserverService -> ElementRef]

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#1109]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-g4gttt

### Description

![image](https://user-images.githubusercontent.com/12021443/146046268-5c97efb0-d788-41b8-8226-8aee1e811272.png)

### Angular version

12

### Taiga UI version

2.27

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
That is most likely an issue with StackBlitz and disabled Ivy, avatars work fine on my pet project with the same versions.
