### ISSUE TITLE
🤖 - Add `special thanks` section in CHANGELOG.md

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#1111]
### Description

Reference: https://github.com/angular/angular/blob/master/CHANGELOG.md

![image](https://user-images.githubusercontent.com/12021443/146145136-b7a77196-e323-4a65-8655-0ae8ec5c2536.png)

@waterplea what do you think?

**Comment by waterplea** [comment]
Can we automate that?

**Comment by splincode** [comment]
`Can we automate that?` I think, yes)) as a weekend homework I can research this
