### ISSUE TITLE
🤖 - Investigate memory leak

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#1119]
### Description

https://blogs.windows.com/msedgedev/2021/12/09/debug-memory-leaks-detached-elements-tool-devtools/

![image](https://user-images.githubusercontent.com/12021443/146400699-29d022aa-0acc-4112-9e80-9f9e5ee4f8b7.png)

**Comment by splincode** [comment]
there are still problems

<img width="840" alt="image" src="https://user-images.githubusercontent.com/12021443/157900349-c01f6903-5576-45c1-8ffc-23c8094a14fe.png">

**Comment by waterplea** [comment]
I've managed to isolate it on Stackblitz, looks like it might be Angular animations bug:
https://github.com/angular/angular/issues/50533
