### ISSUE TITLE
[FEATURE] UI-Rating

### ISSUE THREAD

**Issue by WuglyakBolgoink** [Tinkoff/taiga-ui#112]
# 🚀 Feature request

will be great to have the same component

https://fomantic-ui.com/modules/rating.html

**Comment by waterplea** [comment]
Hi @WuglyakBolgoink.

Such high level specific components are out of scope for this library. They are very easy to create using tools provided by Taiga UI. Here, I quickly threw out an example using `*tuiRepeatTimes` directive:
https://stackblitz.com/edit/taiga-rating?file=src%2Fapp%2Frating%2Frating.component.html

**Comment by WuglyakBolgoink** [comment]
@waterplea sorry, I forgot about this `*tuiRepeatTimes` feature

**Comment by waterplea** [comment]
Internal need for such a component with accessibility popped up so I'm reopening this.
