### ISSUE TITLE
🐞 - PdfViewer does not display document on Android

### ISSUE THREAD

**Issue by rvalitov** [Tinkoff/taiga-ui#1129]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Description

I'm testing PdfViewer https://taiga-ui.dev/components/pdf-viewer
It works fine on desktop, but does not work on Android, it asks me to download/open the document instead of a preview:
![image](https://user-images.githubusercontent.com/16267156/146762864-83e8f888-1b1f-4805-9f0a-f9fae347da05.png)

Tested with latest Google Chrome at Android 10.
As far as I remember the Tinkoff bank mobile apps do allow to view documents (such as invoices, receipts, account statements) in the app. I was expecting the same behavior here. Or the Tinkoff mobile apps use some other approach?

### Angular version

12.2.13

### Taiga UI version

2.27.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [X] Android

**Comment by waterplea** [comment]
Unfortunately mobile browsers do not support displaying PDF so there's nothing we can do about it. I've added a warning to the PdfViewer page notifying about this just today.

**Comment by waterplea** [comment]
If you have some ideas how to handle this better, feel free to share them and we can reopen this issue and turn it to Feature if there's a solution which we can have.
