### ISSUE TITLE
🐞 - Asynchronous tree doesn't render children

### ISSUE THREAD

**Issue by Parzisal** [Tinkoff/taiga-ui#1141]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/tree

### Description

when updating child elements, rendering occurs only after hovering the cursor over the button, thus, the trigger of the "children" getter is triggered, and only after that new elements are rendered

https://user-images.githubusercontent.com/49144303/147222922-8d9340e6-4d59-4645-b0dd-124be8454660.mp4

### Angular version

11.2.13

### Taiga UI version

2.26.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nirajgeorgian** [comment]
should I get started with this bug ?
I would love to work on this.
I am able to reproduce it locally.

**Comment by waterplea** [comment]
@nirajgeorgian thank you for your interest. Sorry but I took it myself as it required certain knowledge of approaches we took when architecting this code and it would probably take some time to understand what's going on over there.
