### ISSUE TITLE
🐞 - TuiHideSelectedPipe does not work with ViewEngine angular app

### ISSUE THREAD

**Issue by tim99919** [Tinkoff/taiga-ui#1149]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/dvavrk--run?file=src/app/app.component.ts

### Description

Providing a component ref to TuiHideSilectedPipe does not work and IDE shows the error: "invalid numbers of arguments".

Error in console: 
> ERROR
Error: StaticInjectorError(AppModule)[TuiHideSelectedPipe -> TuiMultiSelectComponent]:
StaticInjectorError(Platform: core)[TuiHideSelectedPipe -> TuiMultiSelectComponent]:
NullInjectorError: No provider for TuiMultiSelectComponent!

### Angular version

10.2.3

### Taiga UI version

2.28.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
It's impossible to fix for view engine and view engine is obsolete so we'll keep it as is. We have several pipes in Taiga that rely on dependency injection and this has only became possible with ivy

**Comment by tim99919** [comment]
ok, thx
