### ISSUE TITLE
Default Change Event on Select not working

### ISSUE THREAD

**Issue by ShoaibShahid** [Tinkoff/taiga-ui#1159]
### What is the affected URL?

https://taiga-ui.dev/components/select/API?tuiMode=null

### Description

The default change event is not triggering on Select. I just want to  know what to use against it  As documentation demo showing the functionality of onChange event but I am not Finding any thing what to use for this.📚 - 

![image](https://user-images.githubusercontent.com/60649981/147639522-42761e67-2d52-437e-ac46-d78884067389.png)

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
You're not supposed to work with native events in Angular forms. Just listen to ngModelChange if you use FormsModule or control.valueChange if you use ReactiveFormsModule
