### ISSUE TITLE
🐞- Combobox: nativeValue assumes it is human readable value (if the value is a string) 

### ISSUE THREAD

**Issue by jonsamwell** [Tinkoff/taiga-ui#1168]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Description

Further to this issue a while ago https://github.com/Tinkoff/taiga-ui/issues/382

It now seems that when using a combobox to search for a value with a list when the data source is a complex object with say a id (which in my case is a guid string) and a string name property `{id: stirng, name: string}.  When an item is selected the stringify property is used to convert the id (guid string) to the corresponding name property.  However, when the user clicks back into the control the nativeValue property is displayed (https://github.com/Tinkoff/taiga-ui/blob/main/projects/kit/components/combo-box/combo-box.component.ts#L148) which in my case is a string so the stringify function in not called and the user ends up seeing a guid rather than the human readable value.

Items when first selected appears correctly:

![image](https://user-images.githubusercontent.com/3694497/148141450-14273d34-84d0-4b1a-8422-07ce35a2e231.png)

Control when it is clicked into again display the nativeValue of the control rather than the items name value as stringify is not called as the nativeValue is a string (guid) which is assumed to be ok to display

![image](https://user-images.githubusercontent.com/3694497/148141517-b6485c89-2807-476d-9cd9-6871e9c1a160.png)

I think perhaps the control should not be assumed that the nativeValue can always just be display and the stringify function should be called

### Angular version

13.1.1

### Taiga UI version

2.29.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I suppose it was written this way for `[strict]="false"` mode where everything you type in gets into control value but you can also pick an option from the list to be value. And so if your items have some interface and you've given a stringify function for that interfaces — it would probably break for a string in non-strict mode where string can be value too. I'm not saying it is correct, just thinking why this code is there. We need to handle this differently, but I'm not sure how to do it best yet. It's as if in strict = true we need to have `TuiStringHandler<T>` as a type for `stringify` but when strict = false we need `TuiStringHandler<T | string>` 🤔

**Comment by jonsamwell** [comment]
Yes the trouble comes maintaining backward compatibility.  What about a nullable  TuiStringHandler<T> and if it is non-nullable use it instead of returning the raw string value?

**Comment by jonsamwell** [comment]
Thanks this works really well now.
