### ISSUE TITLE
🐞 - `PreviewDialogService.open()` does not work

### ISSUE THREAD

**Issue by robingenz** [Tinkoff/taiga-ui#1174]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

https://github.com/robingenz/taiga-ui-issue-1174

### Description

First of all, thank you for this great library!

I have implemented this example: https://taiga-ui.dev/components/preview#loading
When I press the `Show preview` button, nothing happens. 
This does not work both in StackBlitz and locally.
I have tested it with Angular 12 and 13.
I have tested it with Taiga UI 2.29.0 and 2.26.0.

### Angular version

12.2.0

### Taiga UI version

2.29.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Hi @robingenz, thank you for bringing this up. Please add `PREVIEW_DIALOG_PROVIDER` to your app module providers. @vladimirpotekhin we need to add this provider to a module and update the instructions — we don't need to add `TuiDialogModule` to app module for this to work, we would need to add `TuiPreviewModule` (after we add provider there). Also add a TODO to add `Tui` prefix to the service, it's missing it.

**Comment by robingenz** [comment]
Great, that works! Thank you very much.

**Comment by waterplea** [comment]
> Great, that works! Thank you very much. 
> 

In the next version that comes out Monday 17th you can drop that provider and just use module.
