### ISSUE TITLE
🚀 - Add `interactive` getter to `AbstractTuiInteractive`

### ISSUE THREAD

**Issue by waterplea** [Tinkoff/taiga-ui#1183]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

cdk

### Description

Many of our components rely in their logic on combination of not being `readOnly` and not being `disabled`. Let's add this:

```ts
get interactive(): boolean {
  return !this.computedDisabled && !this.readOnly;
}
```

to `AbstractTuiInteractive` and refactor everything to use that getter.

**Note:** We need to keep in mind it might be written in different order and sometimes it can be `disabled` and sometimes it can be `computedDisabled`. The best approach would be to search whole project for `this.readOnly` and replace code with that new getter wherever possible.

**Comment by GeorgeSokolovsky** [comment]
I will try to make it done today or at the weekend.
