### ISSUE TITLE
🛠 - Investigate other mask options

### ISSUE THREAD

**Issue by SergiusSidorov** [Tinkoff/taiga-ui#120]
# 🚀 Feature request

### Is your feature request related to a problem?

Last release of angular2-text-mask  was about 3 years ago. Currently this project is not maintained. Using this library results in a build-time warning:
_Warning: /node_modules/@taiga-ui/kit/__ivy_ngcc__/fesm2015/taiga-ui-kit-components-input-range.js depends on 'angular2-text-mask'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies_

There is a possibility to switch off this warning. But I'm always frustrated when something can cause optimization bailouts. =)

### Describe the solution you'd like

Maybe it would be better to migrate to ngx-mask (https://github.com/JsDaddy/ngx-mask). This project looks alive.

**Comment by ramax495** [comment]
ngx-mask doesn't work on Ionic.
Just for info)

**Comment by waterplea** [comment]
Thank you for raising this issue. Yes, we would like to migrate to another mask solution at some point. 

I have refactored work with mask in input a little. Now if you were to use angular2-text-mask — you could set it directly on `tui-input`. This way Taiga UI _supports_ angular2-text-mask but doesn't enforce it on you, as end user. It is still required by our internal implementation for various masked inputs, such as InputDate, InputNumber etc. But that could be refactored without breaking changes in future when we will have resources and a good candidate library (or have written our own).

**Comment by Phmager** [comment]
I can highly recommend angular-imask which uses imask.js under the hood. Which would be a bit bigger in comparison

**Comment by Fafnur** [comment]
Don't use ngx-mask.

**Comment by zy2ba** [comment]
> Don't use ngx-mask.

Support this opinion. We take it for our project and have some pain moments.

Primarily, ngx-mask works normally only with type=text. Mobile users be frustrated by strange keyboard type selection with it

**Comment by Yohandah** [comment]
Also, this is blocking because we are unable to run Unit Tests because of this lib https://github.com/text-mask/text-mask/issues/1019

`Error: TextMaskModule does not have a module def (ɵmod property)`

**Comment by hakimio** [comment]
Maybe [@ngneat/input-mask](https://github.com/ngneat/input-mask) could be a good alternative?

**Comment by waterplea** [comment]
I believe we looked into it and decided not to go with it. Writing our own mask solution seems to be the way to go, especially since it would be in demand at our company outside Angular scope as well. So this is one of the supertasks for 3.0 we plan to get to in a couple of weeks.

**Comment by hakimio** [comment]
Worth noting that `angular2-text-mask` is not only causing problems with [Stackblitz](https://github.com/Tinkoff/taiga-ui/issues/2541) but also prevents usage of [yarn v2+](https://github.com/angular/angular-cli/issues/16980) and `pnpm` because of `ngcc` requirement. Would be awesome if getting rid of this dependency could be prioritized.

**Comment by waterplea** [comment]
I believe we dropped `angular2-text-mask` and copy-pasted it for now in newer versions. But `text-mask` remains a dependency. We will prioritize new mask from the November 1, but it's a huge task so there's no forecast how long it's going to take us.

**Comment by hakimio** [comment]
The copy-pasted version is marked `internal` and `deprecated`, but, yeah, it could be a valid work-around until you develop your own solution.

**Comment by hakimio** [comment]
Angular v16 was just released where they dropped `ngcc`.
@nsbarsukov how is `maskito` coming along? Do you plan to start using it in `taiga-ui` soon?

**Comment by nsbarsukov** [comment]
> Angular v16 was just released where they dropped `ngcc`. @nsbarsukov how is `maskito` coming along? Do you plan to start using it in `taiga-ui` soon?

[Maskito](https://github.com/Tinkoff/maskito) is ready to use it inside Taiga UI, yep.
I am going to start in next week. And I will do 1-2 components per week (not all masked inputs at once.).

**Comment by hakimio** [comment]
Awesome 🙂
