### ISSUE TITLE
🐞 - Missed ComboBox arrow cursor pointer

### ISSUE THREAD

**Issue by artsemshein** [Tinkoff/taiga-ui#1201]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Description

Missed cursor pointer when hover combobox arrow
![image](https://user-images.githubusercontent.com/20995091/149765276-e2835131-4ab3-472a-8e52-a1bb6f8eec8b.png)

### Angular version

any

### Taiga UI version

2.29.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by loxy** [comment]
This is also true for the date inputs
