### ISSUE TITLE
🐞 - InputNumber does not display updated form control value

### ISSUE THREAD

**Issue by sFeels** [Tinkoff/taiga-ui#1206]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Description

1. Add inputNumber and pass some form control to it.
2. Change form control value programmatically (set/patchValue).
3. Form control value will be updated, but  inputNumber won't display this change.

### Angular version

12.2.5

### Taiga UI version

2.24.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
@sFeels please try updating to the latest version, I believe it was fixed before.

**Comment by waterplea** [comment]
I'm closing this issue because I'm confident we fixed it already, here's a stackblitz to test:
https://stackblitz.com/edit/taiga-starter-tvkjfp
