### ISSUE TITLE
🐞 - TableBarsHost unable to change mode

### ISSUE THREAD

**Issue by Volker505** [Tinkoff/taiga-ui#1215]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-tablebars

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Description

Changing the mode property does not work in the table-bars-host 
there is no class [class.bar_light]
https://github.com/Tinkoff/taiga-ui/blob/main/projects/addon-tablebars/components/table-bars-host/table-bars-host.template.html

### Angular version

12.2.6

### Taiga UI version

2.29.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
@vladimirpotekhin looks like it was introduced when prefixes were added, it's missing prefix in HTML but the prefix is there in LESS file.
