### ISSUE TITLE
🐞 - InputPhoneInternational for ISO code "BA" is limited to only 7 numbers after prefix

### ISSUE THREAD

**Issue by MladenSijan** [Tinkoff/taiga-ui#1226]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Description

🐞 Bug report

Description
It is currently not possible to enter more than 7 numbers after prefix when Bosnia and Herzegovina is selected as country (ISO code "BA").

Expected behavior
It should accept up to 9 numbers after "+387" prefix

### Angular version

13.0.0

### Taiga UI version

2.30.1

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [X] Linux
- [X] iOS
- [X] Android

**Comment by jonsamwell** [comment]
@MladenSijan I also encountered this issue for 'GB' based phone numbers.  Luckily as Taiga is basically build around DI it is fairly easy to fix this (although the fix is less than ideal so only consider using if need to get out of a spot).  See code below.  I hope this helps

```
import { TuiCountryIsoCode } from '@taiga-ui/i18n';
import { COUNTRIES_MASKS, TUI_COUNTRIES } from '@taiga-ui/kit';


  public constructor(
    @Inject(TUI_COUNTRIES)
    readonly countriesNames$: Observable<Record<TuiCountryIsoCode, string>>,
  ) {
    super();
   // override the GB mask
    COUNTRIES_MASKS[TuiCountryIsoCode.GB] = '+44 #### ######';
  }

  // ensure the countries are sorted alphabetically so they display as such in the ui
  public readonly countries = this.countriesNames$.pipe(
    map((countries) => {
      return Object.values(TuiCountryIsoCode).sort((a, b) => {
        const aName = countries[a];
        const bName = countries[b];

        return aName.localeCompare(bName);
      });
    }),
    shareReplay(1),
  );

  public countryIsoCode = TuiCountryIsoCode.GB;




<tui-input-phone-international
  [nativeId]="id"
  [tuiTextfieldLabelOutside]="labelOutside"
  [tuiHintContent]="description"
  [readOnly]="readonly"
  [formControl]="$any(formControl)"
  [formlyAttributes]="field"
  [class]="field.className"
  [countries]="countries | async"
  [(countryIsoCode)]="countryIsoCode"
>
  <div *ngIf="to.labelPosition !== 'wrap'">
    <span>{{to.label}}</span>
    <div polymorpheus-outlet [content]="$any(to.complexLabel)"></div>
    <span *ngIf="to.required && to.complexLabel === undefined">
      &nbsp;<span class="tui-required"></span>
    </span>
  </div>
  <div *ngIf="to.description">{{to.description}}</div>
</tui-input-phone-international>
```

**Comment by waterplea** [comment]
@splincode let's make country list a DI token as part of this ticket. We need to do it anyway for future plans.

**Comment by MladenSijan** [comment]
@jonsamwell Good approach! I was thinking about it, but I also kept in mind that guys will eventually plan to make some kind of configurable way so there it is! :)
