### ISSUE TITLE
🐞 - Tree examples don't work on StackBlitz

### ISSUE THREAD

**Issue by MarenkovIgor** [Tinkoff/taiga-ui#1237]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/dsakjy--run?file=src/app/app.component.ts

### Description

subj

### Angular version

12.2.15

### Taiga UI version

2.30.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
`TuiTreeModule` is missing from StackBlitz modules list. If you want, you can file a PR to fix it, just look for "stackblitz" in project and you will find the modules list.
