### ISSUE TITLE
Input-cards > demo > Api page > changing tuiTextfieldSize and tuiTextfieldLabelOutside

### ISSUE THREAD

**Issue by overstay812** [Tinkoff/taiga-ui#1252]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-commerce

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/input-card/API?tuiMode=null&tuiTextfieldSize=m

### Description

when truing to change value in  tuiTextfieldSize and tuiTextfieldLabelOutside on demo page > Api,  the result does not change

### Angular version

9.1.12

### Taiga UI version

2.19.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Looks like we forgot to bind those values in the template. A PR is very welcome!

**Comment by Omerbea** [comment]
Hey I would like to take this one

**Comment by waterplea** [comment]
@Omerbea sure, go ahead!
