### ISSUE TITLE
🤖 - Investigate cyclic dependencies

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#1260]
### Description

- https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md
- https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues

**Comment by splincode** [comment]
Wait migrate taiga's codebase to Angular 10+

![image](https://user-images.githubusercontent.com/12021443/151318971-4f963c0e-010d-436a-82e3-7951d5069afe.png)

**Comment by splincode** [comment]
`https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md` this plugin is not tuned for Angular and does not work correctly

**Comment by mullinsmikey** [comment]
Since Taiga utilizes Nx, you might want to consider the following rule: `@nrwl/nx/enforce-module-boundaries`

**Comment by splincode** [comment]
@mullinsmikey I will be very grateful if you help me with this)

**Comment by mullinsmikey** [comment]
@splincode, the ESlint config has been updated. Although the new rule is now set to produce 'warn' error level, I'd suggest to increase it as soon as all these warnings are fixed.

**Comment by mullinsmikey** [comment]
@splincode I guess yes but I need you to be a bit more specific. It could be more convenient to contact me in Telegram - ping the group chat and I'll be in touch)

**Comment by waterplea** [comment]
@splincode Demo app is an app, no library should depend on it.

**Comment by mullinsmikey** [comment]
@splincode, the presented graph looks fine but there's `addon-doc` lib missing. Here:
<img width="1298" alt="Screen Shot 2022-02-02 at 12 20 20 PM" src="https://user-images.githubusercontent.com/8100939/152117948-bb139308-e75e-48ee-af43-444e74e8de45.png">
