### ISSUE TITLE
🚀 - TuiEditorNewComponent to have a possibility to edit the HTML Code as a plain text

### ISSUE THREAD

**Issue by AILazerka** [Tinkoff/taiga-ui#1263]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

addon-editor

### Description

For some application use-cases it may be useful to have the possibility to edit the html directly.

The use case that I'm having is the following:
There are different account login possibilities exists in the application. Being abstract: we have a possibility to login to account as a plain client and as admin. For the admins we are having the possibility to adjust the code directly in case of some issues. My suggestion is to have a new uiTool to have a new button in the toolbar so it will give a possibility of editing the HTML content directly as the HTML Code.

Right now I'm going to implement the custom tool as to the taiga-ui documentation.

Hoping it will be useful.
Thank you in advance!

**Comment by waterplea** [comment]
You can probably make a toggle on your page between `tui-textarea` and `tui-editor` components tied to the same control while this is not implemented natively in `Editor` component.

**Comment by AILazerka** [comment]
Yep @waterplea. That's a kind of what I did as a temporary workaround until the feature will be added 🙂

**Comment by splincode** [comment]
Close in favor of https://github.com/Tinkoff/tui-editor/issues/18
