### ISSUE TITLE
🐞 - "addon-doc" incompatible with Angular v13

### ISSUE THREAD

**Issue by hakimio** [Tinkoff/taiga-ui#1274]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-doc

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Description

Trying to update Angular to v13 with `ng update @angular/core@13 @angular/cli@13` throws following error when using `@taiga-ui/addon-doc`:
```
Package "@taiga-ui/addon-doc" has an incompatible peer dependency to "@angular-devkit/schematics" (requires "^9.0.0", would install "13.2.0").
```

While you are at it, it would be nice if all other `addon-doc` peer dependencies would be updated to the latest version as well and their version range would be extended to at least include minor releases (`^1.0.0`).

### Angular version

13.2.0

### Taiga UI version

2.31.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
There is also another issue with `addon-doc`.
After updating to the latest version, I get the following error during compilation:
```
@angular/compiler-cli/bundles/chunk-5CHRTEXL.js:941
      throw new Error(`The target entry-point "${invalidTarget.entryPoint.name}" has missing dependencies:
            ^

Error: The target entry-point "@taiga-ui/addon-doc" has missing dependencies:
 - markdown-it
```

**Comment by splincode** [comment]
Oh, sorry about that, needs to be added to dependencies `markdown-it`, i will add this! And as long as you can manually install it yourself

**Comment by waterplea** [comment]
We need to probably move some peerDeps to deps anyway:
https://github.com/Tinkoff/taiga-ui/issues/667
