### ISSUE TITLE
🐞 - Wrong active index in tabs with routerLinkActive when no link should be active

### ISSUE THREAD

**Issue by VictorienTardif** [Tinkoff/taiga-ui#1276]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Description

When using tabs with links and routerLinkActive, if no link is active the first one will be marked as if it was.
In my case I have a header with tabs and some pages that are not accessible from that header and therefore it is confusing to display the first tab as active when none should be.

### Angular version

13.1.2

### Taiga UI version

2.31.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
routerLinks make tabs active, they cannot make them inactive. I believe your issue stems from `activeItemIndex` being `0` by default. Maybe we should change initial value to `NaN` 🤔

**Comment by waterplea** [comment]
@VictorienTardif can you try making it `NaN` or `-1` yourself by adding a binding for `activeItemIndex` to see if it helps?

**Comment by VictorienTardif** [comment]
That works at first render but as soon as a tab becomes active it remains active when I navigate to a route that's not in tabs.

**Comment by VictorienTardif** [comment]
As you say, routerLinks make tabs active, they cannot make them inactive. :/

**Comment by waterplea** [comment]
This is expected. If you need to do it on and off then you need to control `[(activeItemIndex)]` yourself, setting it to `NaN`/`-1` when you navigate to a route not present in the set of tabs.

**Comment by VictorienTardif** [comment]
That's a weird behavior, it looks like a bug to me because if I use links outside of tabs with the routerLinkActive directive they won't stay active when they are not anymore. That's what should be expected don't you think?

**Comment by VictorienTardif** [comment]
I just made some tests with `(isActiveChange)` and it seems to work so I guess I can set the `activeItemIndex ` myself using that. But I think that should be done directly in tabs.

**Comment by VictorienTardif** [comment]
I have something working here:

- I set `activeItemIndex` as `NaN` by default
- I pass this `activeItemIndex` to `tui-tabs` (I was not as I was using the `routerLinkActive` directive)
- I use `(isActiveChange)` on my tabs to set the `activeItemIndex` to the tab index on `true` or to `NaN` again on false.

That way I always have truly active links.
It feels like a reimplementation of what `tui-tabs` should do when using `routerLinks` but np :)

**Comment by waterplea** [comment]
The problem with taking care of deactivation internally is race conditions and independency. Tabs can have buttons, router links and just links all mixed together. It's pretty hard to get this to work the way you want and it's a rather strange behaviour to have tabs and show content underneath that doesn't belong to any tab.

**Comment by VictorienTardif** [comment]
I'll go with my homemade solution then!
Thanks!
