### ISSUE TITLE
🐞 - [tiptap warn]: BREAKING CHANGE: "defaultOptions" is deprecated. Please use "addOptions" instead

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#1290]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-editor

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Description

current in repo 

![image](https://user-images.githubusercontent.com/12021443/151818448-a023aee1-ea25-454c-bca0-a8d6701dedc6.png)

after install

![image](https://user-images.githubusercontent.com/12021443/151818486-223abc1a-5ddf-4b9d-a477-c7265b84c3a3.png)

![image](https://user-images.githubusercontent.com/12021443/151818263-5b58bfcf-96ef-4b9c-9dcc-4bad5183b642.png)

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by dzimney** [comment]
How is this fixed? This continues to be a breaking issue as of 2.0.0-beta.174. If defaultOptions is deprecated it ought to still be suported. If defaultOptions is no longer supported a major version release should be issued with the current major version uneffected.
