### ISSUE TITLE
🚀 - Improving and stabilizing `Editor`

### ISSUE THREAD

**Issue by waterplea** [Tinkoff/taiga-ui#1302]
## Description

As a year-long effort we want to fix many bugs, add many features and stabilize `addon-editor` package. Here's a list of what we plan to work on so far.

## Features

- [ ] https://github.com/Tinkoff/taiga-ui/issues/352
- [ ] https://github.com/Tinkoff/taiga-ui/issues/2455
- [ ] https://github.com/Tinkoff/taiga-ui/issues/2458
- [ ] https://github.com/Tinkoff/taiga-ui/issues/3508
- [x] #3607
- [ ] #3606
- [ ] #3605
- [x] https://github.com/Tinkoff/taiga-ui/issues/3158
- [x] https://github.com/Tinkoff/taiga-ui/issues/3244
- [x] #3599
- [x] https://github.com/Tinkoff/taiga-ui/issues/2456
- [x] https://github.com/Tinkoff/taiga-ui/issues/2363

## Bugs

- [ ] https://github.com/Tinkoff/taiga-ui/issues/2288 / **UIKIT-5261**
- [x] #3600
- [x] https://github.com/Tinkoff/taiga-ui/issues/2287 / **UIKIT-5604**
- [x] #3601
- [x] #3602
- [x] #3603
- [x] #3604

**Comment by splincode** [comment]
https://github.com/Tinkoff/taiga-ui/pull/3075
https://github.com/Tinkoff/taiga-ui/pull/3056
