### ISSUE TITLE
🐞 - [BUG] Compile type error while using *tuiLet

### ISSUE THREAD

**Issue by a1exymoroz** [Tinkoff/taiga-ui#1305]
### Which @taiga-ui/* package(s) are the source of the bug?

cdk

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/table#server

### Description

Getting a type error while trying to use *tuiLet. Because `null` slips into the data

![image](https://user-images.githubusercontent.com/28485877/152021709-d96d04b5-e1c6-4fd5-84d2-141b1e7bdb0b.png)

![image](https://user-images.githubusercontent.com/28485877/152021973-34ac0940-9ece-404b-8a85-a4cf9f4bd0de.png)

**Expected behavior**

`*tuiLet="...$ | async as data"` is returned a correct type.

Any help appreciated

### Angular version

13.2.0

### Taiga UI version

2.31.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
That is expected. Async pipe adds `null` to the type because before the first data emit the value it uses its `null`. You should use `*ngIf` there, `*tuiLet` is for the cases where you need falsy values as well.
