### ISSUE TITLE
🐞 - Inconsistent value for checkboxes in tree

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#1319]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/tree#checkbox

### Description

https://user-images.githubusercontent.com/12021443/152368728-fffe84be-9e0d-4721-957c-d06f0e976053.mov

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
This is working as expected, it just looks weird because `Top level 2` checkbox doesn't have an arrow because it has no children.
