### ISSUE TITLE
🐞 - Wrong behavior of [tuiDropdownLimitWidth] in case of using tui-input inside the multiselect tuiDataList

### ISSUE THREAD

**Issue by ohryk-intellias** [Tinkoff/taiga-ui#1323]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter-yp9vuo?file=src/app/app.component.html

### Description

Hi, guys. Sometimes it is useful to add a piece of custom content (like search input, whatever) to the `tuiDataList` container. In the example above try to uncomment the line with `tui-input` and you will see that Angular throws the error in the console and the behavior of `tuiDropdownLimitWidth` works not correctly (dropdown panel should be 300px wide).

### Angular version

12.2.0

### Taiga UI version

2.29.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by ohryk-intellias** [comment]
The error is not visible in the stackblitz console but can be reproduced locally by running app in the dev mode.

The error:
`ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'min'. Current value: 'fixed'.`

**Comment by waterplea** [comment]
That's because `Input` has its own dropdown. I believe in your case it's better to use `PrimitiveTextfield`:
https://taiga-ui.dev/components/primitive-textfield

**Comment by ohryk-intellias** [comment]
@waterplea  Okay, got it :) Thanks

**Comment by waterplea** [comment]
Closing it as even though there's something could probably be done, `PrimitiveTextfield` works better in this situation anyway.
