### ISSUE TITLE
🚀 - EventEmitter for any kind of inputs/selects/dropdowns/etc.

### ISSUE THREAD

**Issue by arndwestermann** [Tinkoff/taiga-ui#1324]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

Hello, I've just started out with TaigaUI and so far it's kinda nice. But I've noticed a few things, which I kinda find inconvenient.
Can you implement EventEmitters on above mentioned controls? I find it rather annoying to always have to define a FormControl, when I just could use some sort of implemented event for example

```
 <tui-select tuiTextfieldSize="s" (selectionChange)="onSelectionChange($event)">
        <tui-data-list-wrapper
            *tuiDataList
            [items]="items"
        ></tui-data-list-wrapper>
    </tui-select>
```

Would be awesome if this would be possible in the near future

**Comment by ohryk-intellias** [comment]
Hi, please try to import `FormsModule` and use `(ngModelChange)="onSelectionChange($event)"` in case you don't want to work directly with `FormControl`.

**Comment by arndwestermann** [comment]
Hi, okay sorry haven't thought about this approach. I'm used to devextreme and my own components where I got "native" change events on the control.

Could you still consider this feature request?

**Comment by waterplea** [comment]
Angular way to work with forms is through reactive forms or template forms. All Taiga UI controls fully support both approaches and native events are redundant at best, and misleading at other cases, where the value of the form is not a plain string. So I'm closing this with Won't fix. However we will soon expose native inputs from controls so you should be able to bind native events of you so desire 🙂

**Comment by arndwestermann** [comment]
@waterplea 

I wasn't using these controls in a form, I use them in a stand-alone way. For example I have a header component with a selection control for the language and a switch for the theme. I just needed to propagate the value changed event up to the parent component with the value to react on that.

But exposing native input events is kinda neat. I also miss the keydown event to listen for the enter key in an input to trigger a method or what ever on the enter key.

Anyway, thanks for your time.
