### ISSUE TITLE
🐞 - Custom dialog closes slowly

### ISSUE THREAD

**Issue by alex-jss** [Tinkoff/taiga-ui#1332]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Description

Custom dialog closes slowly, example was taken from here https://taiga-ui.dev/dialogs 

### Angular version

12.2.16

### Taiga UI version

2.32.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Can you provide more details? Animation is a responsibility of custom dialog, that's why this example has different animation comparing to the default implementation.

**Comment by alex-jss** [comment]
What additional information i can provide? I also didn't use classes for the dialog, but that didn't help.

**Comment by alex-jss** [comment]
@waterplea Found the reason. Dialog closes slowly if is present `tui-field-error`

**Comment by waterplea** [comment]
I am unable to reproduce, please create a repo on github. I tried it with custom dialog, tried it with default dialog, tried it when the error is shown and when the error is hidden.

**Comment by alex-jss** [comment]
@waterplea 
You can see an [example](https://github.com/alex-jss/test-taiga-modal). After opening the dialog box, click in the input box and then Close. When there is a warning, the window closes slowly.

**Comment by waterplea** [comment]
I think I've got it. Your problem is that you have those elements in the dialog component itself, and not on its content. You're not supposed to make a custom dialog for every dialog, just for every qualitatively different kind of dialog. And the effect you're seeing is due to the fact that dialogs wait for child :leave animations to play out before closing. This way you can create any :leave animation you want for your custom dialogs. So this is kind of working as intended. Is my reasoning clear to you? Or does creating custom dialogs needs further explanation?

**Comment by alex-jss** [comment]
Honestly, no.  Am I doing the custom dialog wrong?  I need exactly the elements in the dialog itself.

**Comment by waterplea** [comment]
Yes, this is not the way it is supposed to be used. When you define custom dialog you kind of create a family of dialogs which share the same behavior. For example, same set of sizes, maybe some built-in buttons (like prompt example for custom dialog), open/close animation etc. This custom dialog would then have some socket (typically `polymorpheus-outlet`) to place the actual content so you can show different dialogs within the same behavior. So in your case, `NewCustomModalComponent` should define behavior — animation, padding, size. And then when you call `NewCustomModalService.open` — you would pass some content to display inside that dialog. This would be your form with fields and error messages. Right now you've done it as if you need to create a custom dialog component + custom service per every different dialog. It's incorrect. Here are a couple of examples for custom dialogs to illustrate what would be the reason to make a custom dialog:
https://taiga-ui.dev/components/preview
https://taiga-ui.dev/components/mobile-dialog

**Comment by waterplea** [comment]
In your case, why not just pass this component with a form to a regular `TuiDialogService`?

**Comment by alex-jss** [comment]
@waterplea Извините, я напишу на русском.
Мне не нравится диалог по умолчанию. Потому что нет полной над ним свободы. Например:
- нет возможности назначить положение на экране сверху
- радиус окна, отступ, цвет не изменить (по умолчанию используется класс `content`)
- для мобильной открывается всегда снизу
- нет возможности использовать свой размер окна
Единственный минус пользовательского диалогового окна, который я вижу на данный момент, это необходимость создавать для каждого окна свой сервис.
Будет замечательно, если появится новый пользовательский диалог без необходимости создания своей отдельной службы с возможностью использования в нем любых компонентов. Или использование `TuiDialogService`, но с полной свободой его управления.

**Comment by waterplea** [comment]
Ну да, тогда тебе нужен свой диалог. Только не для каждого, а один, который будет принимать все необходимые тебе параметры кастомизации и реагировать на них так, как тебе нужно. Сделаешь свой сервис, с параметрами:
```ts
interface MyOptions {
  offsetTop: number;
  borderRadius: number;
  background: string;
  // ...
}
```
И твой компонент диалога будет эти параметры принимать, рисовать всё как тебе надо, и содержать `polymorpheus-outlet` чтобы отображать контент, который был передан первым аргументом в сервис.

**Comment by alex-jss** [comment]
@waterplea Думал создать одну службу для всех пользовательских диалогов, но как в службу в `PolymorpheusComponent` передать необходимый компонент, так и не смогу разобраться.
На сколько понимаю `tui-field-error` все равно не будет работать?
Если имеется все же какое-то решение полноценной работы  `tui-field-error` в пользовательском диалоге, могли бы вы показать пример как это можно добиться на моем [примере](https://github.com/alex-jss/test-taiga-modal)? Обновил свой пример, добавил второе пользовательское окно.
Очень надеюсь на вашу помощь, намучался уже с пользовательским диалогом (

**Comment by waterplea** [comment]
Попробую найти время на следующей неделе, когда будет отпуск, сейчас совсем забегался.

**Comment by waterplea** [comment]
Привет. Извини, совсем нет времени сделать нормальный пример. Попробую последний раз словами пояснить:

![image](https://user-images.githubusercontent.com/11832552/184602392-df195f89-622e-4fc0-a573-ef6380fdfce2.png)

То, что я обвёл красной рамочкой — это **содержимое** диалога, оно передаётся первым аргументом в `dialogService.open` метод. То, во что это содержимое вставляется — это **компонент** диалога. Создавать свои компоненты диалога с их сервисами, как ты сделал, надо если тебе нужна какая-то особая анимация открытия/закрытия, отступы, скругления и тому подобное. Это **не нужно** делать под каждое конкретное **содержимое**. Это делается один раз под все диалоги с общим поведением, и потом в `open` передаются уже различные содержимые (к примеру, форма с двумя полями, как у тебя). Если тебе хочется эту форму переиспользовать, то её тоже можно сохранить в компонент — в `open` можно передать компонент, как в [этом примере](https://taiga-ui.dev/components/dialog#data).

**Тем не менее**, я смог воспроизвести твой баг и при правильном использовании, так что сделал на [него ПР](https://github.com/Tinkoff/taiga-ui/pull/2368), в 2.60.0 починится.
