### ISSUE TITLE
🐞 - 

### ISSUE THREAD

**Issue by AleksandraMoiseeva** [Tinkoff/taiga-ui#1338]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-commerce

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter-xr5eds?file=src%2Fapp%2Fapp.module.ts

### Description

If I would like to disable the cvc field in the InputCardGrouped component, component looks like it’s pre-filled and when I click the clear button, the cvc field is enabled again.

Prefilled cvc value should not affect raising placeholder/cleaner appearance and should not be cleared by clicking on cleaner.

### Angular version

12.0.5

### Taiga UI version

2.28.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
@AleksandraMoiseeva Hello, please record video for me about what do you mean

**Comment by AleksandraMoiseeva** [comment]
https://stackblitz.com/edit/taiga-starter-xr5eds?file=src%2Fapp%2Fapp.module.ts
