### ISSUE TITLE
📚 - Missing html code in basic example of InputInline

### ISSUE THREAD

**Issue by VictorienTardif** [Tinkoff/taiga-ui#1357]
### What is the affected URL?

https://taiga-ui.dev/components/input-inline

### Description

Just click on the `HTML` tab, you'll see that there's `LESS` code instead.

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Looks like a simple mess-up. A PR is very welcome :)
