### ISSUE TITLE
🤖 - Investigate some problems with E2E

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#1371]
### Description

Flaky tests

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/12021443/161498063-49ef3f69-becc-418a-af8d-7fade68e3818.png">

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/12021443/161498279-3efed194-13bf-4921-a0bf-4ab2a9414591.png">

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/153618649-ae1d1d61-6e47-450a-9485-be9b45aa6da3.png)

![image](https://user-images.githubusercontent.com/12021443/153618668-899effba-4300-4526-94b8-d2a7de1d2529.png)

![image](https://user-images.githubusercontent.com/12021443/153618690-44352644-d2f2-4490-b785-709f348c4701.png)

**Comment by splincode** [comment]
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/12021443/153623322-7474305f-948e-4761-ac23-953d80ebe1e8.png">

**Comment by splincode** [comment]
add when headless mode

```
[contenteditable=true] {
    caret-color: transparent;
}
```

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/153706567-88bf6f3e-644a-4e3d-9852-54bec6059b2f.png)

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/153710496-5ab6681e-cc3a-407d-943c-a05852a648ef.png)

**Comment by splincode** [comment]
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/12021443/154251516-07db8029-76b8-4ea9-ad18-01b3d2c005a3.png">

**Comment by splincode** [comment]
<img width="872" alt="image" src="https://user-images.githubusercontent.com/12021443/154482329-6b99e4b9-8fd4-47f6-8670-dbfcb235c5b3.png">

![image](https://user-images.githubusercontent.com/12021443/154482376-3c06999d-9a61-4fe0-9389-287d3117c9d3.png)

**Comment by splincode** [comment]
problem with `waitAllRequests`

<img width="973" alt="image" src="https://user-images.githubusercontent.com/12021443/155513080-fbca3f3e-fd13-4ca3-a463-f30ac5c18f5c.png">

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/156349806-0f8bd12f-0240-4359-ab2f-c27cbd03f5b2.png)

**Comment by splincode** [comment]
Link: https://github.com/Tinkoff/taiga-ui/pull/1504

**Comment by nsbarsukov** [comment]
Problem with dropdown.
It has happened in two (not connected between each others) PRs.

![multiSelectDropdown](https://user-images.githubusercontent.com/35179038/158324805-5745b269-b4b0-4831-9096-4228592673c2.png)

**Comment by splincode** [comment]
Problem with only this case
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/12021443/161498063-49ef3f69-becc-418a-af8d-7fade68e3818.png">

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/161563884-e54481b4-cc63-41cb-8160-6bd2b64693a9.png)

**Comment by splincode** [comment]
flaky 

<img width="863" alt="image" src="https://user-images.githubusercontent.com/12021443/162161031-4c957930-1c19-494f-857d-60bf5097ea6d.png">

**Comment by splincode** [comment]
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/12021443/163768021-d9f6dbda-bcfb-4c03-b388-956696be706c.png">

**Comment by splincode** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/12021443/171620053-1f974137-304b-4d60-af53-b1ee9c4f2db7.png">

**Comment by splincode** [comment]
Fixed
