### ISSUE TITLE
🐞 - MultiSelect arrow doesn't get 't-icon_rotated' class after cleaner click

### ISSUE THREAD

**Issue by Formaceft** [Tinkoff/taiga-ui#1373]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/multi-select/API?tuiMode=null&tuiTextfieldCleaner=true

### Description

When you use cleaner in multiselect, it opens, but arrow doesn't rotate.

### Angular version

12.2.11 (never mind)

### Taiga UI version

2.33

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Sorry, I can't reproduce, what do you mean?

**Comment by Formaceft** [comment]
Chose 1-2 values, then clean them all from common cleaner. Dropdown will be opened, but arrow won't change.

**Comment by splincode** [comment]
https://user-images.githubusercontent.com/12021443/153820012-90682769-15b5-46dd-8eae-02bb40260eec.mov

**Comment by waterplea** [comment]
Also from the looks of it, left padding is small for input. It should be 16px for input and 12px for tag.

**Comment by splincode** [comment]
@waterplea what do you mean about `left padding`?

<img width="1375" alt="image" src="https://user-images.githubusercontent.com/12021443/154214765-e4136495-0d55-4b64-8833-02625de157e0.png">

Do you mean remove `-4px` of margin?

<img width="1385" alt="image" src="https://user-images.githubusercontent.com/12021443/154214853-ee73683c-fa30-4e77-811f-811a0e636873.png">
