### ISSUE TITLE
🐞 - Dot is no longer entered in inputNumber as a decimal separator

### ISSUE THREAD

**Issue by helennik** [Tinkoff/taiga-ui#1426]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Description

If you insert a number with a dot or write a dot in inputNumber, then the separator will not be entered

### Angular version

10.2.3

### Taiga UI version

2.34.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
@helennik hello, please provide a minimal reproduce on stackblitz for help me

**Comment by waterplea** [comment]
Reproduction is unnecessary. Before internationalization of number format it was possible to enter both dot and comma as decimal separator. We need to somehow return this behaviour, probably if neither dot nor comma are used as thousand separator.
