### ISSUE TITLE
🚀 - Add a token to be used as a default currency in `tui-money`

### ISSUE THREAD

**Issue by toolstik** [Tinkoff/taiga-ui#1433]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

addon-commerce

### Description

Hello! Every time I use `tui-money` I have to set an input value for the currency (if it is other than RUB). It would be great to have a token like `TUI_CURRENCY` that will be used as a currency value if the input value is not defined

Just let me know if this is applicable and I will create a PR for it

**Comment by waterplea** [comment]
Yes, it's something we plan to have, but not just currency, but all default settings of `Money` component. It's a part of this ongoing effort:
https://github.com/Tinkoff/taiga-ui/issues/133

A PR is very welcome, you can check out linked issue for recent examples. It also makes sense to add DI configuration to `InputNumber` while you're at it 😉

**Comment by splincode** [comment]
@toolstik Please excuse me, I was in a hurry as this PR was already in some state. 
could you take a look and review? https://github.com/Tinkoff/taiga-ui/pull/1434
