### ISSUE TITLE
🐞 - documentRef.createRange is not a function at new TuiLineClampDirective on server side (SSR)

### ISSUE THREAD

**Issue by VictorienTardif** [Tinkoff/taiga-ui#1444]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Description

When rendering a `<tui-line-clamp>` on server side, I get the following error: `documentRef.createRange is not a function`.

### Angular version

13.2.0

### Taiga UI version

2.35.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by VictorienTardif** [comment]
(Note that I do use `@ng-web-apis/universal`, I tried both your version, `1.9.5`, and the latest, `2.0.0`)

**Comment by waterplea** [comment]
@VictorienTardif thank you for the report. We will patch this on our side but the issue is coming from `DOCUMENT` token from Angular so if you want this to be fixed at the root cause, it's best to file an issue with Angular as well.

**Comment by VictorienTardif** [comment]
https://github.com/angular/angular/issues/45163
