### ISSUE TITLE
🐞 - select dropdown opening speed is proportionally decreasing with increasing amount of options

### ISSUE THREAD

**Issue by EricPoul** [Tinkoff/taiga-ui#1448]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-a3zwn8-ffwwkn?file=src%2Fapp%2Fapp.component.html

### Description

I noticed that the speed of select dropdown opening is getting slower if I pass more options. Even if I pass just 50 options I start feeling an opening lag. It can be fixed by virtual-scroll but I'd prefer not to add the virtual-scroll on each select with 20-100 elements.
I think it's a performance issue because in reproduction there are simple options without logic.

### Angular version

13.1.3

### Taiga UI version

2.33

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
I think you can use virtual scroll in your example

**Comment by EricPoul** [comment]
If I use `virtual-scroll` I need to set the precise height so I can have two identical select with a different dropdown height. Also if `tui-dropdown-box` adjusts to the screen size `virtual-scroll` doesn't. When height of `tui-dropdown-box` less than `virtual-scroll` height double scroll pops up.
And again, it looks too much to add virtual scroll for 50-100 items.

**Comment by EricPoul** [comment]
I recently noticed that opened chrome devtools dramatically increased the time of dropdown opening. Without chrome devtools opened it still feels laggy for 1k items but it does feel smooth for 200 items. We could close this issue.

**Comment by waterplea** [comment]
One other thing is to check on prod mode and not on dev mode because dev mode runs change detection twice + has some debug related stuff that drags performance down.
