### ISSUE TITLE
🐞 - color picker is not working

### ISSUE THREAD

**Issue by sarvarkhuja** [Tinkoff/taiga-ui#1495]
### Which @taiga-ui/* package(s) are the source of the bug?

core, kit, addon-editor

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-rcgvzw-specqu

### Description

Hi 👋 

This Stackblitz was cloned from the color picker section of the documentation. I'd appreciate it if you could help me with the usage of this component

best regards

### Angular version

13.1.1

### Taiga UI version

2.28.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
Thanks for the bug report!

We forgot to add import of the `TuiInputColorModule` to stackblitz files.
Just add import of it to your opened stackblitz.

I also opened PR to fix this problem.
