### ISSUE TITLE
📚 - Website not reachable

### ISSUE THREAD

**Issue by arndwestermann** [Tinkoff/taiga-ui#1499]
### What is the affected URL?

https://taiga-ui.dev/

### Description

Hello guys,

since yesterday your website isn't reachable anymore. Any particular reason for that?

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by viorelrj** [comment]
Can confirm, can't access it as well.

**Comment by loxy** [comment]
Here too (Germany). Probably because of Ukraine conflict...

**Comment by arndwestermann** [comment]
I thought so, thank you for your efforts!

**Comment by arndwestermann** [comment]
Everything is up and running, thank you @waterplea !

Issue can be closed!
