### ISSUE TITLE
🐞 - TuiInputDateTime min max has not the expected type

### ISSUE THREAD

**Issue by arndwestermann** [Tinkoff/taiga-ui#1514]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://github.com/arndwestermann/tui-datetime-example

### Description

Hello guys,

I encountered a problem, where the min max input of the TuiInputDateTime is not matching the the [docs](https://taiga-ui.dev/components/input-date-time/API?tuiMode=null).
There it says that the Type for min max is `TuiDay | [TuiDay, TuiTime]` but providing this type results in an error

```
Error: apps/client/src/app/app.component.html:3:55 - error TS2322: Type 'TuiDay | [TuiDay, TuiTime]' is not assignable to type 'TuiDay'.
  Type '[TuiDay, TuiTime]' is not assignable to type 'TuiDay'.

3     <tui-input-date-time formControlName="testValue" [min]="minDatetime">
                                                        ~~~

  apps/client/src/app/app.component.ts:9:16
    9   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.




✖ Failed to compile.
```

This is my getter for the minDatetime property

```
  public get minDatetime(): TuiDay | [TuiDay, TuiTime] {
    if (this.options.min_value) {
      const date = new Date(this.options.min_value);
      const day = TuiDay.fromLocalNativeDate(date);
      const time = TuiTime.fromLocalNativeDate(date);
      return [day, time];
    }

    return TUI_FIRST_DAY;
  }
```

I also noticed, that in the installed code the type is also wrong. This is the component from my node_modules folder

```
export declare class TuiInputDateTimeComponent extends AbstractTuiControl<[TuiDay | null, TuiTime | null]> implements TuiWithOptionalMinMax<TuiDay | [TuiDay, TuiTime]>, TuiFocusableElementAccessor {
    private readonly textfieldSize;
    readonly dateFormat: TuiDateMode;
    readonly dateSeparator: string;
    readonly timeTexts$: Observable<Record<TuiTimeMode, string>>;
    readonly dateTexts$: Observable<Record<TuiDateMode, string>>;
    readonly valueTransformer: TuiControlValueTransformer<[TuiDay | null, TuiTime | null]> | null;
    private readonly textfield?;
    private month;
    min: TuiDay;
    max: TuiDay;
    disabledItemHandler: TuiBooleanHandler<TuiDay>;
    defaultActiveYearMonth: TuiMonth;
    timeMode: TuiTimeMode;
   [...]
```

### Angular version

13.2.0

### Taiga UI version

2.36.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Fixed by https://github.com/Tinkoff/taiga-ui/pull/1470 and release in v2.38.0

<img width="1178" alt="image" src="https://user-images.githubusercontent.com/12021443/160348037-2d6c981b-f0be-4bbb-aa9a-9f5cf6b6dc22.png">
