### ISSUE TITLE
🐞 - `Multiselect` dropdown jerks when using expanded="true"

### ISSUE THREAD

**Issue by vladimirpotekhin** [Tinkoff/taiga-ui#1534]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Description

https://user-images.githubusercontent.com/46284632/159659944-0da5d290-75bf-467a-9f9e-3e0820b1d075.mov

### Angular version

9>

### Taiga UI version

2.38.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by niklissad** [comment]
any updates about this bug?
