### ISSUE TITLE
🐞 - при загрузке страницы с элементом ComboBox данные из списка не выбираются, если ComboBox про кручен до конца страницы и список элементов разворачивается в верх.

### ISSUE THREAD

**Issue by v-v-kuznetsov** [Tinkoff/taiga-ui#1570]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Description

 1)  Загрузить страницу с элементом ComboBox, прокрутить до конца страницы, нажать на стрелку, элементы списка выведены вверх ; 
2)  Выбрать элемент из списка.  

ОР В ComboBox отобразиться выбранный пунк 

ФР В ComboBox отображается предыдущее значение

Видео воспроизведения во вложении.

![image (4)](https://user-images.githubusercontent.com/102601364/160622331-b4ded916-2f53-42ae-bd0d-59fe9165896d.png)
![image (3)](https://user-images.githubusercontent.com/102601364/160622336-65f0ce95-d990-4c8a-8b31-c0ac8237de48.png)

https://user-images.githubusercontent.com/102601364/160622376-67fb2fb0-4329-4324-ab5e-9e887406ebe0.mp4

.

### Angular version

2.38.0

### Taiga UI version

2.38.0

### Which browsers have you used?

- [x] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [X] Android

**Comment by vladimirpotekhin** [comment]
In a personal conversation, we found out that the problem is gone, I close the issue
