### ISSUE TITLE
📚 -  Failed to execute 'setEnd' on 'Range': There is no child at offset 33.

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#1576]
### What is the affected URL?

https://taiga-ui.dev/directives/dropdown-selection

### Description

<img width="1406" alt="image" src="https://user-images.githubusercontent.com/12021443/160931170-ff3912b5-57db-4ceb-90b5-25e229f9eb48.png">

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
This probably just needs an additional check + early return at some point.
