### ISSUE TITLE
🐞 - `PrimitiveTextfield` postfix/prefix input-props don't work with `text-align: right`

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#1585]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

See description

### Description

```html
<tui-primitive-textfield
    postfix="things"
    prefix="$"
    [style.textAlign]="'right'"
    [value]="30"
>
    text-align: right;
</tui-primitive-textfield>
```

<img width="338" alt="textfieldPostfixBug" src="https://user-images.githubusercontent.com/35179038/161491203-5dc5a26f-3b2b-41ae-a45e-d82f17c7a401.png">

### Angular version

any

### Taiga UI version

2.39.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Link: https://github.com/Tinkoff/taiga-ui/issues/1193

**Comment by nsbarsukov** [comment]
@splincode thanks, i did not know that the same issue already exists.

I will close my issue.
