### ISSUE TITLE
grid - adaptive layout haven't paddings

### ISSUE THREAD

**Issue by AnteaterKit** [Tinkoff/taiga-ui#160]
Hi!
I have the example with adaptive grid.
https://gist.githubusercontent.com/AnteaterKit/0f0f3fcf64d3b6db7359e8ccd4ebb83f/raw/ce7031a3148535e039d167f36c0025953b85ec1a/grid

May be add  padding-bottom and padding-top in some media queries?

<img width="1439" alt="Screenshot 2021-01-27 at 20 19 07" src="https://user-images.githubusercontent.com/5115677/106029595-4fa2af00-60de-11eb-8d76-6b4a56ad2ef5.png">
<img width="1440" alt="Screenshot 2021-01-27 at 20 19 20" src="https://user-images.githubusercontent.com/5115677/106029608-529d9f80-60de-11eb-827a-7fd924d32161.png">
<img width="1440" alt="Screenshot 2021-01-27 at 20 19 30" src="https://user-images.githubusercontent.com/5115677/106029613-53cecc80-60de-11eb-9064-9256b18b7555.png">

**Comment by waterplea** [comment]
Frankly I don't want to support those global styles as I believe it's out of Taiga UI scope and it's better to use some layout library like Tailwind. Those styles were prepared by our layout team specifically for out internal project needs and it's probably a mistake that we shipped them in public package in the first place (and not kept them in private packages). If you need this you can make a PR and we will merge it after review, but I'll close this issue so it doesn't sit in the backlog forever :)
