### ISSUE TITLE
🐞 - Since version 2.39.0 the input-tags do not have a status

### ISSUE THREAD

**Issue by loxy** [Tinkoff/taiga-ui#1618]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://github.com/loxy/taiga-input-tag-bug

### Description

Since version 2.39.0 the input-tags (also inside multi select) do not have a default status. So, something like `data-tui-host-status="default"` is missing on element.

This is not the case for the website. Don't know why.

Version 2.40.0 is also affected.

### Angular version

12.2 - 13.3

### Taiga UI version

+2.39.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Yes, sorry, the fix is coming on Monday.
