### ISSUE TITLE
typo on typography page

### ISSUE THREAD

**Issue by evoytenkoapps** [Tinkoff/taiga-ui#1623]
https://github.com/Tinkoff/taiga-ui/blob/fc0f27a3ff4d0117dcb09e51fc628550bc2589cd/projects/demo/src/modules/markup/typography/typography.template.html#L270

У вас опечатка в нескольких стилях.
Например вместо tui-text-body-m-2 нужно tui-text_body-m-2 , я находил аналогичные ошибки в других стилях.

**Comment by splincode** [comment]
Hello, you can create a pull request for help us ))
