### ISSUE TITLE
🐞 - Button "Еще" in `tui-tabs-with-more` component doesn't fit in container

### ISSUE THREAD

**Issue by mbogomazov** [Tinkoff/taiga-ui#1629]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Description

When there are many tabs, the "Еще" button does not fit into the container.
![tabswm](https://user-images.githubusercontent.com/23421487/162950036-ba732bb8-0512-4521-b1c0-7eb8281a9e05.gif)

### Angular version

12

### Taiga UI version

2.40.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I don't think this is still relevant with all the changes done to `TabsWithMore`, and it also kind of seems like an issue initially was on the CSS side of the example. If it is still reproducible on the latest version, we would need a StackBlitz to investigate. Please let us know, I'm closing it for now.
