### ISSUE TITLE
🐞 - input and suffix/postfix alignment 

### ISSUE THREAD

**Issue by Lightllord** [Tinkoff/taiga-ui#1630]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Description

there is some sort of bug with layout
![image](https://user-images.githubusercontent.com/8024934/162989407-0547a9de-a516-4abf-a5e0-5df5dfed292b.png)
![image](https://user-images.githubusercontent.com/8024934/162989436-7a5bfe49-5a1a-460b-88c4-bcc82cf38ffe.png)

### Angular version

12.69.0

### Taiga UI version

2.40.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
This is a long standing issue we've been battling to mediocre success 🙁 Whenever we get this fixed for some particular scale and DPI this brakes on the other setup. If you have any idea how to better handle this, you are very welcome to share 🙂
