### ISSUE TITLE
🐞 - missing padding between tuioption in tuidatalist if tuioption has long multiline text

### ISSUE THREAD

**Issue by helennik** [Tinkoff/taiga-ui#1687]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Description

missing padding between tuioption in tuidatalist if tuioption has long multiline text
example
![image (4)](https://user-images.githubusercontent.com/25726433/165516646-e0652a74-46b5-4b28-bbef-b3b81fdfac26.png)

expectation
<img width="464" alt="Screenshot 2022-04-27 at 12 12 35" src="https://user-images.githubusercontent.com/25726433/165516718-d9b93261-f34e-4eba-8ad8-5cd7bd92fb2f.png">

### Angular version

10.2.3

### Taiga UI version

2.43.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
We also need to fix padding around separator in optgroup.
