### ISSUE TITLE
🤖 - `@taiga-ui/testing` Make plugin for cypress screenshot tests

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#1691]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

testing

### Description

We use [cypress-image-snapshot](https://github.com/jaredpalmer/cypress-image-snapshot) to catch visual regressions during integration tests.

Unfortunately, this library is not longer supported.
It can be difficult to add new features on the basis of this plugin.

**My proposed solution:**
Use the source code of [cypress-image-snapshot](https://github.com/jaredpalmer/cypress-image-snapshot).
Move it to our `@taiga-ui/testing/cypress`-library.
Rewrite the code using Typescript. Also, make some refactoring.

Make this library publishable.

**Comment by splincode** [comment]
Is it relevant?

https://github.com/Tinkoff/taiga-ui/issues/4912

**Comment by waterplea** [comment]
I think this is not relevant anymore. Probably harnesses are the solution to it.
