### ISSUE TITLE
Close the PdfViewer with Esc key

### ISSUE THREAD

**Issue by Kaaning** [Tinkoff/taiga-ui#1700]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

Can you please make it possible (at least an option) to close the PdfViewer with Esc key ?

Thank you

**Comment by waterplea** [comment]
Definitely 🙂 I thought it was already implemented, but I was thinking about Preview. We probably need to implement some reusable solution so it's easy to toggle for custom dialogs.
