### ISSUE TITLE
🐞 - Cannot access TuiSortByDirective

### ISSUE THREAD

**Issue by nikochetov** [Tinkoff/taiga-ui#1701]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-table

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Description

ReferenceError: Cannot access 'TuiSortByDirective' before initialization error after update Taiga to latest version
![2022-04-29 13 34 16](https://user-images.githubusercontent.com/47281241/165928876-66bf9ac0-2e20-4b42-93a1-8cc3da705258.jpg)

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by jonsamwell** [comment]
Is there a work around to this while we wait for the merge?

**Comment by waterplea** [comment]
> Is there a work around to this while we wait for the release with this fix in?
> 

Isn't the latest version fixed?

**Comment by jonsamwell** [comment]
Yes sorry I've thought I upgraded but npm was playing tricks on me. Apologies!
