### ISSUE TITLE
🤖 - convert `index.ts` -> `public_api.ts`

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#1725]
### Description

![image](https://user-images.githubusercontent.com/12021443/166925335-206654ca-9e22-4b4a-b698-b569a459c212.png)

**Comment by nsbarsukov** [comment]
Should we close this issue ?

<img width="941" alt="next6" src="https://user-images.githubusercontent.com/35179038/169565189-a7c90096-221e-499b-a255-505ad9a712e9.png">

<img width="930" alt="next9" src="https://user-images.githubusercontent.com/35179038/169565201-89d1c4e3-457f-48a4-add0-e40d384f5988.png">
