### ISSUE TITLE
🚀 - Implement valueOf in TuiDay, TuiMonth, TuiYear, TuiTime 

### ISSUE THREAD

**Issue by Adrug** [Tinkoff/taiga-ui#1729]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

cdk

### Description

I just suggest to add `valueOf` implementation for each of them. This will make it easier to use comparison operators 

```
const a = new TuiTime(11, 0);
const b = new TuiTime(12, 0);
If (a < b) {
   doSometing();
}
```

**Comment by ddubrava** [comment]
I’ll work on this 👀
