### ISSUE TITLE
🚀 - Ability to change `tui-tabs` orientation 

### ISSUE THREAD

**Issue by dzolotarova** [Tinkoff/taiga-ui#1731]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

It might be useful for some applications to have the ability to change `tui-tabs` orientation (from horizontal to vertical). Something like that:
![image](https://user-images.githubusercontent.com/36307205/167109786-4b011736-4827-47fa-9679-4caa74112c30.png)

**Comment by waterplea** [comment]
Sounds reasonable. I'll ask our designer to think about this.

**Comment by theorlovsky** [comment]
@waterplea any updates here?

**Comment by waterplea** [comment]
Sorry it took this long, got shoved back by all the 3.0 work. Will be out in the next release 🎉
