### ISSUE TITLE
🐞 - `DataList` dropdowns can overlap each over

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#1733]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/data-list#complex

### Description

1. Set browser size to 1300*900
2. See last example of the [DataList](https://taiga-ui.dev/components/data-list#complex)
3. Click button

https://user-images.githubusercontent.com/35179038/167130260-22523288-86b7-49d1-865b-876ced1386a4.mov

**Need to investigate:** it can be just a problem of the documentation or bug of the `DataList`-component.

### Angular version

any

### Taiga UI version

2.44.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Native dropdowns behave the same way at low res:
![image](https://user-images.githubusercontent.com/11832552/167132130-8fc1d466-9c62-499c-83d8-eae847cec395.png)
