### ISSUE TITLE
🤖 - 3.0 migrations

### ISSUE THREAD

**Issue by waterplea** [Tinkoff/taiga-ui#1764]
### Description

Taiga UI 3.0 is coming this summer, we need to cover as many breaking changes with migrations as possible. Where migrations are not applicable we need to show some kind of instructions for manual migration if given situation is spotted in the code by our schematic.

Some things are probably never used by anyone and writing a migration for them is complex and pointless. We need to spot those things that we decide not to cover and make some blanket message to show if they happen to be spotted in code. We could leave some contact details in there if people are having troubles migrating those on their own.

I also went over all of the TODOs and changed them so all of 3.0 related ones can be found by searching for `TODO: 3.0`. We can probably remove all `@dynamic` comments after we switch to Ivy distribution as well.

# Deprecated entities

## Addons

- [x] `TUI_DEFAULT_COLOR_HANDLER`, `TuiColorHandler`, `DEFAULT_COLORS`
https://github.com/Tinkoff/taiga-ui/pull/1916
- [x] `TuiCodeEditor.open`
- [x] `CodeEditor`
- [x] `TUI_SHEET_OFFSET`
- [x] `TuiTouchMode`
- [x] `tuiResizableColumn`
#1877 
- [x] `TuiEditor`
- [x] `HongKong_dollar`
- [x] `TableComands` -> `TuiTableCommands`
- [x] TuiMoneySign
## CDK

- [x] `AbstractTuiInteractive` (many removed properties
- [x] `TuiController` -> `AbstractTuiController`
https://github.com/Tinkoff/taiga-ui/pull/1923
- [x] `TuiPortalService`
- [x] `EMPTY_VALIDATOR`
- [x] `TUI_DATE_FILLER`, `TUI_DATE_RANGE_FILLER`
#1838
- [x] date-time related deprecations
- [x] `TuiDirectiveStylesService.addStyle`
- [x] `TUI_SANITIZER`
- [x] `tuiCustomEvent`, `getClosestElement`, `padStart`, `fallbackValue` — remove in favor of native alternatives
https://github.com/Tinkoff/taiga-ui/pull/1933
- [x] `getClosestKeyboardFocusable`
- [x] `identity`
- [x] CDK enums

## Core

- [x] `TuiNotificationsModule`, `TuiNotificationsService`
- [x] `tui-group` -> `[tuiGroup]`
- [x] `tui-wrapper` -> `[tuiWrapper]`
#1877 
- [x] `CheckboxOptions`, `NotificationTokenOptions`
#1845
- [x] `TuiPrimitiveTextfieldComponent.autofilledChange`
- [x] `MEDIA`
- [x] `TuiColorDirective`
- [x] `TuiTableModeDirective`
- [x] `TuiNotificationOptions`
#1845
- [x] `TuiPluralizePipe`, `pluralize`
- [x] `TuiColor`
- [x] `colorFallback`
- [x] Core enums

## Kit

- [x] Sliders
- [x] `TuiBreadcrumbsComponent`
- [x] `TuiCalendarRangeComponent.rangeChange`
- [x] `TuiFieldErrorModule`
https://github.com/Tinkoff/taiga-ui/pull/1982
- [x] `TuiFilterByInputBase` -> `AbstractTuiFilterByInputBase`
- [x] `InputCountOptions`, `InputPasswordOptions`, `InputTimeOptions`, `RadioOptions`, `ToggleOptions`
#1827
- [x] `TuiCountryIsoCode`, `COUNTRIES`, `Country`
#1850
- [x] `TuiHideSelectedPipe` — remove second optional argument
https://github.com/Tinkoff/taiga-ui/pull/2026
- [x] `TuiProgressColorSegmentsAsyncPipe`, `TuiProgressColorSegmentsPipe`
https://github.com/Tinkoff/taiga-ui/pull/1994
- [x] `TUI_DATE_MASK`, `TUI_DATE_RANGE_MASK`
- [x] `WithDateMaskPipeConfig`
- [x] `TUI_MOBILE_AWARE`
- [x] Kit enums

## Demo

- [x] No migration is necessary, just get rid of deprecated stuff — `FrontEndExample` and `open` inside `TuiStackblitzService`

**Comment by splincode** [comment]
`ng build addon-editor`

<img width="1765" alt="image" src="https://user-images.githubusercontent.com/12021443/181739702-cc9438d3-9e3b-4da4-ad0d-23ba5043d10a.png">

`ng build addon-editor`

![image](https://user-images.githubusercontent.com/12021443/181739747-3f94355e-cefe-40d8-a8ac-174704bd21c6.png)
