### ISSUE TITLE
🤖 - [Firefox] Cookie “_ym_isad” will be soon rejected because it has the “SameSite”

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#1778]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Non-Blocking

### Description

```
Cookie “_ym_isad” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Request to access cookie or storage on “<URL>)” was blocked because it came from a tracker and content blocking is enabled.
```

<img width="1682" alt="image" src="https://user-images.githubusercontent.com/12021443/169035797-67a6a654-ca89-442d-8122-96381cf96545.png">

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
This is coming from a 3rd party analytics library, let's not pollute our changelog. I've updated it in a linked PR, warning remains there but I'm willing to close this ticket after merge.
