### ISSUE TITLE
🐞 - `AbstractTuiPortalService` Error after updating to 2.45

### ISSUE THREAD

**Issue by Sunshine6low** [Tinkoff/taiga-ui#1796]
### Which @taiga-ui/* package(s) are the source of the bug?

core, cdk

### Is this issue blocking you?

Blocking

### Description

After updating taiga-ui from 2.43 to 2.45 it doesn't starts
![Снимок экрана 2022-05-23 в 01 55 34](https://user-images.githubusercontent.com/43717688/169719467-99b51085-e00a-44b9-b0f1-332f7d77c692.png)

### Angular version

13.3.0

### Taiga UI version

2.45

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Hello, please add a repository for reproduce

**Comment by splincode** [comment]
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/12021443/169782730-e924151c-34ee-4407-b40b-ae0f232391fe.png">

Sorry, I don't see a problem

**Comment by splincode** [comment]
@waterplea what do you think?
