### ISSUE TITLE
🐞 - Scrollbar is not visible on android mobile device (its getting recognized as Ios-Device)

### ISSUE THREAD

**Issue by michael-hein** [Tinkoff/taiga-ui#1809]
### Which @taiga-ui/* package(s) are the source of the bug?

cdk

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter-5fbfwu?file=src%2Fapp%2Fapp.component.ts

### Is this issue blocking you?

Non-Blocking

### Description

When using the scrollbar (https://taiga-ui.dev/components/scrollbar) the scrollbar is not visible on some Android devices with chrome browser. (e.g. huawei honor 8x which has the useragent in chrome of 'Mozilla/5.0 (Linux; Android 10; JSN-L21) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.61 Mobile Safari/537.36' with 5 maxTouchPoints).

So the 'TUI_IS_IOS'-Providers says its an iOS-Device which is maybe not right which leads to, that there is no visible scrollbar.

Props of the scrollbar on the device
`
delegated: false;
isIos: true;
isLegacy: false;
showNative: false;
showScrollbars: false;
`

### Angular version

12.2.4

### Taiga UI version

2.46.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [X] Android

**Comment by michael-hein** [comment]
Same issue happens when using a notebook/laptop on windows which has a touchscreen (with more than 1 touchpoint) and is using the chrome-browser.

Thank you :)

**Comment by splincode** [comment]
<img width="587" alt="image" src="https://user-images.githubusercontent.com/12021443/170779837-bc38a70e-2969-458f-9b2c-bf100641e7fd.png">
