### ISSUE TITLE
🐞 - `ComboBox` + `cdk-virtual-scroll-viewport` throws "ExpressionChangedAfterItHasBeenCheckedError"

### ISSUE THREAD

**Issue by bayburin** [Tinkoff/taiga-ui#1822]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter-jyiu1c?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.css

### Is this issue blocking you?

Blocking

### Description

When using the cdk-virtual-scroll-viewport into tui-combo-box, if you quickly scroll with the mouse wheel, an error is raised: Expression has changed after it was checked. Previous value for '_focused': 'true'. Current value: 'false'. There is no error in case of slow scrolling.

The error is also raised with the example shown in the documentation (I copied the example to the stackblitz):
![Снимок экрана 2022-05-27 в 13 42 10](https://user-images.githubusercontent.com/16703823/170645670-e1cc672a-2eb7-411b-9145-dd6d2b59f46f.png)
)

### Angular version

13.2.7

### Taiga UI version

2.46.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
It reproduces only if we use **mouse wheel** (no bug if we use touchpad).

Probably, it can be somehow connected with these lines:
https://github.com/Tinkoff/taiga-ui/blob/19d7bce35a57f3c5ab641fbe56a47505d68512d6/projects/core/components/data-list/data-list.component.ts#L94-L100

**Comment by bayburin** [comment]
Also the bug is not reproduced inside the Component Dialog

**Comment by waterplea** [comment]
> Also the bug is not reproduced inside the Component Dialog

That's because dialogs use `OnPush` change detection strategy.
