### ISSUE TITLE
🚀 - Titles above barsets

### ISSUE THREAD

**Issue by gennadiipetrov** [Tinkoff/taiga-ui#1829]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

addon-charts

### Description

Hi, guys!

My UI\UX designer and I want to ask you to develop following features for BarChart component.

- titles
- strip css
- and so on

I drew all the wishes in the pictures

this

![chart1](https://user-images.githubusercontent.com/77464892/170955512-3892befb-1a2b-4979-be9d-152786dfdd4e.png)

1) Could you add title above barsets?
2) Could you add so dividers between barsets?  
2) Could you add short suffix (тыс. млн.) like this?  

and this

![chart2](https://user-images.githubusercontent.com/77464892/170955524-c9e2bc03-4556-4e4a-a634-ed10878f9d9f.png)

1) Could you add strip css effect for some barsets(not for all)?
2) Could you align X text by center or give component attr for this?  

I added 2 directives for added titles and strip effect as workaround (this directives depends on html structure and format):

```
            <tui-bar-chart
                [max]="maxX$ | async"
                [value]="barSegments$ | async"
                [collapsed]="true"
                [size]="'l'"
                [hintContent]="hint"

[barSetTitles]="titles$ | async"
[barSetLinearGradient]="from$ | async" // from index position

            ></tui-bar-chart>
```

**barSetTitles** - the directive get titles$ array and print above barsets

```
            for (let i = 0; i < this.elementRef.nativeElement.children.length; i++) {
                const span = document.createElement("span");
                const {height} = this.elementRef.nativeElement.children[i].querySelector("div").style;

                span.innerText = value[i];
                span.classList.add("bar-set-title");
                span.style.bottom = height;
                this.elementRef.nativeElement.children[i].prepend(span);
            }
```

```
    .bar-set-title {
        position: absolute;
        left: 50%;
        transform: translateX(-50%);

        font: var(--tui-font-text-xs);
        color: var(--tui-text-02);
    }
```

**barSetLinearGradient** - the directive get from$ number and make strip effect for next(after from index) barsets

```
            for (let i = 0; i < this.elementRef.nativeElement.children.length; i++) {
                if (i >= data.value) {
                    const first = this.elementRef.nativeElement.children[i].querySelector("div > tui-bar-set > tui-bar > div:nth-child(1)");
                    const second = this.elementRef.nativeElement.children[i].querySelector("div > tui-bar-set > tui-bar > div:nth-child(2)");
                    const third = this.elementRef.nativeElement.children[i].querySelector("div > tui-bar-set > tui-bar > div:nth-child(3)");

                    first.classList.add("bar-set-first");
                    second.classList.add("bar-set-second");
                    third.classList.add("bar-set-third");
                }
            }
```

```
    .bar-set-first {
        background: repeating-linear-gradient(45deg,
        var(--tui-support-01),
        var(--tui-support-01) 10px,
        var(--tui-support-02) 10px,
        var(--tui-support-02) 20px) !important;
    }
```

I use 3 section in barset thats why I repeat classList 3 times.

**Comment by waterplea** [comment]
1. As for strips, you can set any kind of color, including gradients, by just using the CSS vars, see [this example called Horizontal](https://taiga-ui.dev/components/bar-set#horizontal).
2. As for labels, you can provide an array of strings with whatever texts you like already, no need for a directive to do it.
3. Titles above bar chart is a valid feature request and it is what this issue is about for those who want to take it on :)
