### ISSUE TITLE
🐞 - 

### ISSUE THREAD

**Issue by daniilefremow** [Tinkoff/taiga-ui#1832]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Is this issue blocking you?

Non-Blocking

### Description

**Desc:**
In mobile version tui-preview componet's buttons (close, download etc.) are hidden outside the screen.

**Env:**
https://coretech-frontend.pages.devplatform.tcsbank.ru/tinkoff-ui-angular/tui-preview

**Preconditions:**
iOS or Andriod device (ex. _Iphone 13_ or _Samsung Galaxy A11_ via [Browserstack](https://live.browserstack.com/dashboard))

**Steps to reproduce:**
1. Open the env link
2. Click "Показать превью" for "Собранное превью"

**Actual result:**
Close, download and other header buttons are hidden outside the screen

![image](https://user-images.githubusercontent.com/63865492/170974685-7bcf3aff-51a5-4804-bbd1-e6663253887c.png)

**Expected result:**
All the header buttons are present on the screen

### Angular version

11.2

### Taiga UI version

1.36.2

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
it is a problem of 1.x.x.
This legacy major version is not supported.

But this bug does not exist in 2.x.x. You can just update to the fresh version of Taiga UI.
