### ISSUE TITLE
🐞 - `InputNumber` prefix is overlapped by value

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#1862]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/input-number-prefix-bug?file=src/app/app.component.html

### Is this issue blocking you?

Non-Blocking

### Description

1. Open stackblitz reproduction. It contains these lines:
```html
<tui-input-number
    [formControl]="control"
    prefix="$"
>
    Type a sum
</tui-input-number>
```
<img width="809" alt="inputNumberBug" src="https://user-images.githubusercontent.com/35179038/171842625-8063ece7-00aa-4b75-a2ee-c4055bd8d400.png">

### Angular version

any 

### Taiga UI version

2.47.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
also need to take into RTL direction

**Comment by nsbarsukov** [comment]
**Intermediate notes before weekend**
Bug start reproduces only after this PR:
https://github.com/Tinkoff/taiga-ui/pull/1349/files

Before this changes prefix works as expected.
Probably, it happens because of changes inside `value-decoration.component.ts`.

On Monday I will continue my research and try to fix bug.

**Comment by nsbarsukov** [comment]
**UPDATE:**
it works before only because the examples were initialized as
```ts
readonly example1: FrontEndExample = {
    HTML: example1Html,
    TypeScript: example1Ts,
};
```

And in the mentioned PR it was replaced by the async loading of the content:
```ts
readonly example1: TuiDocExample = {
    HTML: import('!!raw-loader!./examples/1/index.html'),
    TypeScript: import('!!raw-loader!./examples/1/index.ts'),
};
```

Need investigate why `InputNumber` does not work properly in this case.
