### ISSUE TITLE
🚀 - `PdfViewer` display message when inline PDF is disabled

### ISSUE THREAD

**Issue by fe-c** [Tinkoff/taiga-ui#1866]
### What is the affected URL?

https://taiga-ui.dev/components/pdf-viewer

### Description

Just to press any button that must show PDF.
Expected: PdfViewver with pdf in it.
Actual: pdf-file download starts.
Firefox 101, no addons. Windows 11 21H2. Google Chrome - no issue.
[Screen Record](https://disk.yandex.ru/i/OWXRlshMG5SL2g)

### Which browsers have you used?

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by fe-c** [comment]
I just found why it is - default action in Firefox was set to download for PDF files. If its can't be handled or alerted I think that it issue can be closed.

**Comment by fe-c** [comment]
Please note that I only indicated Windows. But now I checked on macOS, and I was able to reproduce this problem there.
Also note my first comment.

Reproduce on macOS 12.3, Firefox 101 :
![macOS](https://user-images.githubusercontent.com/3897693/172291281-a64d2d3d-ffef-4f5c-973c-f54f6135690e.png)

**Comment by waterplea** [comment]
There doesn't seem to be a robust way to detect this setting and since the PDF gets downloaded user is not limited in their ability to view the content. As per the first comment, I think we can close it.
