### ISSUE TITLE
🐞 - Stackblitz Taiga starter example doesn't work on last version of library

### ISSUE THREAD

**Issue by mbogomazov** [Tinkoff/taiga-ui#1890]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter-gpppe4

### Is this issue blocking you?

Blocking

### Description

When application was compiled in Stackblitz it shows error:
```
Error in turbo_modules/@taiga-ui/core@2.48.0/styles/markup/tui-group.less (1:0)
Could not import ../taiga-ui-local from /turbo_modules/@taiga-ui/core@2.48.0/styles/taiga-ui-global.less
```

### Angular version

12.2.4, 14.0.1

### Taiga UI version

2.48.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
fixed by:

https://github.com/stackblitz/core/issues/1828
https://github.com/stackblitz/core/issues/2112
