### ISSUE TITLE
🐞 - `Money`, `InputMonthRange` incorrect punctuation mark

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#1917]
### Which @taiga-ui/* package(s) are the source of the bug?

kit, addon-commerce

### Please provide a link to a minimal reproduction of the bug

__

### Is this issue blocking you?

Non-Blocking

### Description

[InputMonthRange](https://taiga-ui.dev/components/input-month-range) uses em-dash.
It should use en-dash.

[Money](https://taiga-ui.dev/components/money) uses en-dash.
It should use `&minus;`.

### Angular version

any

### Taiga UI version

any

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by zlodeev** [comment]
I'm open PR with changes asis in issue with symbol `&minus;`. 

Think right way to use hyphen-minus in numbers and math-minus as math operator. When user copies value with `&minus` then `parseFloat' and `parseInt` will return NaN. It makes not sense in number with separators, but badly for use it as pattern for all numbers.

Want to ask you about more complicated typography, like in [kontur guide](https://guides.kontur.ru/principles/typography/). Thin spaces in dates, default phone pipe and number pipe are overthinking or good practice?
