### ISSUE TITLE
📚 - `InputSlider` unexpected scroll to top of the page

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#1970]
### What is the affected URL?

https://taiga-ui.dev/components/input-slider#min-max-labels

### Description

1. Use Safari Mac OS
2. Open `InputSlider`'s example [With min and max labels](https://taiga-ui.dev/components/input-slider#min-max-labels)
3. Click on thumb of the slider

https://user-images.githubusercontent.com/35179038/174777433-e880fd30-bae4-4587-9298-78af68fad640.mov

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Could be related )
https://github.com/Tinkoff/taiga-ui/issues/1952

**Comment by nsbarsukov** [comment]
It is **only** reproducible **for Mac OS Big Sure | Safari 14.1.**

**Catalina | Safari 13.1 (no bug):**

https://user-images.githubusercontent.com/35179038/190190632-31a1ae3d-933f-4445-bc9e-1d0a31411c1d.mov


**Big Sur | Safari 14.1 (bug!):**

https://user-images.githubusercontent.com/35179038/190190939-852c9be0-904f-4ebb-bd09-d04911b469bf.mov

**Monterey | Safari 15.3 (no bug):**

https://user-images.githubusercontent.com/35179038/190191759-639ad1e7-710c-4280-9dd6-14591287c3aa.mov

**Comment by nsbarsukov** [comment]
Probably, it is just a temporary Safari bug that is already solved.

Can we close it ?
