### ISSUE TITLE
🐞 -  Virtual scroll on table not working on stackblitz.com (link from documentation)

### ISSUE THREAD

**Issue by Gordondalos** [Tinkoff/taiga-ui#1983]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Non-Blocking

### Description

Link from documentation https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts
not load table with virtual scroll
Catch Error:

Error in /turbo_modules/@angular/compiler@12.2.16/bundles/compiler.umd.js (6762:21)
Template parse errors:
Can't bind to 'itemSize' since it isn't a known property of 'cdk-virtual-scroll-viewport'.
1. If 'cdk-virtual-scroll-viewport' is an Angular component and it has 'itemSize' input, then verify that it is part of this module.
2. If 'cdk-virtual-scroll-viewport' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
tuiScrollable
class="viewport tui-zero-scrollbar"
[ERROR ->][itemSize]="45"
[maxBufferPx]="500"
[minBufferPx]="400"
"): ng:///AppModule/AppComponent.html@7:8
Can't bind to 'maxBufferPx' since it isn't a known property of 'cdk-virtual-scroll-viewport'.
1. If 'cdk-virtual-scroll-viewport' is an Angular component and it has 'maxBufferPx' input, then verify that it is part of this module.
2. If 'cdk-virtual-scroll-viewport' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
class="viewport tui-zero-scrollbar"
[itemSize]="45"
[ERROR ->][maxBufferPx]="500"
[minBufferPx]="400"
>
"): ng:///AppModule/AppComponent.html@8:8
Can't bind to 'minBufferPx' since it isn't a known property of 'cdk-virtual-scroll-viewport'.
1. If 'cdk-virtual-scroll-viewport' is an Angular component and it has 'minBufferPx' input, then verify that it is part of this module.
2. If 'cdk-virtual-scroll-viewport' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("
[itemSize]="45"
[maxBufferPx]="500"
[ERROR ->][minBufferPx]="400"
>
<table
"): ng:///AppModule/AppComponent.html@9:8
Can't bind to 'cdkVirtualForOf' since it isn't a known property of 'tr'. ("
<tbody tuiTbody>
<tr
[ERROR ->]*cdkVirtualFor="let item of data | tuiTableSort"
tuiTr
>
"): ng:///AppModule/AppComponent.html@46:20
Property binding cdkVirtualForOf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("
</thead>
<tbody tuiTbody>
[ERROR ->]<tr
*cdkVirtualFor="let item of data | tuiTableSort"
tuiTr
"): ng:///AppModule/AppComponent.html@45:16
'cdk-virtual-scroll-viewport' is not a known element:
1. If 'cdk-virtual-scroll-viewport' is an Angular component, then verify that it is part of this module.
2. If 'cdk-virtual-scroll-viewport' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("

<tui-scrollbar>
[ERROR ->]<cdk-virtual-scroll-viewport
#viewport
tuiScrollable
"): ng:///AppModule/AppComponent.html@3:4

![image](https://user-images.githubusercontent.com/7421933/175039205-19091e9c-184f-4a09-953f-2a3a5331d6e1.png)

### Angular version

12.2.16

### Taiga UI version

2.50.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I just requires scrolling module from Angular CDK. Quick fix would be to add it to all modules we have for stackblitz examples.

**Comment by vladimirpotekhin** [comment]
I close the issue, it is not reproduced in the latest version
