### ISSUE TITLE
🐞 - broken grid on xs-screen

### ISSUE THREAD

**Issue by bayburin** [Tinkoff/taiga-ui#2029]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter-w2eddh?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.css

### Is this issue blocking you?

Blocking

### Description

`tui-col-offset_md-*` class is activated on the small screen and gives an margin that should not be there
![Снимок экрана 2022-06-30 в 15 32 50](https://user-images.githubusercontent.com/16703823/176632692-7e82ccd0-8caf-42c4-9931-06d608a74553.png)

### Angular version

13.3.10

### Taiga UI version

2.46.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I'm sorry but I'll close this issue as we plan to deprecate and get rid of those grid classes. It's best to use dedicated layout CSS library or something similar. Those global classes were released in Taiga UI by accident and should have remained in proprietary package as they were designed with particular needs of our internal projects by different people from the team that supports Taiga UI.
