### ISSUE TITLE
🐞 - Chrome has incorrect behavior in iPhone for animation 

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#2067]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Non-Blocking

### Description

https://user-images.githubusercontent.com/12021443/177619733-ff859fbe-a8af-490d-a01b-762b99973adb.MOV

### Angular version

latest 

### Taiga UI version

latest 

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Seems to be not reproducible on an iPhone I have at hand.
