### ISSUE TITLE
🚀 - Templated view support in tui-input-tag

### ISSUE THREAD

**Issue by jrstnly** [Tinkoff/taiga-ui#2089]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

Implement `[valueContent]=""` input on `tui-input-tag` like what already exists on `tui-select` to support advanced values in  tag content. Functionality already exists when using data lists in the autocomplete, it just needs to be available in the tag content itself.

My specific use case for this would be the ability to automatically add tags to the server-side when an "unknown" tag is entered in the client. Storing the data as an object instead of a string would give me the ability to differentiate between the known tags and unknown.

**Comment by waterplea** [comment]
`InputTag` is a string based control, for objects you should use `MultiSelect`. Would that work for you?

**Comment by waterplea** [comment]
Closing this as no response was given for quite some time.
