### ISSUE TITLE
🐞 - skeletons color in night theme are incorrect

### ISSUE THREAD

**Issue by vemikheevdev** [Tinkoff/taiga-ui#2098]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Is this issue blocking you?

Non-Blocking

### Description

skeletons have a special _light class for use in a night theme, but it's not very convenient to add it everywhere manually. color  should change automatically depending on the theme

### Angular version

12

### Taiga UI version

2.35.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by ddubrava** [comment]
Hey! What's the expected solution to this?

After some investigation it seems we can replace a `background-color` value from `tui-skeleton:after` with a variable. And initialize it in `variables.less` and `theme-night.style.less` files. 

I would like to reuse `tui-base-09` but it doesn't work with `fade(). I also don't have any ideas on how can we convert a CSS variable to rgba. So probably I have to create sth like `tui-skeleton-bg` with rgba value.

**Comment by waterplea** [comment]
@ddubrava I believe we can just change `background-color: rgba(0,0,0,.16);` to `background-color: var(--tui-clear-hover);`, probably the only reason it was not done like that in the first place is we didn't have those CSS vars when skeletons were created.
