### ISSUE TITLE
🐞 - Strange behavior for autocomplete

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#2113]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Non-Blocking

### Description

https://user-images.githubusercontent.com/12021443/178581847-50519511-81a5-4a14-a22f-c014b84821eb.mp4

### Angular version

latest

### Taiga UI version

v2.52

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by bayburin** [comment]
**Some additional information:**
Google Chrome 103.0.5060.114
Macos Mojave 10.14.6 

html code of element:
```
<tui-input-number formControlName="standardSpeed" tuiTextfieldSize="m" postfix="км/ч">
  Нормативная скорость
  <input tuiTextfield name="standardSpeed" />
</tui-input-number>
```
