### ISSUE TITLE
🐞 - HostedDropdown 

### ISSUE THREAD

**Issue by BrothersWar** [Tinkoff/taiga-ui#2167]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter-udcr2h?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts,src%2Fdropdown%2Fdropdown.module.ts,src%2Fapp%2Fapp.component.css,src%2Fdropdown%2Fdropdown.component.html

### Is this issue blocking you?

Non-Blocking

### Description

Hello! Problem with tuiDropdownHover. When I click on the toggle inside the dropdown, the hover breaks and the dropdown doesn't close. If you click in an empty area, then hover, then remove the hover, and then hover again, then the dropdown works as expected (if you click on toggle again, everything repeats)

### Angular version

11.2.14

### Taiga UI version

2.44.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I'm not able to reproduce it in 3.0 after dropdowns got a big overhaul. Feel free to reopen if you run into it again on the 3.x release.
