### ISSUE TITLE
🚀 - Why does Taiga uses less vars for font size on data-size instead of the defined --tui-font-text-x ?

### ISSUE THREAD

**Issue by Yohandah** [Tinkoff/taiga-ui#2172]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

core

### Description

I'm trying to override the overal theme of TaigaUI and doing so I redefined all the --tui-font-text vars like this

``` 
...
--tui-font-text-m: normal 1.25rem var(--tui-font-text);
... etc
```

Then the S button `<button tuiButton size='s'></button>`  uses `--tui-font-text-s` but the M button `<button tuiButton size='m'></button>` doesn't use `--tui-font-text-m` but uses the less var `@font-size-large`. 
Why is that ? I am not able to override this value.

**Resulting in compiled**
![Inkedimage (4)_LI](https://user-images.githubusercontent.com/15921402/180234996-d62461b4-d1b1-418d-be45-b15c0078c567.jpg)

**Code responsible for this : [button.style.less](https://github.com/Tinkoff/taiga-ui/blob/main/projects/core/components/button/button.style.less)**

![image](https://user-images.githubusercontent.com/15921402/180234549-3d4dc542-98db-4e66-9153-d42fffad940a.png)

**Comment by Yohandah** [comment]
@splincode Thank you for the reactivity !!! Amazing. 
Do you think it could be a great idea to do this globally in Taiga so it becomes more customizable ? For example there's the same issue with [toggle.style.less](https://github.com/Tinkoff/taiga-ui/blob/main/projects/kit/components/toggle/toggle.style.less)

![image](https://user-images.githubusercontent.com/15921402/180725707-a5902b47-395d-4719-8654-4bdb39f583f8.png)

**Comment by splincode** [comment]
@Yohandah Hello, you can create a new issue with all the places we could fix ))
