### ISSUE TITLE
🐞 - Angular element + shadowDom инкапсуляция ломает взаимодействие с модальными окнами и инпутами 

### ISSUE THREAD

**Issue by seryoga279** [Tinkoff/taiga-ui#2223]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://github.com/seryoga279/tui-encapsulation

### Is this issue blocking you?

Blocking

### Description

При использовании shadowDom инкапсуляции внутри custom-elements, как правило воспроизводиться до первого взаимодействия с открытым модальным окном

-  в случайном порядке переключаются фокус между элементами
![gif_1](https://user-images.githubusercontent.com/6993892/181304024-2900020c-9dbd-4ea1-a6ff-db0db5f7b30b.gif)

- закрываются модальные окна при взаимодействии с ними
![gif_2](https://user-images.githubusercontent.com/6993892/181304997-5bef418a-9e8e-4c22-8f7d-c7d8cb9b4571.gif)

- на закрываются дропдауны у элементов
![gif_3](https://user-images.githubusercontent.com/6993892/181305252-1a2f317a-bab6-43c7-ab7c-7ef2e76a16f8.gif)

### Angular version

13.3.11

### Taiga UI version

2.54.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
v2.x
