### ISSUE TITLE
🐞 - The following provided properties are not animatable: overflow

### ISSUE THREAD

**Issue by magicbright100** [Tinkoff/taiga-ui#2247]
### Which @taiga-ui/* package(s) are the source of the bug?

core, kit, cdk

### Is this issue blocking you?

Non-Blocking

### Description

<img width="552" alt="image" src="https://user-images.githubusercontent.com/31839812/181782426-1ecc777e-40ea-470f-b3dd-6e61a92cbdde.png">

Warnings in browser console. There is a selection on the page where the layout of the option template is larger than the block size.

### Angular version

14.0.0

### Taiga UI version

2.54.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I am closing this as it is working as expected. It's not on [the list](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties), but it works, at least in Chrome:
https://codepen.io/waterplea/pen/PoRJEvP

I believe we need it so scrollbars don't appear in dialogs during animation.
