### ISSUE TITLE
🐞 - Loader doesn't work in dialog

### ISSUE THREAD

**Issue by expdts** [Tinkoff/taiga-ui#2252]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-dialog-loader-ll929n?file=src%2Fapp%2Fapp.component.ts

### Is this issue blocking you?

Blocking

### Description

The loader does not shut down in the dialog box.

Click the 'test' button in the example, the loader will open and close.
Open the dialog box and click the 'test' button, the loader closed only when the mouse is clicked or the 'esc' key is pressed.

Which browsers have you used?
- Yandex

### Angular version

13.3.5

### Taiga UI version

2.56.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
This is expected. All Taiga UI components are **OnPush** and in case of dialogs this effectively makes your components **OnPush** as well (because parent component is **OnPush**). You need to inject `ChangeDetectorRef` and call `markForCheck()` in your `setTimeout` callback.

**Comment by splincode** [comment]
@expdts https://stackblitz.com/edit/taiga-dialog-loader-ll929n-pqb3w7?file=src%2Fapp%2Fdialog%2Fdialog.component.ts
if you want to manually manage change detection

<img width="317" alt="image" src="https://user-images.githubusercontent.com/12021443/182123919-a6f25f4c-1cc8-47ef-bccf-63c82ee07786.png">

**Comment by waterplea** [comment]
Dialogs host was since then made `Default` so now it's on you and your component to use either `Default` or `OnPush`.
