### ISSUE TITLE
🚀 - Add token for dialog options

### ISSUE THREAD

**Issue by festim-prebreza** [Tinkoff/taiga-ui#2267]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

core

### Description

It would be a nice feature if we could have the option to configure all dialogs globally by providing a value for an injection token

**Comment by waterplea** [comment]
It's not a well-known fact, but that fancy new `inject` function from Angular 14 works in global services even in older versions (I believe every Ivy one, but in Angular 12 and above it definitely works). So this is a pretty easy feature to implement:

```ts
@Injectable({ providedIn: `root` })
export class TuiDialogService extends AbstractTuiDialogService<TuiDialogOptions<any>> {
    protected readonly component = DIALOG;
    // Just add token instead of constant for defaults and inject it:
    protected readonly defaultOptions: TuiDialogOptions<any> = inject(TUI_DIALOG_OPTIONS);
}
```

P.S. If it doesn't work in current Angular 9 versions of Taiga UI (2.x) then it's going to be added in 3.0 only.
