### ISSUE TITLE
🐞 - in `InputNumber` after entering the second comma the carriage will move to the previous character

### ISSUE THREAD

**Issue by dzolotarova** [Tinkoff/taiga-ui#2268]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Non-Blocking

### Description

In `InputNumber` after entering the second comma the carriage will move to the previous character. Steps to reproduce:
1. Click `InputNumber`
2. Enter a comma (or dot)
3. Enter a comma (or dot) again
The carriage will move to the previous character.

[Taiga UI_ InputNumber.webm](https://user-images.githubusercontent.com/36307205/182578719-2d4008f3-73dc-468d-882d-7ec6bacc4191.webm)

### Angular version

14.1.0

### Taiga UI version

2.44.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by theorlovsky** [comment]
this bug can be seen on the latest version as well (v2.57.0 at the time of writing)
https://taiga-ui.dev/components/input-number/API?tuiMode=null

**Comment by waterplea** [comment]
This issue is pretty superfluous since why would you press another decimal separator when you just did? Also it's an issue with mask which is a 3rd party library that we plan on changing completely in the next quarter. Therefore I'll close this ticket as no fix plan for now, sorry if it causes you inconvenience.

**Comment by theorlovsky** [comment]
it is actually the first comma that worries me, because it deletes the already present `0` 🙂

but it's totally valid about the 3rd party package, thanks for looking into it anyway 🙌
