### ISSUE TITLE
🐞 - Background-color заголовков на нескольких строчках наезжает на текст

### ISSUE THREAD

**Issue by EgiazaryanAram** [Tinkoff/taiga-ui#2335]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-editor

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/editor-new

### Is this issue blocking you?

Non-Blocking

### Description

Заливка наезжает на текст соседних строк:
1. Добавить в эдиторе заголовок(например, subtitle) на две-три строки
2. Залить background-color любым цветом

### Angular version

11.2.11

### Taiga UI version

2.55.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
@waterplea @EgiazaryanAram I can't reproduce

<img width="565" alt="image" src="https://github.com/Tinkoff/taiga-ui/assets/12021443/1cea45ef-f710-4c0d-83cf-a2aa5a83673b">

**Comment by vladimirpotekhin** [comment]
The bug is no longer reproduced

**Comment by splincode** [comment]
Fixed by https://github.com/Tinkoff/taiga-ui/pull/4428/files
<img width="735" alt="image" src="https://github.com/Tinkoff/taiga-ui/assets/12021443/7c24ab56-4e97-4699-b0d5-3a926e4f03da">
