### ISSUE TITLE
🐞 - Character descenders overflow the line

### ISSUE THREAD

**Issue by YuliaTsareva** [Tinkoff/taiga-ui#2374]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/form (check first input)

### Is this issue blocking you?

Non-Blocking

### Description

Characters like "y", "p", "g" (i.e. which have descenders) are not fully visible in field placeholders (at least in `tui-input`).

<img width="200" alt="Снимок экрана 2022-08-15 в 17 28 24" src="https://user-images.githubusercontent.com/8158578/184655257-4ca6d33c-f55f-4010-a19e-5c66ec324b60.png">

### Angular version

14.1.1

### Taiga UI version

2.58.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Not reproduce in v3
