### ISSUE TITLE
🐞 - List of langages made fixed in typings. Can't add new languages for i18n.

### ISSUE THREAD

**Issue by hheexx** [Tinkoff/taiga-ui#2381]
### Which @taiga-ui/* package(s) are the source of the bug?

i18n

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Blocking

### Description

@splincode,

in commit https://github.com/Tinkoff/taiga-ui/commit/4e1b70e838765bfe2d836b5c5c58d80337d2a069 you have made list of languages finite in typings in file language-names.d.ts.

Now when we add new custom language we break the typings and can't compile.

### Angular version

14.1.0

### Taiga UI version

2.58.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [X] Linux
- [X] iOS
- [X] Android

**Comment by splincode** [comment]
Hello, I'm sorry for that! Could you add please minimal github repo for reproduce?

**Comment by hheexx** [comment]
https://stackblitz.com/edit/taiga-starter-zlgfja?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Flanguages%2Fserbian%2Fserbian.ts
