### ISSUE TITLE
🐞 - @taiga-ui/i18n dependency problem

### ISSUE THREAD

**Issue by hheexx** [Tinkoff/taiga-ui#2383]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Non-Blocking

### Description

@taiga-ui/core depends on @taiga-ui/i18n.
But dependency is not to specific version same as core but instead has ^ witch means npm pulls latest version.

![image](https://user-images.githubusercontent.com/103767/184884113-4288a068-8c80-40a4-ade6-27bababedcdb.png)

i18n types differ between version a lot and that creates all sorts of random typing problems

### Angular version

14.1.0

### Taiga UI version

2.60.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [X] Linux
- [X] iOS
- [X] Android

**Comment by hheexx** [comment]
Why not?

**Comment by splincode** [comment]
Because we have correct dependency in package 
https://github.com/Tinkoff/taiga-ui/blob/main/projects/core/package.json#L18

**Comment by hheexx** [comment]
but ^ means it will get the latest, not the one that is specified

**Comment by splincode** [comment]
fixing the version is bad practice, if you need fix version inside your project, you can fix it in your project

``` json5
"dependencies": {
  "@taiga-ui/core": "^2.60.0",
  "@taiga-ui/kit": "^2.60.0",
  "@taiga-ui/i18n": "2.52.0" // <- also you need re-update your package-lock.json file for fixing it
}
```

**Comment by hheexx** [comment]
@splincode It's internal library of your project and I see no reason why would somebody want to change the version.

Currently simple npm update breaks taigaui in a hard to debug way. I lost a lot of time on this.


At least add @taiga-ui/i18n to a documentation as a standard way of installing taiga.

**Comment by splincode** [comment]
@vladimirpotekhin @nsbarsukov @waterplea what do you think about this?

**Comment by splincode** [comment]
won't fix
