### ISSUE TITLE
🚀 - How to close Preview programmatically?

### ISSUE THREAD

**Issue by offs-bach** [Tinkoff/taiga-ui#2406]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

Don't known / other

### Description

🚀 - How to close Preview programmatically?

Have you even think about to close Preview when clicking on the overlay?

**Comment by waterplea** [comment]
I don't think it makes sense to close it on click to overlay since it will be easy to close it by accident, misclicking the buttons. To close it programmatically you need to terminate a subscription, like with all other modals in Taiga UI.
