### ISSUE TITLE
🐞 - `InputNumber` allows to exceed JS number limitations

### ISSUE THREAD

**Issue by waterplea** [Tinkoff/taiga-ui#2421]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Non-Blocking

### Description

We should limit `min`/`max` so that we do not exceed `number` type in JavaScript until we add `BigInt` option or other solution to giant sums:

```ts
    @Input()
    @tuiDefaultProp()
    min = -Infinity;

    @Input()
    @tuiDefaultProp()
    max = Infinity;
```

### Angular version

any

### Taiga UI version

any

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
maybe add `tui-input-number[bigInt]` directive for it

```html
<tui-input-number 
    formControlName="testValue" bigInt>
    Type a sum
</tui-input-number>
```
