### ISSUE TITLE
🚀 - Dialog OnPush

### ISSUE THREAD

**Issue by festimprebreza** [Tinkoff/taiga-ui#2491]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

core, cdk

### Description

This is more of a question than a feature request. I wanted to know why the Dialog Host and the Dialog components use `OnPush`? This effectively forces us to use `OnPush` on each component that is projected into a dialog. I understand that the whole library spreads this `OnPush` culture, but when there are some huge components (which there are in existing projects that might migrate to your library), forcing change detection just makes for worse code. 
OnPush is preferred for Pure (Dumb) components usually, and in dialogs there usually are some Wrapper (Smart) components that `Default` change detection strategy might be a better use for them. Their children then could be OnPush thus reducing the change detection cycle time. Looking forward to your answer!

**Comment by waterplea** [comment]
To make them `Default` we would need to make `DialogHost` and `Root` both use `Default` strategy. I'll see if it doesn't hurt us that much because giving an option to the user is probably better than forcing them to use `OnPush`. Taiga UI is rather opinionated regarding best practices :)
