### ISSUE TITLE
🐞 - [v3] "TuiDropdownControllerDirective" missing from "@taiga-ui/core" package

### ISSUE THREAD

**Issue by hakimio** [Tinkoff/taiga-ui#2513]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Blocking

### Description

For some reason `TuiDropdownControllerDirective` is not included in `@taiga-ui/core` package.

![image](https://user-images.githubusercontent.com/768105/187380551-2d463d34-4da5-468d-b692-e5a0c9a8a236.png)

**EDIT:**
Seems to be removed in [PR #2389](https://github.com/Tinkoff/taiga-ui/pull/2389/files#diff-027ede7de7b90b1f13991dab4d8e18e906d976a04089e2af24245f682bd9c7bcL3)
I guess we are supposed to be using `TuiDropdownOptionsDirective` instead now.
Maybe [the documentation](https://taiga-ui.dev/next/directives/dropdown-controller/Setup) should be updated?
Also, `TuiHintOptionsDirective` is missing from the latest release.

### Angular version

14.2

### Taiga UI version

3.0.0-rc.5

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Please, use `ng update` for run migration script

Renamed:
`TuiDropdownControllerModule` -> `TuiDropdownModule`

**Comment by hakimio** [comment]
@splincode any idea when the next v3 RC release will happen? Hint controller was also removed, but `TuiHintOptionsDirective` is not in the latest release.

**Comment by hakimio** [comment]
Also, what happened to global styles? `node_modules/@taiga-ui/core/styles/taiga-ui-global.less` doesn't seem to exist anymore, but the docs are still referring to it.

**Comment by hakimio** [comment]
@splincode do you have to install `@taiga-ui/styles` separately now?

**Comment by splincode** [comment]
if you use `ng update` then no

**Comment by hakimio** [comment]
Seems to be an issue on your side:

![image](https://user-images.githubusercontent.com/768105/187401506-efc32a56-c6f4-4bb8-b5cb-5b60dc8dd018.png)

**Comment by splincode** [comment]
@hakimio try rc.6

**Comment by hakimio** [comment]
@splincode It works well now.

@waterplea you've over-engineered the drop-down and hint directives to the max. Thanks for providing a very good example how Angular DI can be used to split complex component :)

**Comment by waterplea** [comment]
> @splincode It works well now.
> 
> @waterplea you've over-engineered the drop-down and hint directives to the max. Thanks for providing a very good example how Angular DI can be used to split complex directive :)
> 

Thank you 🙂 I'll definitely make an article or a talk on some conference about hints and decomposition.

**Comment by hakimio** [comment]
@waterplea subscribed to you on medium and looking forward to the article :)
