### ISSUE TITLE
🐞 -  @taiga-ui/addon-mobile has missing dependencies @angular/cdk/scrolling

### ISSUE THREAD

**Issue by Kulikov17** [Tinkoff/taiga-ui#2517]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-mobile, Don't known / other

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Blocking

### Description

When i try to run the project i get an error:
```
     throw new Error(`The target entry-point "${invalidTarget.entryPoint.name}" has missing dependencies:
            ^

Error: The target entry-point has missing dependencies:
 - @angular/cdk/scrolling
```
@angular/cdk is installed, @angular/cdk/scrolling is in node_modules.
I use build system NX and run the project using the command "nx run serve".
I tried to pick up the packets with "postinstall": "ngcc --async", but it didn't work out.

### Angular version

13.3.11

### Taiga UI version

2.62.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
![image](https://user-images.githubusercontent.com/12021443/187421448-c6021971-b20c-4290-8915-54dd51dd05cc.png)
