### ISSUE TITLE
🐞 - Input style bug when autofill class is added

### ISSUE THREAD

**Issue by Blend-Rugova-KodeLabs** [Tinkoff/taiga-ui#2560]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Non-Blocking

### Description

```
.autofill(@mode:default) {
    &:-webkit-autofill,
    &:-webkit-autofill:hover,
    &:-webkit-autofill:focus {
        border-radius: inherit;
        color: inherit !important;
        background-color: transparent !important;
        -webkit-text-fill-color: transparent !important;

        & when (@mode = default) {
            border-color: var(--tui-autofill);
            -webkit-box-shadow: 0 0 0 100rem var(--tui-autofill) inset !important; // to overlay native background
        }

        & when (@mode = dark) {
            border-color: var(--tui-autofill-night);
            -webkit-box-shadow: 0 0 0 100rem var(--tui-autofill-night) inset !important;
        }
    }
}
```

The line that is causing the issue:

 -webkit-text-fill-color: transparent !important;
 
This was added a month ago in another fix by @splincode to fix another bug with card number autofill but it is making the value of all inputs invisible when using autofill.

Here is a image of a case

![image](https://user-images.githubusercontent.com/95361223/187927978-bff61dcd-b6d2-4051-8131-55ace5c2260f.png)

### Angular version

14.1.1

### Taiga UI version

2.58.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
try on version 2.62, all the same?

**Comment by Blend-Rugova-KodeLabs** [comment]
@splincode we have update now to 3.0 and it seems to be fixed!
