### ISSUE TITLE
🐞 - `InputMonth` ReactiveForms with value got undefined

### ISSUE THREAD

**Issue by rendiriz** [Tinkoff/taiga-ui#2566]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter-lah46q

### Is this issue blocking you?

Non-Blocking

### Description

```
readonly testForm = new FormGroup({
  // testValue: new FormControl(null), // working
  testValue: new FormControl('2022-08-01'), // not working
  // testValue: new FormControl('2022-08'), // not working
  // testValue: new FormControl(new Date()), // not working
});
```

Here is a image of a case
![22-09-02-02](https://user-images.githubusercontent.com/16224915/188052186-e46bafd2-b03e-423e-9327-2c26b6de1fd9.PNG)

### Angular version

12.2.4

### Taiga UI version

2.26.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by vladimirpotekhin** [comment]
Hi, @rendiriz !
InputMonth / InputDate works with `TuiMonth/TuiDay` object by default, take a look https://stackblitz.com/edit/taiga-starter-nhvqu5?file=src%2Fapp%2Fapp.component.ts
If you want to configure it to work with other formats (like strings), see this example https://taiga-ui.dev/components/input-date#native-date-output

**Comment by rendiriz** [comment]
Oh okay, my bad. Because I didn't find `TuiMonth/TuiDay` in `InputMonth` doc or example.

Thanks @vladimirpotekhin
