### ISSUE TITLE
🐞 - `cdk` "parse5" and "ng-morph" should be optional dependencies

### ISSUE THREAD

**Issue by hakimio** [Tinkoff/taiga-ui#2569]
### Which @taiga-ui/* package(s) are the source of the bug?

cdk

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Non-Blocking

### Description

Just like in [Angular Material CDK package](https://github.com/angular/components/blob/881b6ca62bd4342f97fbfdc359bf5921b84e0ddf/src/cdk/package.json#L56), libraries, used for creating schematics, should be listed as `optionalDependencies` not core `dependencies`.

### Angular version

14.2

### Taiga UI version

3

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
@hakimio good idea, thanks!

We will investigate how it works with schematics and solve this issue)
