### ISSUE TITLE
🐞 - Tables - tuiHead type error

### ISSUE THREAD

**Issue by TonyFich** [Tinkoff/taiga-ui#2585]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-table

### Is this issue blocking you?

Non-Blocking

### Description

`<th *tuiHead="'name'" tuiTh>Name</th>`

Typescript error:
Error:(11, 21) Type "name" is not assignable to type keyof T

### Angular version

14.0.0

### Taiga UI version

3.0.1

**Comment by splincode** [comment]
@TonyFich hello, please provide minimal reproduction github repo and I'll fix it quickly
