### ISSUE TITLE
🐞 - `Editor` doesn't render tables & editor style

### ISSUE THREAD

**Issue by ahmedkhairydev** [Tinkoff/taiga-ui#2587]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-editor

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Blocking

### Description

when adding a table in the editor, there's no anything displayed!
after debugging, I found that the editor style deson't injected in the head tag in the DOM.

Imports in my module: 
`    TuiRootModule,
    TuiEditorModule,
    TuiColorPickerModule,
    TuiEditorSocketModule,
`

Ex: 
![image](https://user-images.githubusercontent.com/15922118/188325998-65c0ced5-a7a3-4304-8b11-71bcaa106087.png)

But when I added the style manually from the taiga-ui website, It displayed!

Ex:
![image](https://user-images.githubusercontent.com/15922118/188326122-7bf3f9d6-a0c9-41cb-aeb8-f34b6998b8a6.png)
The style in the website:
![image](https://user-images.githubusercontent.com/15922118/188326125-37be938a-f124-4500-86a1-0fdfc2b1c01b.png)

### Angular version

12.1.4

### Taiga UI version

3.0.1

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
@ahmedkhairydev Hello, please provide minimal github repo for reproduction

**Comment by ahmedkhairydev** [comment]
> @ahmedkhairydev Hello, please provide a minimal GitHub repo for reproduction

I tried to get it to work, but I think there's a problem with the stackblitz.
@splincode 
https://stackblitz.com/edit/angular-taiga-play-ground-2szo4h?file=src%2Fstyles.less,angular.json

**Comment by ahmedkhairydev** [comment]
@splincode Hello, any update?

**Comment by splincode** [comment]
try to create a repository on github, not stackblitz with an example of reproduction

**Comment by ahmedkhairydev** [comment]
@splincode here the GitHub repo.
[GitHub Repo.](https://github.com/ahmedkhairydev/taiga-ui-editor)
[CodeSandbox](https://codesandbox.io/p/github/ahmedkhairydev/taiga-ui-editor/draft/confident-dhawan)

**Comment by ahmedkhairydev** [comment]
@splincode 

It works when I add the style manually from [here](https://github.com/Tinkoff/taiga-ui/blob/main/projects/addon-editor/components/editor-socket/editor-socket.component.less) [tui-editor-socket] Component's style

you must export the style **OR** put it inside the editor component because in my case, I want to add the text inside the editor but I won't preview it! So, I don't suppose to inject `tui-editor-socket` component inside the page.

**Comment by splincode** [comment]
Thank you for your research! We will try to fix the issue this week.
