### ISSUE TITLE
🐞 - `demo` opens `v2.x.x` after `2.x.x`-release

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#2600]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/next/components/editor-new

### Is this issue blocking you?

Non-Blocking

### Description

Open https://taiga-ui.dev/components/editor-new or https://taiga-ui.dev/next/components/editor-new

<img width="1785" alt="Screenshot 2022-09-05 at 18 00 36" src="https://user-images.githubusercontent.com/35179038/188477376-5636a62d-5638-4ece-a0f2-0cf0d7d691bc.png">

**Expected behaviour:**
3.x.x taiga version

### Angular version

any

### Taiga UI version

any

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
- [x] public
- [ ] proprietary
