### ISSUE TITLE
🚀 - Calendar should provide way to customize weekends

### ISSUE THREAD

**Issue by evantrimboli** [Tinkoff/taiga-ui#2606]
### Description

- The days on which weekends fall should be customizable, they aren't Sat/Sun in all locales.
- Weekend days shouldn't automatically be coloured as `tui-negative`.

**Comment by waterplea** [comment]
I suppose we can add config token for calendars with handler for week days to return color by index of the day. What do you think, @evantrimboli @vladimirpotekhin @nsbarsukov @splincode ?

**Comment by evantrimboli** [comment]
Not sure what would be most idiomatic. I can think of a couple of options:
- Use content projection and pass the date in as the context
- Add specific classes `tui-weekday`, `tui-weekend`, `tui-whatever` and then have the styling done as a function of theming and appearance

**Comment by waterplea** [comment]
Content projection is hard, considering all calendar use cases. And adding classes does not take care of customizing what days are considered weekend (from the other issue that I merged into this one).

**Comment by evantrimboli** [comment]
I was under the impression that determining the weekend days would be a localization issue, not a calendar issue. So at the calendar stage it would be known which days are weekend days.
