### ISSUE TITLE
tui-preview

### ISSUE THREAD

**Issue by PiotrGutowski** [Tinkoff/taiga-ui#2624]
Hi,

I use tui-preview in mat-dialog. I have there one problem when i want to open picture preview. This preview is opening behind mat-dialog (mat-dialog is always on top) how i can change it to have tui-preview on top.
thanks

**Comment by splincode** [comment]
Hello, could you please create a minimal example on github to reproduce the issue?

**Comment by vladimirpotekhin** [comment]
Hello! Angular material uses a high z-index for dialogs, but taiga-ui doesn't use z-index for preview. Taiga uses the portal pattern (you can read more about it [here](https://indepth.dev/posts/1417/demystifying-taiga-ui-root-component-portals-pattern-in-angular))
So you can try to raise the z-index for tui-dialog-host higher than the angular one (1000+), but I would recommend using the taiga dialog with the preview
