### ISSUE TITLE
Styles throw error when upgraded to 3.0.1🐞 - 

### ISSUE THREAD

**Issue by grizlizli** [Tinkoff/taiga-ui#2627]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Is this issue blocking you?

Blocking

### Description

Big fan of the project. Keep up the good work. 

However, I have updated the packages to 3.01 and I when I tried to import the stylings following the documentation I got this and similar errors in the console:

```
HookWebpackError: Module build failed (from ./node_modules/@angular-devkit/build-angular/node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
2 │ @import '~@taiga-ui/core/styles/taiga-ui-theme';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  apps\my-project\src\styles.scss 2:9  root stylesheet
```

My angular.json for the project:
```
"styles": [
              "node_modules/@taiga-ui/core/styles/taiga-ui-theme.less",
              "node_modules/@taiga-ui/core/styles/taiga-ui-fonts.less",
              "src/styles.css"
]
```

Only styling that I managed to import is:
@import '~@taiga-ui/core/styles/taiga-ui-local';

However, containers and responsive layout are not working as expected.

Thank you in advance.

### Angular version

14.1.3

### Taiga UI version

3.0.1

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
rename `styles.scss` to `styles.less` please

**Comment by vladimirpotekhin** [comment]
Hi! Global styles (like containers) have been moved to a separate `@taiga-ui/styles` package. Try to add `node_modules/@taiga-ui/styles/taiga-ui-global` in styles in angular.json

**Comment by grizlizli** [comment]
Installing `@taiga-ui/styles`  and adding `node_modules/@taiga-ui/styles/taiga-ui-global.less` fixed the issue.

Thanks!
