### ISSUE TITLE
🐞 - `tui-hint` Hint is positioned off-screen on mobile device

### ISSUE THREAD

**Issue by hakimio** [Tinkoff/taiga-ui#2634]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Non-Blocking

### Description

When `tui-hint` component is used on mobile device, automatic positioning doesn't seem to work correctly.

The issue can be reproduced either on a real Android phone or on Chrome mobile emulator.
Steps to reproduce the issue:
- Emulate a relatively small phone. For example, Samsung S21 (resolution 360x759, device pixel ratio: 3).
- Test by running [UI tour demo which uses tui-hint for UI implementation](https://hakimio.github.io/ngx-ui-tour/tui-hint)
- On some of the tour steps, you'll see that the hint is positioned off-screen. For example, you can clearly see it on the following UI tour step:
![image](https://user-images.githubusercontent.com/768105/188893099-80b9fcd6-1362-4a12-8868-9b3bed54e201.png)

The positioning on mobile seems to work correctly when using [`tui-dropdown` component](https://hakimio.github.io/ngx-ui-tour/tui-dropdown) instead or when using `tui-hint` on desktop device.

### Angular version

14.2

### Taiga UI version

3

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [X] Android

**Comment by waterplea** [comment]
Forgot to mention this in a PR, it will be fixed in the next version.

**Comment by hakimio** [comment]
@waterplea there still seems to be one case where the hint is positioned offscreen:
![image](https://user-images.githubusercontent.com/768105/192506796-142c6551-ad5d-4b45-be6e-2db285883e42.png)

Can you test the changes with [ngx-ui-tour](https://github.com/hakimio/ngx-ui-tour) demo project?

**Comment by waterplea** [comment]
Hmm. That's weird, it should have flipped to the top 🤔

**Comment by waterplea** [comment]
Oh, I see. Once it's in the mode of "I cannot fit at any position" it stops flipping vertically. Ok, I'll take a look again.

**Comment by hakimio** [comment]
Thanks. It seems to work correctly in desktop browser mode though.
