### ISSUE TITLE
🐞 - wrong positioning for `tuiTextfieldCustomContent` in tuiTextfield

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#2656]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/input/API?&tuiHintContent=Some%20content&tuiTextfieldCustomContent=%3Cb%3ELongTextContent%3Cb%3E

### Is this issue blocking you?

Non-Blocking

### Description

<img width="472" alt="image" src="https://user-images.githubusercontent.com/12021443/189347727-8708d6db-ac7c-4bc2-b8b3-81bb464b3801.png">

### Angular version

12

### Taiga UI version

3.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
You can also use this test to reproduce problem

https://github.com/Tinkoff/taiga-ui/blob/b373af1c3bf62908a69d276166957b5e0771579b/projects/demo-integrations/cypress/tests/kit/input/input.spec.ts#L7-L15

Investigate, can we improve this test somehow ?
