### ISSUE TITLE
🐞 -  Migration failed: Cannot read properties of undefined (reading 'getInitializer')

### ISSUE THREAD

**Issue by loxy** [Tinkoff/taiga-ui#2660]
### Which @taiga-ui/* package(s) are the source of the bug?

taiga-schematics

### Is this issue blocking you?

Blocking

### Description

When migrating to version 3 I get the following error: 

```
[error] TypeError: Cannot read properties of undefined (reading 'getInitializer')
    at decoratorToTemplateResource (C:\Dev\ionity\cockpit-frontend\node_modules\@taiga-ui\cdk\schematics\utils\templates\get-component-templates.js:30:39)
    at Array.map (<anonymous>)
    at Object.getComponentTemplates (C:\Dev\ionity\cockpit-frontend\node_modules\@taiga-ui\cdk\schematics\utils\templates\get-component-templates.js:11:10)
    at Object.migrateTemplates (C:\Dev\ionity\cockpit-frontend\node_modules\@taiga-ui\cdk\schematics\ng-update\steps\migrate-templates.js:22:67)
    at C:\Dev\ionity\cockpit-frontend\node_modules\@taiga-ui\cdk\schematics\ng-update\index.js:53:29
    at Generator.next (<anonymous>)
    at C:\Dev\ionity\cockpit-frontend\node_modules\tslib\tslib.js:118:75
    at new Promise (<anonymous>)
    at Object.__awaiter (C:\Dev\ionity\cockpit-frontend\node_modules\tslib\tslib.js:114:16)
    at C:\Dev\ionity\cockpit-frontend\node_modules\@taiga-ui\cdk\schematics\ng-update\index.js:44:39
```

 I cannot provide more information. Any hint how to debug?

### Angular version

14.0.2

### Taiga UI version

3.1.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
i think we can improve our migrations to show a warning
show a minimal example of such a component, please

**Comment by loxy** [comment]
The component looked like:

```ts
@Component({ selector: 'app-tma-filters' })
class TmaFiltersStubComponent {}
``` 

And I added a required template:
```ts
@Component({ selector: 'app-tma-filters', template: '' })
class TmaFiltersStubComponent {}
``` 

In your migration this is not checked: 
https://github.com/Tinkoff/taiga-ui/blob/e34550be8e335be08716c47552cf27ffec656155/projects/cdk/schematics/utils/templates/get-component-templates.ts#L43

I've added a log to your compiled code to find the wrong definitions. I mean, you can ignore if there is no template  and put a warning. But the problem is more on our side, I guess

**Comment by waterplea** [comment]
I'll close it because `@Component` requires either `template` or `templateRef` so it's not a valid case.
