### ISSUE TITLE
📚 - Check Documentation's API Pages (`@Input()` names)

### ISSUE THREAD

**Issue by Kulikov17** [Tinkoff/taiga-ui#2665]
### What is the affected URL?

https://taiga-ui.dev/components/button/API?tuiMode=null

### Description

Check field names for components. For example, for a button component, the field name is still called "[pseudoHovered]", although it has been changed to "[pseudoHover]".

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by jrstrayhorn** [comment]
I'd like to take this one.

**Comment by waterplea** [comment]
> I'd like to take this one - at least for the button component called out in the issue.

Sure, go ahead.

**Comment by jrstrayhorn** [comment]
@waterplea - PR submitted!
