### ISSUE TITLE
[TuiDropdownModule] tuiDropdownSided in v3

### ISSUE THREAD

**Issue by tigatujuhlima** [Tinkoff/taiga-ui#2667]
I am currently updating from v2 to v3 and I have noticed that tuiDropdownSided is no more in the dropdown, and in my project I have used this in a few places, so I wanted to ask, is this intentional (the reason why I didn't know whether to put it as bug or feature issue)? I would love to have it back.

Thank you!

**Comment by waterplea** [comment]
It is now just `tuiDropdownSided` and cannot be dynamically changed to `false`. We need to add an example to demo indeed.

**Comment by tigatujuhlima** [comment]
> It is now just `tuiDropdownSided` and cannot be dynamically changed to `false`. We need to add an example to demo indeed.

Ahh okay I tried it with hosted-dropdown and it didn't work. With dropdown it worked fine thanks!
