### ISSUE TITLE
🤖 - Cypress 10.8 supports Safari

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#2690]
### Description

<img width="814" alt="image" src="https://user-images.githubusercontent.com/12021443/190006800-0931a8d6-1d64-499c-b83f-30dffb660a8c.png">

https://docs.cypress.io/guides/guides/launching-browsers#WebKit-Experimental

**Comment by nsbarsukov** [comment]
Unbelievable ! It has finally happened.

**Comment by splincode** [comment]
We need use Playwright instead
