### ISSUE TITLE
🐞 - [Table] Type 'IUser[]' is not assignable to type 'readonly Record<keyof IUser, any>[]'

### ISSUE THREAD

**Issue by arndwestermann** [Tinkoff/taiga-ui#2706]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-table

### Please provide a link to a minimal reproduction of the bug

[https://github.com/arndwestermann/taiga-ui-playground](https://github.com/arndwestermann/taiga-ui-playground)

### Is this issue blocking you?

Blocking

### Description

Since v3.2.0 I can't build two of my libraries which uses the table. It complains about the type I want to assign to the data field of the tuiTBody and tuiTr. v3.1.0 works perfectly fine. ~~Unfortunately I can't reproduce the error in a new project.~~

```
Error: libs/user-administration/src/lib/user-administration.component.html:119:54 - error TS2322: Type 'IUser[]' is not assignable to type 'readonly Record<keyof IUser, any>[]'.

119       <tbody *ngxObserve="users$ as users" tuiTbody [data]="users">
                                                         ~~~~
```

```
Error: libs/user-administration/src/lib/user-administration.component.html:120:30 - error TS2322: Type 'IUser[]' is not assignable to type 'readonly Record<keyof IUser, any>[]'.

120        <tr *tuiRow="let user of users; let index = index" tuiTr (click)="openDrawer(user)" class="cursor-pointer">
                                 ~~
```

What I've also noticed is that the type of TuiTBodyComponent and data input changed to any after the update

Before

![tuiTBody type before update v3_1_0](https://user-images.githubusercontent.com/58134597/190420536-48652f6d-c230-4993-9bc3-31897bc81175.png)

![data type before update v3_1_0](https://user-images.githubusercontent.com/58134597/190420628-54e02984-5efc-4f01-9d1f-c86b0f9538c4.png)

After

![tuiTBody type after update v3_2_0](https://user-images.githubusercontent.com/58134597/190420684-a9f31a33-7c63-472e-b01a-5fc28f23d000.png)

![data type after update v3_2_0](https://user-images.githubusercontent.com/58134597/190420744-04c570d5-dac1-4cf6-b893-9d53d6aeba9e.png)

### Steps to reproduce

- clone the repo
- switch to the branch `bug/table-not-assignable-to-type`
- run `npm i`
- run `npm run build:prod` to make sure everything works as expected
- run `npm i @taiga-ui/addon-charts@3.2.0 @taiga-ui/addon-commerce@3.2.0 @taiga-ui/addon-editor@3.2.0 @taiga-ui/addon-table@3.2.0 @taiga-ui/cdk@3.2.0 @taiga-ui/core@3.2.0 @taiga-ui/icons@3.2.0 @taiga-ui/kit@3.2.0 @taiga-ui/styles@3.2.0` to update to v3.2.0
- run `npm run build:prod` again

### Angular version

14.2.0

### Taiga UI version

3.2.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Hello, could you please send a minimal example to reproduce on Github?

**Comment by arndwestermann** [comment]
Hi @splincode sorry for the delayed answer, it took me a while to reproduce it. I've updated the issue with a link to the repo and steps to reproduce. Hope this helps.

**Comment by splincode** [comment]
```html
<tbody *ngxObserve="users$" tuiTbody [data]="users$ | async">
		<tr *tuiRow="let user of users$ | async; let index = index" tuiTr>
```

instead of 

```html
	<tbody *ngxObserve="users$ as users" tuiTbody [data]="users">
		<tr *tuiRow="let user of users; let index = index" tuiTr>
```
