### ISSUE TITLE
🐞 - `Editor` incorrect column's width after cell merging (table extension)

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#2730]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-editor

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/editor/API

### Is this issue blocking you?

Non-Blocking

### Description

1. Open https://taiga-ui.dev/components/editor/API
2. Insert table 3*3
3. Change size of the first two columns
4. Merge all cells of the first table's row

https://user-images.githubusercontent.com/35179038/190990598-c71f725c-4976-4b56-9c98-7bd95895c1ef.mov

### Angular version

any

### Taiga UI version

3.3.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Closed in favor of https://github.com/Tinkoff/tui-editor/issues/24
