### ISSUE TITLE
🤖 - `eslint-plugin` add `no-import-circular-deps`

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#2750]
## Problem

**projects/testing/core/badge.harness.ts:**
```ts
import {TuiComponentHarness} from '@taiga-ui/testing';
```
It breaks build because it produces circular dependency:
```console
Entry point @taiga-ui/testing has a circular dependency on @taiga-ui/testing/core.
```
To fix build it should be corrected to:
```ts
import {TuiComponentHarness} from '@taiga-ui/testing/utils';
```

## Proposed solution
Write eslint-rule (with autofix!).

**Comment by ddubrava** [comment]
hey, doesn't [import/no-cycle](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-cycle.md) help?

**Comment by nsbarsukov** [comment]
@ddubrava Hi!

Thank for this great idea!
It works
<img width="1532" alt="eslint-error" src="https://user-images.githubusercontent.com/35179038/193521886-29664e3f-192a-4734-931b-4e9dc6303aed.png">

Do you want to contribute and add this rule to our `.eslintrc.js` ?
It is October and time for Hacktoberfest =)

**Comment by ddubrava** [comment]
yep, I'll raise a PR in a few days
