### ISSUE TITLE
🐞 - .tui-editor-socket

### ISSUE THREAD

**Issue by alex-jss** [Tinkoff/taiga-ui#2754]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-editor

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Non-Blocking

### Description

Please remove !import in `.tui-editor-socket blockquote`. This prevents from setting values

### Angular version

13.3.5

### Taiga UI version

2.62.4

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
@splincode please check this one when you're back, maybe that `!important` is not necessary, or if it is — let us know what for :)

**Comment by alex-jss** [comment]
@waterplea The custom style is ignored
![image](https://user-images.githubusercontent.com/44188728/193201611-fac3a3c2-c612-4748-ba9a-b96c179a5c09.png)
