### ISSUE TITLE
🐞 - `schematics` throws error `collection [...]\\schematics\\collection.json` cannot be resolved

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#2769]
### Which @taiga-ui/* package(s) are the source of the bug?

cdk

### Is this issue blocking you?

Blocking

### Description

Windows!
![Image Pasted at 2022-9-28 17-15](https://user-images.githubusercontent.com/35179038/192804154-65401830-3fd2-475b-833e-1b7c7458cebd.png)

### Angular version
14.2.2

### Taiga UI version

3.4.0

### Node version
14.18.1

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by MishkaKlkv** [comment]
Same problem, but I have macOS 13,  node - 16.18.0, npm - 8.19.1 and Taiga 3.8.0

I tried to add Taiga for this project:
https://github.com/maximegris/angular-electron

**I solved this issue** with command ng add @taiga-ui/cdk

**Comment by weldeondotwav** [comment]
I had my development server (`ng serve`) running while trying to add taiga. After stopping the dev server the installation went through with no errors.

I did bump my Angular versions slightly by running `ng update @angular/cli` and `ng update @angular/core`, but the version bump was really minor, so I think stopping the dev server is what made it work for me.

**Comment by waterplea** [comment]
Seems like on Windows it's an issue with slash/backslash in paths and it's not something we can fix, as this is under Angular's code. Workaround would be running **`ng add @taiga-ui/cdk`**.
