### ISSUE TITLE
🐞 - `Editor` change type of nested list produces style problems

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#2776]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-editor

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/editor/API?tuiMode=null&ngModel=%3Cul%3E%3Cli%3E%3Cp%3E1%3C%2Fp%3E%3Col%3E%3Cli%3E%3Cp%3E2%3C%2Fp%3E%3C%2Fli%3E%3Cli%3E%3Cp%3E3%3C%2Fp%3E%3C%2Fli%3E%3C%2Fol%3E%3C%2Fli%3E%3C%2Ful%3E%3Cp%3E%3C%2Fp%3E%3Col%3E%3Cli%3E%3Cp%3E1%3C%2Fp%3E%3Cul%3E%3Cli%3E%3Cp%3E2%3C%2Fp%3E%3C%2Fli%3E%3Cli%3E%3Cp%3E3%3C%2Fp%3E%3Cp%3E%3C%2Fp%3E%3C%2Fli%3E%3C%2Ful%3E%3C%2Fli%3E%3C%2Fol%3E%3Cp%3E%3C%2Fp%3E

### Is this issue blocking you?

Non-Blocking

### Description

1. Open https://taiga-ui.dev/components/editor/API
2. Create ordered list with two items
3. Apply indent for the second item and change type of list for these item (ordered => unordered)

https://user-images.githubusercontent.com/35179038/193208376-70f46446-30ad-467f-98ce-1936ebe4a452.mov

___

[[Open]](https://taiga-ui.dev/components/editor/API?tuiMode=null&ngModel=%3Cul%3E%3Cli%3E%3Cp%3E1%3C%2Fp%3E%3Col%3E%3Cli%3E%3Cp%3E2%3C%2Fp%3E%3C%2Fli%3E%3Cli%3E%3Cp%3E3%3C%2Fp%3E%3C%2Fli%3E%3C%2Fol%3E%3C%2Fli%3E%3C%2Ful%3E%3Cp%3E%3C%2Fp%3E%3Col%3E%3Cli%3E%3Cp%3E1%3C%2Fp%3E%3Cul%3E%3Cli%3E%3Cp%3E2%3C%2Fp%3E%3C%2Fli%3E%3Cli%3E%3Cp%3E3%3C%2Fp%3E%3Cp%3E%3C%2Fp%3E%3C%2Fli%3E%3C%2Ful%3E%3C%2Fli%3E%3C%2Fol%3E%3Cp%3E%3C%2Fp%3E)
<img width="1103" alt="Screenshot 2022-09-30 at 09 51 23" src="https://user-images.githubusercontent.com/35179038/193208685-a13e3c91-71b7-42e7-bafc-2d46123c77f7.png">

### Angular version

any

### Taiga UI version

3.4.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Duplicate: https://github.com/Tinkoff/taiga-ui/issues/2287

**Comment by nsbarsukov** [comment]
Oops :)
