### ISSUE TITLE
[FEATURE] taiga-ui & ngx-formly

### ISSUE THREAD

**Issue by RobotCherries** [Tinkoff/taiga-ui#279]
# 🚀 Feature request

### Describe the solution you'd like
Hello, I would like to use [ngx-formly](https://github.com/ngx-formly/ngx-formly). 

### Additional context
**ngx-formly** is an angular library which dynamically generates a form based on a given object model ([see example here](https://stackblitz.com/angular/mnlmmvmyamy?file=src%2Fapp%2Fapp.component.ts)). 

It currently supports the following ui-themes: bootstrap, material, ionic, primeng, kendo, nativescript.

### Main question
Would you be interested to add taiga-ui support to angular formly? I would love to help.

**Comment by jonsamwell** [comment]
@RobotCherries I have partially already done this for my needs and could release this but I have very little time to do this, I am happy to share the code in a repo and give you commit rights.

Taiga is a bit different due to everything being a component i.e. a label is either a string or a component displayed via a polymorphous outlet so it needed a bit of massaging to fit into the Formly structure where Formly expects string for everything.  However, it is working nicely at the moment

![image](https://user-images.githubusercontent.com/3694497/111087485-0adfb400-8576-11eb-8caa-1779bbacd093.png)

**Comment by RobotCherries** [comment]
@jonsamwell Hey, sorry for the late reply. Tomorrow I'll starting to dig trough the code and try to merge the two. 
<br>
> I have partially already done this for my needs and could release this but I have very little time to do this, I am happy to share the code in a repo and give you commit rights.

And Yes, if you could share the code of what you've done so far, that would be amazing! 💯
<br>
> Taiga is a bit different due to everything being a component i.e. a label is either a string or a component displayed via a polymorphous outlet so it needed a bit of massaging to fit into the Formly structure where Formly expects string for everything. However, it is working nicely at the moment

Ok, interesting solution, it turned out pretty neat 👍
<br>
Also, I notice there are slight style differences, are those some of your custom styles?
![image](https://user-images.githubusercontent.com/26595540/111998371-9af89d00-8b24-11eb-87cf-b0f25d9c0a80.png)

**Comment by RobotCherries** [comment]
@waterplea Aw, that would be even better!

**Comment by waterplea** [comment]
I talked to them and it looks like they have only created it to the limited scope of what they needed to do with it, so you cannot really feed it arbitrary JSON and have your form auto-generated. Also they do not seem to have the resources to extend functionality, release and maintain the library, unfortunately :(

**Comment by RobotCherries** [comment]
Oh well then. I guess that the best idea would be to build upon @jonsamwell's solution.

**Comment by waterplea** [comment]
Since there are no plans to add official support at this time, I'm closing this issue. If somebody makes one, for example, based on messages above, please share it here.
