### ISSUE TITLE
🐞 - non-visible cursor in input card group

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#2792]
### Which @taiga-ui/* package(s) are the source of the bug?

core, kit

### Please provide a link to a minimal reproduction of the bug

components/input-card-grouped

### Is this issue blocking you?

Blocking

### Description

```
начинаем вводить номер карты
включаем переводчик в хроме и меняем на любой язык
продолжаем печатать
и тут несколько вариантов

мы не видим что мы печатаем дальше
переводчик перевод цифры (если она одна) например 9 - девять
Самая большая проблема:
после этого по сабмит, в инпут value находиться переведенный текст, а не настоящее значение!!!

Баг повторяется в тайге2 и 3. Но не замечен в Input и InputCard
```

<img width="983" alt="image" src="https://user-images.githubusercontent.com/12021443/193531873-0494f8a1-6e97-4ea6-9c64-db5cb1f6adf1.png">

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Translation bug is already fixed, the remaining issue is non-visible cursor.
