### ISSUE TITLE
🚀 - ability to align elements in the carousel

### ISSUE THREAD

**Issue by instingt** [Tinkoff/taiga-ui#2802]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

By default, the elements are centered. Please add an option that defines alignment (top, center, bottom).

Branch: 2.x

**Comment by waterplea** [comment]
Rather than adding option, we could add flex to the wrapper element so this can be externally controlled by align-self, margin and other CSS rules.
