### ISSUE TITLE
[BUG] Incorrect work with Angular Elements

### ISSUE THREAD

**Issue by stcyuvoronin** [Tinkoff/taiga-ui#281]
# 🐞 Bug report

### Description

When you create a component using [Angular Elements](https://angular.io/guide/elements), some controls do not work correctly. For example, the _InputDate_ drop-down closes immediately after opening.

Also, the CSS variables _--tui*_ do not work correctly, since they are placed inside the _:root_ selector, which is not applicable in ShadowDOM.

### Reproduction

Steps:

- create a component as an Angular Element using tui-root
- add another component inside it, which will have inputDate
- start the project and try to set the date in inputDate

StackBlitz:

https://stackblitz.com/edit/angular-ivy-gnjgeu

### Expected behavior

It is expected that the component will work the same way as on the demo site.

### Versions

-   OS: Windows 10, Ubuntu 18.04
-   Browser: Firefox, Chrome
-   Angular 11.2.5
-   Packages: @taiga-ui/core@2.6.2 @taiga-ui/cdk@2.6.2 @taiga-ui/kit@2.6.2

**Comment by waterplea** [comment]
Interesting. Thank you for bringing this up, we will need to investigate. Some of our internal projects used Taiga UI as Angular Elements, I'll reach out to them. As for CSS variables, I believe there's no other way, other than add theme styles to your top level Angular Element component.

**Comment by waterplea** [comment]
Issue with dropdowns and shadow dom was fixed some versions ago. CSS variables penetrate shadow dom so in theory if you put Taiga UI theme in the top app it should work fine. If you have some other concrete issues, please open a separate ticket for easier tracking.
