### ISSUE TITLE
🐞 - migrations @taiga-ui/cdk throw error "Cannot read property 'getInitializer' of undefined"

### ISSUE THREAD

**Issue by bayburin** [Tinkoff/taiga-ui#2820]
### Which @taiga-ui/* package(s) are the source of the bug?

cdk

### Is this issue blocking you?

Blocking

### Description

I'm trying to update @taiga-ui/cdk from version 2.56.0 to version 3.5.0 with migrations and receiving an error:

```
Running migration updateToV3
 

🚀 Your packages will be updated to @taiga-ui/*@^3.5.0

  ⚡️ replacing deep imports...
  ✅  deep imports replaced 

  ⚡️ replacing enums imports...
  ✅  enums replaced 

  ⚡️ renaming types...
  ✅  types renamed 

  ⚡️ replacing constants...
  ✅  constants replaced 

  ⚡️ replacing services...
    > replacing TuiPortalService...
    > replacing TuiNotificationsService...
    > replacing TuiCodeEditor...
    > replacing PreviewDialogService...
  ✅  services replaced 

  ⚡️ migrating templates...
Cannot read property 'getInitializer' of undefined
```

Commands to reproduce:

1. nx migrate @taiga-ui/cdk
2. nx migrate --run-migrations

### Angular version

13.3.10

### Taiga UI version

2.56.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I guess we need to include fix for that if it's the case again :)

**Comment by nsbarsukov** [comment]
I take it)

**Comment by bayburin** [comment]
> See #2660 Maybe it helps...

Thanks! Yes, I found all components without templates, change it and migrations completed successfully
