### ISSUE TITLE
📚 - 

### ISSUE THREAD

**Issue by Flarion-ion** [Tinkoff/taiga-ui#2869]
### What is the affected URL?

https://taiga-ui.dev/getting-started

### Description

Need to add command for install taiga-ui in nx workspaces
`nx g @taiga-ui/cdk:ng-add
`

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [X] Linux
- [X] iOS
- [X] Android

**Comment by splincode** [comment]
fixed by next 
https://taiga-ui.dev/next/
<img width="540" alt="image" src="https://user-images.githubusercontent.com/12021443/195133039-1c7177a3-a249-4c1d-8064-4d32b2d1128f.png">
