### ISSUE TITLE
📚 - Уточнение по установке в nx

### ISSUE THREAD

**Issue by Flarion-ion** [Tinkoff/taiga-ui#2880]
### What is the affected URL?

https://taiga-ui.dev/next/getting-started

### Description

Ссылаюсь на https://github.com/Tinkoff/taiga-ui/issues/2869
 При `ng add <lib_name>` идет поиск и установка пакета средствами angular-cli
 При `nx g @taiga-ui/cdk:ng-add` выполняется "инсталяция" пакета в проект

Корректнее команда для раздела "You can easily install Taiga UI by running the following command:" выглядит так
`npm i @taiga-ui/{cdk,core,kit,icons} && nx g @taiga-ui/cdk:ng-add`
Извините, за то что сразу так не описал
 

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [X] Linux
- [X] iOS
- [X] Android

**Comment by waterplea** [comment]
`npm i @taiga-ui/{cdk,core,kit,icons}` делать не нужно, при установке через схематик. Это ручная установка пакетов.
