### ISSUE TITLE
🚀 - Backend adapter

### ISSUE THREAD

**Issue by Bykiev** [Tinkoff/taiga-ui#2883]
### Description

Hi, it'll be cool if taiga-ui will have a backend adapter. While using tables we need remote paging, sorting, filtering. grouping and etc. Dropdown list content can be huge enough.

**Comment by waterplea** [comment]
I'm not sure what are you requesting here. Could you clarify more?

**Comment by waterplea** [comment]
Doesn't look like it's within Taiga UI scope. Our components are data model agnostic and this is taiga **UI**. Sounds like this should be a separate package but since our controls don't care about data at all I don't see how such adapter would be tied to Taiga UI. At the moment I'm inclined to close this issue as out of scope.

**Comment by Bykiev** [comment]
Of course it should be a separate package for needed frameworks. We need a client-side and server-side adapters, most of the developers need an enterprise-ready solution, such as DevExtreme, Telerik and etc. Taiga-UI is not developer-friendly now, It's almost unusable in enterprise applications, hope it'll be changed in near future

**Comment by waterplea** [comment]
I see two ways for this to proceed:

1. You are welcome to create such package and we can incorporate links to it on demo portal, add usage examples and such.
2. You are also welcome to express specification for such package clearly here so this issue can remain open for us to consider in the future or for external contributors to take on. 

At the moment it is not clear to me what kind of work is needed on the Taiga UI side to satisfy the need, sorry. Taiga UI is opensourced proprietary solution used by worlds biggest online bank for many years. It might be a bit skewed towards our internal needs and such adapter issue never surfaced before. Our goal was to make it as flexible as possible and rather low level so it could be used anywhere. I might just lack knowledge and experience needed to cover that backend/frontend adapter issue.

**Comment by Bykiev** [comment]
As I've used another UI frameworks for a long time I need some more time to research Taiga-UI. Unfortunately, data adapter is not the only disappointment for me - table features are weak enought (column fixing, column hiding priority, multisorting, popup editing mode are not supported). 
But there are some interesting controls which I didn't see in another UI kits. I'll research more issues and report back (maybe it'll be better to create a new issue for each one))

**Comment by waterplea** [comment]
Unrelated to the ticket, but just to help with other issues you're having: 

1. Column fixing is done with passing sticky to the horizontal `th`. You would need to do some calculations for width if you need to fix multiple columns though.
2. Column hiding is done with `columns` input and `[Reorder](https://taiga-ui.dev/components/reorder)` component to reorder/toggle columns with UI.
3. Multisorting is done through passing an arbitrary sorter which you can compose any way you like. There's no UI for it though as it's not that clear how to make it universally.
4. Not sure about popup editing mode, but you can make tables editable inline or add a button to edit with a dialog and a form inside it.

Mostly, once again, Taiga UI is flexible and low level, comparing to the rest of UI kits. It is not intended to be a complete solution for all cases, but rather a toolkit of easy to compose lego blocks to achieve solution for every case.

**Comment by waterplea** [comment]
Typically, there's an `API` tab listing all the inputs for the component:
https://taiga-ui.dev/components/table/API
