### ISSUE TITLE
🚀 - Pivot table control

### ISSUE THREAD

**Issue by Bykiev** [Tinkoff/taiga-ui#2884]
### Description

Hi, pivot table with OLAP datasource is a must have control. Is any plans to implement it?

**Comment by waterplea** [comment]
Here, as well, we would need a well-defined feature request, otherwise it's too abstract to consider. Please add specification of desired functionality.

**Comment by Bykiev** [comment]
The pivot grid control should provide the same OLAP explorer features, as Excel, including filtering and sorting.

**Comment by waterplea** [comment]
DevExtreme is a commercial solution with different scope. It's not the goal of Taiga UI to provide such high level components. Taiga UI has all the necessary lower level components and APIs to make those however. If somebody is willing to make it and release a separate package, we would definitely promote it on our portal, but it's not something we will be implementing here. A bugbounty or a personal contract with somebody interested might be an option if you want this functionality in Taiga UI/Angular but don't have the resources to develop such solution yourself.
