### ISSUE TITLE
📚 - typo on scrollbar page

### ISSUE THREAD

**Issue by AchrafLance** [Tinkoff/taiga-ui#2886]
### What is the affected URL?

https://taiga-ui.dev/components/scrollbar

### Description

on the second line in the page it's written: 
Native scrollbar is hidden to keep native platform scroll **_expirience_**
quick fix: 
Native scrollbar is hidden to keep native platform scroll **_experience_**

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
@AchrafLance hello, please, send corrections to your pull request
