### ISSUE TITLE
🚀 - Implement a `tuiTextfieldAppearance` directive

### ISSUE THREAD

**Issue by theorlovsky** [Tinkoff/taiga-ui#2901]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

core

### Description

There is one in the `input-range` component, but it's not public and doesn't support neither dynamic changes nor binding. I believe it should be implemented similar to `tuiTextfieldSize`

I'll open a PR if you okay with that

**Comment by waterplea** [comment]
Sure, go ahead. We were planning to make it public later. However I'm not sure if it's going to be easy to be easy to make it dynamic since it's just a string you get from DI.

**Comment by waterplea** [comment]
Probably you'll need to change type to `Observable<string> | string` for backward compatibility.

**Comment by theorlovsky** [comment]
thanks, I'll take it into account
