### ISSUE TITLE
🐞 - Dropdownbox should adjust to screen visibility

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#2930]
### Which @taiga-ui/* package(s) are the source of the bug?

core, addon-editor

### Please provide a link to a minimal reproduction of the bug

.

### Is this issue blocking you?

Non-Blocking

### Description

<img width="549" alt="image" src="https://user-images.githubusercontent.com/12021443/196626256-348bfbb7-6530-4a8f-b31c-6d5f2ce6c8a5.png">

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Looks like we need some kind of a `VIEWPORT` token that defaults to `WINDOW` and that would be able to override.

**Comment by splincode** [comment]
@waterplea great idea

**Comment by waterplea** [comment]
Fixed with `TUI_VIEWPORT` token
