### ISSUE TITLE
🐞 - Can't remove hover state from MarkerIcon with link mode

### ISSUE THREAD

**Issue by SeregaZnam** [Tinkoff/taiga-ui#2947]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-88ng2v?file=src%2Fapp%2Fapp.component.html

### Is this issue blocking you?

Blocking

### Description

When I use MarkerIcon with property mode 'link' I have hover state and I can't remove this state

### Angular version

11.2.14

### Taiga UI version

2.66.1

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [X] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Fixed with https://github.com/Tinkoff/taiga-ui/pull/2950
