### ISSUE TITLE
🚀 - Support tuiTextfieldSize 's' in tui-text-area

### ISSUE THREAD

**Issue by JorisMolnar** [Tinkoff/taiga-ui#2956]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

Not sure if this is actually a bug or a feature request.

I've noticed that the [tui-text-field demo page](https://taiga-ui.dev/components/text-area/API?tuiMode=null) doesn't support selecting `tuiTextfieldSize="s"`, while the type column states `TuiSizeS | TuiSizeL` and thus should accept `'s'`.

When using `'s'` on a tui-text-area, a couple of problems appear. You can see these using [this URL](https://taiga-ui.dev/components/text-area/API?tuiMode=null&tuiTextfieldSize=s) (where I set `tuiTextfieldSize=s` by changing the URL).

- The label is shown inside the input, but moves to be partially visible at the top when focussing.
![image](https://user-images.githubusercontent.com/20184617/197551037-9234a5fc-8d36-4793-9eba-40609a12fe6a.png)
    - `labelOutside=false` is not officially supported with `size=s`, so this might not actually be a problem.
- `font-size` and `line-height` doesn't get smaller, as it does with other inputs like tui-input.
    - In the demo environment, [tui-input with size=s](https://taiga-ui.dev/components/input/API?tuiMode=null&tuiTextfieldSize=s&tuiTextfieldLabelOutside=true) has font-size 13. [tui-text-area with size=s](https://taiga-ui.dev/components/text-area/API?tuiMode=null&tuiTextfieldSize=s&tuiTextfieldLabelOutside=true) has 15.
- Text is immediately against the top of the text-area, instead of (visually) having a little padding at the top as tui-input does.
    - Looks like tui-input doesn't actually have a padding-top, but the inner tui-primitive-textfield has a set height of 2rem, which results in a perceived padding-top of `0.375rem`. Adding `padding-top: 0.375rem` to `tui-text-area[data-size="s"] .t-wrapper` visually aligns the contents.

**Comment by waterplea** [comment]
We also need to check with Figma for proprietary design, seems like it has changed a bit.
