### ISSUE TITLE
🐞 - Calendar icon in date inputs can be hidden, but it still occupies its space

### ISSUE THREAD

**Issue by theorlovsky** [Tinkoff/taiga-ui#2960]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-owymhi?file=src/app/app.component.ts

### Is this issue blocking you?

Blocking

### Description

I'd like to move the icon to the left, and I'm kinda able to do it via `providers`, but there is a visual bug that stops me from using this solution. I can open a PR and add an `*ngIf` to completely hide the icon when it's not present (e.g. [here](https://github.com/Tinkoff/taiga-ui/blob/1f44e39fb4fba6b579107cae2094d7e5a228e0d7/projects/kit/components/input-date/input-date.template.html#L44))

And/or we can open another issue for moving the icon left

### Angular version

14.2.7

### Taiga UI version

3.8.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
You can probably write something like that instead of `*ngIf`:
```html
[tuiTextfieldIcon]="computedMobile ? mobileIconContent : (calendarIcon && iconContent)"
```
It would be a welcomed PR, also, if you can, take a look at other places where similar change might improve customization.

**Comment by waterplea** [comment]
Also you don't need to create directive class, providing a simple object of that interface would be enough. We should improve typings for those tokens.
```ts
{
  provide: TUI_TEXTFIELD_ICON_LEFT,
  useValue: {
    iconLeft: ({ $implicit }) => $implicit === 's' ? 'tuiIconCalendar' : 'tuiIconCalendarLarge'
  },
},
```
