### ISSUE TITLE
🐞 - Input elements should have autocomplete attributes (suggested: "new-password")

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#2965]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/taiga-starter

### Is this issue blocking you?

Non-Blocking

### Description

<img width="784" alt="image" src="https://user-images.githubusercontent.com/12021443/198049549-9c7b25a9-ee0a-42a0-a104-688ae3e4f09d.png">

### Angular version

latest

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
That is working as intended, you are free to set any autocomplete attribute using exposed `<input tuiTextfield />`.
