### ISSUE TITLE
🐞 - PdfViewer only shows the first page of the file on mobile

### ISSUE THREAD

**Issue by anastasiiabaranova** [Tinkoff/taiga-ui#2973]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/pdf-viewer

### Is this issue blocking you?

Blocking

### Description

On mobile devices when opening a file using TuiPdfViewerService, only the first page of the file is shown.

### Angular version

11.2.14

### Taiga UI version

2.57.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by waterplea** [comment]
Do you have a screenshot of that? As far as I know, mobile browsers don't support embedding PDF and it should just display a "Download" button there (native way PDF in `iframe` shows on mobile).

**Comment by splincode** [comment]
![B5BD9A3A-4C8D-4B4A-B1DA-1906627BF0B5](https://user-images.githubusercontent.com/12021443/198539775-b72b49b8-2f12-400a-8fde-616dd354bebb.png)

**Comment by waterplea** [comment]
Looks like this is another decade long BS from Apple 😫 
https://stackoverflow.com/questions/15480804/problems-displaying-pdf-in-iframe-on-mobile-safari
