### ISSUE TITLE
Setting up dynamic language switch

### ISSUE THREAD

**Issue by loxy** [Tinkoff/taiga-ui#2991]
### Discussed in https://github.com/Tinkoff/taiga-ui/discussions/2990

<div type='discussions-op-text'>

<sup>Originally posted by **loxy** October 31, 2022</sup>
Hi,

I cannot setup dynamic language switching like described here: https://taiga-ui.dev/i18n/Dynamic_loader

I copied the dynamic loading to our app module. But when changing via `this.switcher.setLanguage('english')` I get:

```sh
ERROR Error: Cannot find module './english'
    at .*$ chunkName: i18n-lazy- namespace object:1366:1
```

In this chunk I've found several entries like this (here only english):

```json5
// ...
"./english/addon-commerce.d": [
	4699,
	7,
	"i18n-lazy-42"
],
"./english/addon-commerce.d.ts": [
	4699,
	7,
	"i18n-lazy-42"
],
"./english/addon-editor.d": [
	1870,
	7,
	"i18n-lazy-44"
],
"./english/addon-editor.d.ts": [
	1870,
	7,
	"i18n-lazy-44"
],
"./english/addon-preview.d": [
	3976,
	7,
	"i18n-lazy-46"
],
"./english/addon-preview.d.ts": [
	3976,
	7,
	"i18n-lazy-46"
],
"./english/addon-table.d": [
	6475,
	7,
	"i18n-lazy-48"
],
"./english/addon-table.d.ts": [
	6475,
	7,
	"i18n-lazy-48"
],
"./english/core.d": [
	9147,
	7,
	"i18n-lazy-50"
],
"./english/core.d.ts": [
	9147,
	7,
	"i18n-lazy-50"
],
"./english/countries.d": [
	4312,
	7,
	"i18n-lazy-52"
],
"./english/countries.d.ts": [
	4312,
	7,
	"i18n-lazy-52"
],
"./english/english.d": [
	5875,
	7,
	"i18n-lazy-54"
],
"./english/english.d.ts": [
	5875,
	7,
	"i18n-lazy-54"
],
"./english/index.d": [
	7658,
	7,
	"i18n-lazy-56"
],
"./english/index.d.ts": [
	7658,
	7,
	"i18n-lazy-56"
],
"./english/kit.d": [
	6678,
	7,
	"i18n-lazy-58"
],
"./english/kit.d.ts": [
	6678,
	7,
	"i18n-lazy-58"
],
"./english/package.json": [
	6223,
	3,
	"i18n-lazy-60"
],
"./english/taiga-ui-i18n-languages-english.d": [
	5794,
	7,
	"i18n-lazy-61"
],
"./english/taiga-ui-i18n-languages-english.d.ts": [
	5794,
	7,
	"i18n-lazy-61"
],
// ...
```

Changing the dynamic loading to something like this:

```ts
@NgModule({
  providers: [
    tuiLanguageSwitcher(
      async (language: TuiLanguageName): Promise<unknown> =>
        import(
          /* webpackMode: "lazy" */
          /* webpackChunkName: "i18n-lazy-" */
          `@taiga-ui/i18n/languages/${language}/index.d`
          // also you can override the paths to your i18n language files
        ),
    ),
  ],
})
export class AppModule {}
```
solves this webpack issue but leads to 

```sh
2i18n-lazy-2.js:1 ERROR TypeError: Cannot read properties of undefined (reading 'dateTexts')
    at taiga-ui-i18n-tools.js:7:157
    at map.js:7:37
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at subscribe.innerSubscriber (switchMap.js:14:144)
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at map.js:7:24
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    ...
```

Can you elaborate more on how this should work or being set up? I'm lost and didn't found any hints in code base...

I'm on Taiga UI 3.8.0 and Angular 14

Best regards,
Kersten</div>

**Comment by splincode** [comment]
@loxy also could you please provide a minimal repro on github?

**Comment by loxy** [comment]
https://github.com/loxy/tui-dynamic-lang

**Comment by loxy** [comment]
Did someone already had a look? Can you reproduce?

**Comment by splincode** [comment]
Unfortunately, I didn’t have time yet, if you already have a ready-made solution, it will be great if you send a pull request

**Comment by loxy** [comment]
No problem. But didn't found solution neither

**Comment by AlexShi23** [comment]
I faced the same issue. I was helped by explicitly specifying the paths to the languages in app.module.ts
`        tuiLanguageSwitcher(
            async (language: TuiLanguageName): Promise<unknown> =>
            {
                if (language === 'russian') {
                    return import(`@taiga-ui/i18n/languages/russian`)
                }
                if (language === 'english') {
                    return import(`@taiga-ui/i18n/languages/english`)
                }
            }
        )`

**Comment by waterplea** [comment]
@loxy did you try solution from the message above? Did it work for you?

**Comment by loxy** [comment]
Yes, this seems to work. Except that the example leads to "Not all code paths return a value". But this was quickly fixed...

Is this now the "new way"?

**Comment by waterplea** [comment]
@splincode can you take a look please. If that is how this should be done we need to document this.
