### ISSUE TITLE
🐞 - responsiveness not working

### ISSUE THREAD

**Issue by andchir** [Tinkoff/taiga-ui#2996]
### Which @taiga-ui/* package(s) are the source of the bug?

styles

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/grid

### Is this issue blocking you?

Blocking

### Description

![ksnip_20221031-234045](https://user-images.githubusercontent.com/6392311/199106311-3ec6d332-a708-4720-b8e4-e079bba3bf6b.png)

https://taiga-ui.dev/grid
![ksnip_20221031-232014](https://user-images.githubusercontent.com/6392311/199103334-4e696d8a-87b4-40fd-b0ed-3f2362217954.png)

.tui-container_adaptive - I think columns that don't fit in the container should wrap to another row, not be truncated.

And why do you call it adaptability and not responsiveness? I think you mixed up the concepts.

### Angular version

14.0.0

### Taiga UI version

3.9.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by andchir** [comment]
```<tui-dropdown-host ...``` - This element looks very strange. It's on your demo too.

**Comment by andchir** [comment]
https://angular-cqfhyz.stackblitz.io/
![ksnip_20221101-122715](https://user-images.githubusercontent.com/6392311/199203070-2b11c8df-cf58-4e65-91d7-cdb8cd4416a9.png)

**Comment by waterplea** [comment]
The design for Taiga UI is made with following assumptions:
1. On desktop we show desktop content shrink up until certain size, after which horizontal scrollbar appears.
2. On tablet interface is supposed to scale with HTML meta tags.
3. On mobile we show mobile version

We should reflect this in the docs somehow to clear the confusion.

**Comment by andchir** [comment]
I understood you. Thanks for the answer. I think this task can be closed, but it is advisable to recommend another package for responsiveness somewhere in the documentation, because now it looks like a Bootstrap grid on the one hand, and on the other hand it doesn’t look like it for the reasons that I described above.
