### ISSUE TITLE
🚀 - Add to TuiInputTime mode only "HH"

### ISSUE THREAD

**Issue by nikitadubinsk** [Tinkoff/taiga-ui#3005]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

Add to TuiInputTime mode only "HH" so that only hours can be entered

**Comment by waterplea** [comment]
I wonder if it's much different from `InputNumber` with custom content with clocks icon 🤔

**Comment by waterplea** [comment]
I'm closing this as this can be achieved with current components.
