### ISSUE TITLE
🐞 - tui-avatar component does not work with blob

### ISSUE THREAD

**Issue by eruslan44** [Tinkoff/taiga-ui#3047]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-edaxtz

### Is this issue blocking you?

Blocking

### Description

Good afternoon. please tell me how to transfer the blob to tui-avatar correctly?

1. if I convert blob to url - `URL.createObjectURL(file)`
I get a warning - `WARNING: sanitizing unsafe URL value blob:http://localhost:4200/d8a8738f-fc5f-44b9-8408-67ad694bc831`

2. if I sanitizing the blob-url - `this.domSanitizer.bypassSecurityTrustUrl(url)`
I get an error message - `ERROR TypeError: _a.startsWith is not a function
    at get iconAvatar [as iconAvatar] (taiga-ui-kit-components-avatar.js:49:81)
    at set avatarUrlSetter (taiga-ui-kit-components-avatar.js:39:48)
    at TuiAvatarComponent.set (taiga-ui-cdk-decorators.js:125:1)
    at setInputsForProperty (core.mjs:10979:1)
    at elementPropertyInternal (core.mjs:10023:1)
    at ɵɵproperty (core.mjs:14446:1)`

### Angular version

13.2.2

### Taiga UI version

3.9.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Second approach with sanitizing URL is the correct one. We need to update type here:
https://github.com/Tinkoff/taiga-ui/blob/main/projects/kit/components/avatar/avatar.component.ts#L28
to support `SafeResourceUrl` and fix all related typing issues in the component. Would you be willing to submit a PR?
