### ISSUE TITLE
🐞 - Theme is not set for every component

### ISSUE THREAD

**Issue by rchks** [Tinkoff/taiga-ui#3054]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Is this issue blocking you?

Non-Blocking

### Description

The night theme cannot be set at every element on the page. In app component there is theme night tag and data-mode is 'onDark' but some elements in child components have a light theme color (button text, popup background and dropdown). But it affects to just a part of element, not the whole ones

![image](https://user-images.githubusercontent.com/53855462/201306654-79e9a218-812e-48af-b842-97a0b3fd7569.png)

![photo_2022-11-11_11-52-09](https://user-images.githubusercontent.com/53855462/201306718-98cb3b19-9a7b-4cbd-9e4f-933d52693f4d.jpg)

![photo_2022-11-11_11-52-34](https://user-images.githubusercontent.com/53855462/201307656-9a896442-d8cc-49a1-814a-80f97f06cd6b.jpg)

![photo_2022-11-11_11-52-282](https://user-images.githubusercontent.com/53855462/201307677-846209e6-b296-4aaa-8ce9-326a0cffcf6b.jpg)

![photo_2022-11-11_11-52-298](https://user-images.githubusercontent.com/53855462/201307954-87ea114e-8ed0-4169-891e-5cec10ce4b93.jpg)

Also element hint always has a light night background and tuiHintAppearance doesn't help for it.

![photo_2022-11-10_23-58-10](https://user-images.githubusercontent.com/53855462/201307148-804e7658-c20a-4d78-9a5a-19c379780fae.jpg)

What's the reason of this behavior?

### Angular version

14.1.2

### Taiga UI version

2.59.1

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux
- [X] iOS
- [X] Android

**Comment by waterplea** [comment]
This is very strange. Do you have a repository I can take a look at?

**Comment by rchks** [comment]
If it's needed, I can share element html code from a client at which device it can be caught. You can check all attributes and maybe it'll help you to determine a reason of the issue

![Screenshot 2022-11-11 at 21 56 43](https://user-images.githubusercontent.com/53855462/201413418-83d8c3a6-750c-4b70-ac41-25b941a06f16.png)
 
![Screenshot 2022-11-11 at 21 57 18](https://user-images.githubusercontent.com/53855462/201413437-b06576b0-c4a7-41be-b4df-549a8a2cb2dd.png)

![Screenshot 2022-11-11 at 21 57 22](https://user-images.githubusercontent.com/53855462/201413460-c574f976-24b0-4124-b592-13fe85562bdb.png)

About dropdown there's something strange bc hover state of element is working as it has a night theme
![Screenshot 2022-11-11 at 21 57 242](https://user-images.githubusercontent.com/53855462/201413537-dc53ec51-27b3-4b3a-a80c-ba585c24f2ad.png)

![Screenshot 2022-11-11 at 21 58 45](https://user-images.githubusercontent.com/53855462/201413559-bf31f52f-56be-4058-b7d9-f03ba5f6a998.png)

**Comment by waterplea** [comment]
The thing is, `tui-theme-night` overrides CSS variables across entire HTML. So it should be impossible to have dialog's background, which is `background: var(--tui-base-01);` to be white, when the very first line of `tui-theme-night` styles read:
```css
:root {
    --tui-base-01: #222;
```
Are you sure you haven't made some global style changes on your own?

**Comment by rchks** [comment]
> Are you sure you haven't made some global style changes on your own?

Yes, I am. Event if it had been changed, there would have been all gialog and all elements types like described above have the same behavior, wouldn't it? But in my case it affects to a part of some 'special elements'
Maybe it'll help to investigate the issue reason: I tried to set color-style for a button text forceable like this and it didn't help, button text is still in a light theme

![Screenshot 2022-11-12 at 17 12 37](https://user-images.githubusercontent.com/53855462/201532999-cf94b630-676d-47fa-a647-511683ae94de.png)

**Comment by waterplea** [comment]
I still don't understand how this can be possible unless something is altered on your end. If you have a particular component that doesn't work, say, a dialog on your screenshot, how about you try stripping down everything from your project to make a minimal reproduction that you could then share? Or maybe you will find that after removing something in particular, it would start working again. That's usually how I debug confusing stuff :)

**Comment by waterplea** [comment]
@rchks any news on trying to pinpoint when this issue starts appearing? Maybe you would be willing to jump on a screenshare session, if you cannot share your code on GitHub?

**Comment by waterplea** [comment]
I will have to close this as there is no way for us to address this issue. Feel free to reach out/comment here if you still face it and has a way to share reproduction with us somehow.
