### ISSUE TITLE
🤖 - [Eslint-plugin] add lint rule for simple text

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#3057]
### Description

<img width="627" alt="image" src="https://user-images.githubusercontent.com/12021443/201357591-b1b736c5-21ad-4211-bd18-12abac0716e6.png">

**Comment by waterplea** [comment]
@ddubrava you seem to be fond of making linting rules, care to lend a hand? :smile:

**Comment by ddubrava** [comment]
> @ddubrava you seem to be fond of making linting rules, care to lend a hand? 😄

yep, I can work on this, but you know, it seems weird that there isn't a rule for such a thing in `angular-eslint`, for instance. Maybe there are cases when `[userName]="'John'"` is ok?

**Comment by splincode** [comment]
should be `userName="John"`

**Comment by ddubrava** [comment]
> should be `userName="John"`

Yeah, that makes sense. I mean, it's an obvious mistake, and still, we don't have community rules to handle this.

**Comment by waterplea** [comment]
Asked Twitter about this. Maybe this way they want to highlight an error if such input is missing? 🤔

**Comment by waterplea** [comment]
Seems like it:
https://github.com/angular-eslint/angular-eslint/issues/1172

Also worth noting that if [title] is an input, with brackets it won't bind to the native title attribute, which can be a desired effect. Anyway, let's close this as not fit due to overgeneralization.
