### ISSUE TITLE
🐞 - FieldError displaying incorrectly on repeating inputs with max input length reached

### ISSUE THREAD

**Issue by dequubi** [Tinkoff/taiga-ui#3066]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/pipes/field-error#formArray

### Is this issue blocking you?

Non-Blocking

### Description

In `tui-input-phone` (maybe in other inputs, too) when you try to write past the character limit with the `tui-error` visible, it generates a lot of `tuiHeightCollapse` blocks.

https://user-images.githubusercontent.com/47535336/201718040-6a701d32-61b5-4bc3-b0ad-448fa44fee1e.mp4

### Angular version

14.2.2

### Taiga UI version

latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
This can probably be fixed inside `Error` component by adding:
```css
:not(:first-child) {
  display: none;
}
```
to the container with error inside. This would fix issue with multiple errors, but there's also an issue of error appearing **at all** in this case. Looks like the value is emitted before mask corrects it and then again after it does 🤔
