### ISSUE TITLE
📚 - Stackblitz Starter opens with no dependencies

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#3081]
### What is the affected URL?

https://taiga-ui.dev/stackblitz

### Description

1. Open https://taiga-ui.dev/stackblitz
2. It opens Stackblitz with no dependencies

<img height="500" alt="no-deps-starter" src="https://user-images.githubusercontent.com/35179038/202420740-6ad91ebe-1976-442a-ac94-94b8d60bbba0.png">

Linked issues:
- https://github.com/stackblitz/core/issues/2166

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
To reproduce problem locally, revert these changes:
* https://github.com/Tinkoff/taiga-ui/pull/3082

**Comment by markwhitfeld** [comment]
We have deployed a fix to the StackBlitz npm dependency resolver to support the non npm spec compliant package name used by the `@_ueberdosis/prosemirror-tables` down stream dependency. This should fix the issue that you are experiencing with your project dependencies 👍.
see: https://github.com/stackblitz/core/issues/2166

**Comment by waterplea** [comment]
That's great to hear, thank you, @markwhitfeld!
