### ISSUE TITLE
🐞 - Expression has changed after it was checked when using LineClamp 

### ISSUE THREAD

**Issue by bayburin** [Tinkoff/taiga-ui#3087]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-s61afv?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.less&hideExplorer=1

### Is this issue blocking you?

Non-Blocking

### Description

Hi! When I use tui-line-clamp element with *ngIf directive, I got error `ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for 'max-height': 'null'. Current value: '20'`

Example:
``` ts
// Component
ngOnInit() {
  setTimeout(() => {
    this.value = 'fake-value';
  }, 2000);
}
```

``` html
<!-- Template -->
<div *ngIf="value">
  <tui-line-clamp [content]="value" [lineHeight]="20" [linesLimit]="1"></tui-line-clamp>
</div>
```

![Снимок экрана 2022-11-18 в 20 12 03](https://user-images.githubusercontent.com/16703823/202714032-7338bfe6-4d86-4267-96dd-883c4a868051.png)

### Angular version

14.2.11

### Taiga UI version

3.10.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Fixed

```ts
export class AppComponent implements OnInit {
  value: string;

  constructor(private cd: ChangeDetectorRef) {}

  ngOnInit() {
    setTimeout(() => {
      this.value =
        'fake-value fake-value fake-value fake-value fake-value fake-value fake-value fake-value fake-value';

      this.cd.detectChanges();
    }, 2000);
  }
}
```

**Comment by bayburin** [comment]
> Fixed
> 
> ```ts
> export class AppComponent implements OnInit {
>   value: string;
> 
>   constructor(private cd: ChangeDetectorRef) {}
> 
>   ngOnInit() {
>     setTimeout(() => {
>       this.value =
>         'fake-value fake-value fake-value fake-value fake-value fake-value fake-value fake-value fake-value';
> 
>       this.cd.detectChanges();
>     }, 2000);
>   }
> }
> ```

Yes, that's how I've done it. But shouldn't it work without ChangeDetectorRef? It turns out that every time the state changes, you need to manually call the change detection. For example, I want to display an LineClamp only after the data has loaded.

**Comment by waterplea** [comment]
Yes, it should, of course. We'll investigate.
