### ISSUE TITLE
🐞 - InputDate opens current month and not the month of the maximum date

### ISSUE THREAD

**Issue by anastasiiabaranova** [Tinkoff/taiga-ui#3090]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/input-date/API?tuiMode=null&max$=1

### Is this issue blocking you?

Non-Blocking

### Description

If setting the maximum date for tui-input-date < the current month, then when you open the calendar, the current month of the current year is still opened, where all the days are locked (as they should be). Clicking on the arrow to go to the previous month immediately opens the month of the set maximum date, where you can choose something. So, in fact, one can still use the input, but the UX doesn’t seem to be great here.
It seems like it would be much nicer if the calendar would open the maximum possible month instead of the current one (when max month < current).

An example for this issue:
https://taiga-ui.dev/components/input-date/API?tuiMode=null&min$=1

<img width="649" alt="image" src="https://user-images.githubusercontent.com/59923026/202756310-53e9d187-f0a1-4cbf-92bf-2b148b2d64ae.png">

### Angular version

11.2.13

### Taiga UI version

2.57.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by oknimot** [comment]
I think that this is related to the computing of active month because the getter of value doesn't count with `min` and `max` values, so it basically computes only the current local month or month of the selected value to be displayed like default view.
```ts
get computedActiveYearMonth(): TuiMonth {
    if (this.items[0] && this.value && this.value.daySame(this.items[0].day)) {
        return this.items[0].displayDay;
    }

    return this.month || this.value || this.defaultActiveYearMonth;
}
```
