### ISSUE TITLE
🐞 - Missing Overseas France phone number codes (TUI_COUNTRIES_MASKS)

### ISSUE THREAD

**Issue by VictorienTardif** [Tinkoff/taiga-ui#3102]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Is this issue blocking you?

Blocking

### Description

We have Overseas France users who cannot fill in their phone number because the code does not exist in the `<tui-input-phone-international` component: 

- [La Réunion](https://fr.wikipedia.org/wiki/La_R%C3%A9union), [Mayotte](https://fr.wikipedia.org/wiki/Mayotte) et [autres territoires de l’Océan Indien](https://fr.wikipedia.org/wiki/Terres_australes_et_antarctiques_fran%C3%A7aises) (+262)
- [Guadeloupe](https://fr.wikipedia.org/wiki/Guadeloupe), [Saint-Martin](https://fr.wikipedia.org/wiki/Saint-Martin_(Antilles_fran%C3%A7aises)) et [Saint-Barthélemy](https://fr.wikipedia.org/wiki/Saint-Barth%C3%A9lemy_(Antilles_fran%C3%A7aises)) (+590)
- [Guyane](https://fr.wikipedia.org/wiki/Guyane) (+594)
- [Martinique](https://fr.wikipedia.org/wiki/Martinique) (+596)

### Angular version

12.2.7

### Taiga UI version

3.10.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
@VictorienTardif thank you for bringing this up. What do you suggest we name those regions? First 2 are rather lengthy. We also probably do not have flags for those regions, is French flag appropriate to use? What about the rest of the phone mask for them? Will you be willing to make a PR?

**Comment by VictorienTardif** [comment]
Actually it's the same code for different regions, the list should be:

- La Réunion : +262
- Mayotte : +262
- Guadeloupe : +590
- Saint-Martin : +590
- Saint-Barthélemy : +590
- Guyane : +594
- Martinique : +596

French flag is definitely the one to use. 
I can try to make a PR yes.
