### ISSUE TITLE
🐞 - Не работает атрибут [max] у компонента tui-files

### ISSUE THREAD

**Issue by strelok372** [Tinkoff/taiga-ui#3103]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-ujvfzd?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts&hideExplorer=1

### Is this issue blocking you?

Non-Blocking

### Description

Ограничение [max]="3" у компонента tui-files должно скрывать файлы которые мы добавили после превышения общего кол-ва файлов указанного в max, но этого не происходит

### Angular version

13.3.11

### Taiga UI version

3.3.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
This is working as expected, you need to put `*tuiItem` directive on `tui-file` so `tui-files` can count it and remove extra items from DOM, see this example:
https://taiga-ui.dev/components/input-files#With button

I've updated your stackblitz with a fix:
https://stackblitz.com/edit/angular-ujvfzd-h4kxrm

P.S. Also keep in mind that rejected files do not get into form control, you need to listen to them over `(reject)` output.

**Comment by strelok372** [comment]
Thanks!
