### ISSUE TITLE
🐞 - `PieChart` / `RingChart` mask doesn't work on `/next/` demo

### ISSUE THREAD

**Issue by DenisVinokurov** [Tinkoff/taiga-ui#3109]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-charts

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/next/components/ring-chart 

### Is this issue blocking you?

Blocking

### Description

В версии 3.10.0 выводится корректно, в next не корректно

### Angular version

14.x.x

### Taiga UI version

next

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
This issue is only reproducible on `/next/` subpath. Something's wrong with handling URL and base href here:
https://github.com/Tinkoff/taiga-ui/blob/main/projects/addon-charts/components/pie-chart/pie-chart.component.ts#L105
