### ISSUE TITLE
🐞 -TuiInputDateTimeComponent  value is not always displayed after transformation with TuiControlValueTransformer

### ISSUE THREAD

**Issue by AnitaKem** [Tinkoff/taiga-ui#3155]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-n7dmly?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fto-native-date-time.directive.ts&hideExplorer=1

### Is this issue blocking you?

Non-Blocking

### Description

I'm trying to use directive to transform value at TuiInputDateTimeComponent like in this example https://taiga-ui.dev/components/input-date-time#string-control-output

When I try to update this value, it is not displayed in control

### Angular version

13.3.4

### Taiga UI version

2.62.3

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by fullzero87** [comment]
bug is in writeValue function. It overrides base behaviour and skips valueTransformer logic.
I fix it by adding
value = this.value;
before 
this.nativeValue = value && (value[0] || value[1]) ? this.computedValue : ``;
value here is not [TuiDay, TuiTime] structure, so input gets empty string

**Comment by waterplea** [comment]
Hello @fullzero87, thank you for investigation. Will you be willing to make a PR for it?
