### ISSUE TITLE
🚀 - Allow for Embeds in Text Editor

### ISSUE THREAD

**Issue by KhaledGabr** [Tinkoff/taiga-ui#3158]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

addon-editor

### Description

There is often a need to adding embeds within the text editor for things like audio, video, etc. 

One option is doing it through iFramely. 
It takes a URL and generate the HTML automatically for the embed. https://iframely.com/domains

Popular text editors such as ckeditor integrates with it as well. 
https://ckeditor.com/docs/ckeditor5/latest/features/media-embed.html

**Comment by splincode** [comment]
https://taiga-ui.dev/editor/embed
