### ISSUE TITLE
🚀 - Add possibility to control Dialog closing 

### ISSUE THREAD

**Issue by Alexander-Panimash** [Tinkoff/taiga-ui#3181]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

core

### Description

For instance: 
We open Dialog(with closeable and dismissible options), fill some information and accidentally close this dialog by clicking outside or pressing escape button and  our information won't be saved. Usually there should be some kind of additional modal window with "Are you sure" question.
So it would be great if it could be possible to control dialog closing and if necessary preventing it with custom logic.
As i know in some  libraries it is implemented via base dialog interface and base closing method and if you want to add some custom logic you just override closing method

**Comment by waterplea** [comment]
I was thinking about this a bit, and I believe we should switch `closeable` type to `boolean | Observable<boolean>` which would allow people to implement "Are you sure?" confirmation dialogs.
