### ISSUE TITLE
🚀 - Ability to configure dropdown width for select component

### ISSUE THREAD

**Issue by r0ss0neri** [Tinkoff/taiga-ui#3201]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

**Problem:**

Select component [defines](https://github.com/Tinkoff/taiga-ui/blob/c79a7888cbdbf20686137cd1dd25116feacc612f/projects/kit/components/select/select.component.ts#L59) "fixed" width for own dropdown and there is no way to define other property (e.g. "auto").

<img width="541" alt="image" src="https://user-images.githubusercontent.com/24474497/206402051-45e5da65-0b86-4553-aaa5-fa01a5c4cf9d.png">

What do you think about to expose this option to be configured?

**Comment by waterplea** [comment]
It can be configured with `tuiDropdownLimitWidth` directive, please see this link with predefined parameters:
https://taiga-ui.dev/components/select/API?sandboxWidth=100&tuiDropdownLimitWidth=min

**Comment by r0ss0neri** [comment]
I see, thank you.

Seems there is a difference how property will be defined. When as attribute it's not working. Please check https://stackblitz.com/edit/angular-df3zya?file=src%2Fapp%2Fapp.component.html

Also, another use case when another control component will be added inside "tuiDataList". 
https://stackblitz.com/edit/angular-gdesm6?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts
