### ISSUE TITLE
🐞 - Change distance between label and its content according to the design spec

### ISSUE THREAD

**Issue by vladzavadsky** [Tinkoff/taiga-ui#3203]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Non-Blocking

### Description

Distance between label and its content should be 4px
![msg-1445385734-8482](https://user-images.githubusercontent.com/113680868/206458117-cda945d1-4947-4c31-9f4b-69f70b35f69d.jpg)

### Angular version

15.0.0

### Taiga UI version

3.12.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
fixed by https://github.com/Tinkoff/taiga-ui/pull/3242
