### ISSUE TITLE
🐞 - ExpressionChangedAfterItHasBeenCheckedError: Previous value for '_hosted_dropdown_focused': 'true'. Current value: 'false'

### ISSUE THREAD

**Issue by Benny739** [Tinkoff/taiga-ui#3212]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-editor

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Blocking

### Description

I'm using the color selector and getting the error:
```
ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value for '_hosted_dropdown_focused': 'false'. Current value: 'true'
```

It only happens when the hosted dropdown is in the root and the color selector in a lazy loaded module. The error happens when clicking inside one of the inputs or opening the mode dropdown

### Angular version

15.0.3

### Taiga UI version

3.12.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
@Benny739 please give it a shot with latest version 3.13.0, I think this might have gotten fixed.

**Comment by waterplea** [comment]
Since no response is given, I'll close it as I believe this issue was addressed in the mentioned PR.
