### ISSUE TITLE
🐞 - Sub dropdown after close gets additionally reopened and closed in left top corner

### ISSUE THREAD

**Issue by r0ss0neri** [Tinkoff/taiga-ui#3249]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-t2w7nv?file=src%2Fapp%2Fapp.component.ts

### Is this issue blocking you?

Blocking

### Description

The same issue which fixed before https://github.com/Tinkoff/taiga-ui/issues/997. Now we observe it again.

### Angular version

14.2.6

### Taiga UI version

3.13.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Managed to reproduce this on the StackBlitz, but only a couple of times out of many tries. If you know a stable way to reproduce it, please share to help investigation.
