### ISSUE TITLE
Add schematics for easy creating app. Drop and Dialog schematics.

### ISSUE THREAD

**Issue by AnteaterKit** [Tinkoff/taiga-ui#33]
# 🚀 Add schematics to the easy creating apps. Drop and Dialog schematics.

### Schematic helps to setup a project with taiga CDK.

We can to discuss it and I can help. What do you think?

**Comment by waterplea** [comment]
Hi @AnteaterKit 

Taiga UI consists of multiple layers of libraries. At the moment we are working on bringing remaining libraries to open source. There will be a Dialog component too, based on abstractions that you have in CDK so there will be an example.

So thanks for your interest, please wait a month or so until we release everything and then we can come back to this question.

**Comment by AnteaterKit** [comment]
Hi @waterplea 

Thank you for this open source library!

**Comment by waterplea** [comment]
@AnteaterKit hi again. Now that the rest of the library is out, do you have concrete questions regarding this subject?

**Comment by AnteaterKit** [comment]
hi. no, I haven't any questions. 
I found example 
drag and drop
https://github.com/TinkoffCreditSystems/taiga-ui/blob/main/projects/kit/components/input-file/input-file.template.html#L41
and there are a lot of dialogs/drop components based on portal. 
Thank you!
