### ISSUE TITLE
🐞 - Dropdown context menu does not close

### ISSUE THREAD

**Issue by ArcheoCodix** [Tinkoff/taiga-ui#3356]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-323fzw?file=src%2Fapp%2Fapp.component.ts

### Is this issue blocking you?

Non-Blocking

### Description

After opening the dropdown context menu, when you click outside to close it, it does not close and goes into a state where you can't select any options from the menu.

### Angular version

14.2.12

### Taiga UI version

3.15

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by vladimirpotekhin** [comment]
Hi! Did you only face the problem on stackblitz example or real project? I can't reproduce it outside of stackblitz 🤔

**Comment by ArcheoCodix** [comment]
Hi, yes, I found the bug in my project first.
When I wanted to see if the problem appeared on taiga-ui.dev, there was no bug on the demo, but on the stackblitz only.
The stackblitz I gave is a copy of the original demo.
