### ISSUE TITLE
📚 - Mapping of icons set is documented incorrectly

### ISSUE THREAD

**Issue by jekru** [Tinkoff/taiga-ui#3370]
### What is the affected URL?

https://stackblitz.com/edit/angular-ivy-wwdvcq

## Description

The mapping function from the [icons-set documentation](https://taiga-ui.dev/icon-set) is incorrect. If applied, the associated icon is not rendered correctly.

```ts
const MAPPER: Record<string, string> = { tuiIconCloseLarge: 'tui-icon-close-large' ];

// This is incorrect (from the documentation)
export function iconsPath(name: string): string {
    return `assets/icons/${MAPPER[name]}.svg#${MAPPER[name]}`;
}
```

A correct mapping function would be:

```ts
const MAPPER: Record<string, string> = { tuiIconCloseLarge: 'tui-icon-close-large' ];

export function iconsPath(name: string): string {
    return `assets/icons/${MAPPER[name]}.svg#${name}`;
}
```
The string behind the hashtag has to match the default name of the associated icon. In this case, the (correct) mapping function would return `assets/icons/tui-icon-close-large.svg#tuiIconCloseLarge`.

## Solution

Replace the mapping function from the documentation with a correct mapping function.

```ts
export function iconsPath(name: string): string {
    return `assets/icons/${MAPPER[name]}.svg#${name}`;
}
```

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [X] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
That mapping function assumes you processed you icons with `process-icons` script. That script creates a symbol inside SVG file with ID matching the name of the file, that's why it has to be `assets/icons/tui-icon-close-large.svg#tui-icon-close-large` **not** `assets/icons/tui-icon-close-large.svg#tuiIconCloseLarge`.
