### ISSUE TITLE
🐞 - Checkboxes not updated in submit mode

### ISSUE THREAD

**Issue by Oleg979** [Tinkoff/taiga-ui#3386]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-tqgx3q?file=src/app/app.module.ts

### Is this issue blocking you?

Blocking

### Description

tui-multi-select attached to form control with "on submit" update mode doesn't display checkboxes correctly when selecting new items

### Angular version

14.2.12

### Taiga UI version

3.15.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I think we can fix it by optionally injecting `TuiControl` and using its value if it exists, otherwise fallback to `NgControl`.
