### ISSUE TITLE
📚 - Drop tilde imports for all `.scss` code examples

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#3387]
### What is the affected URL?

https://taiga-ui.dev/getting-started#styles

### Description

Tilde imports have been deprecated in the Sass loader for a long time and they won't work with the new package format in Angular v13. 
See https://github.com/angular/components/commit/f2ff9e31425f0e395e6926bcaf48f876688000d8
Read more https://webpack.js.org/loaders/sass-loader/#resolving-import-at-rules

We should find all `sass` - code-examples and drop tilde.

For example: https://taiga-ui.dev/getting-started#styles
<img width="626" alt="Screenshot 2023-01-09 at 15 21 11" src="https://user-images.githubusercontent.com/35179038/211306912-cb7be238-7318-4cf2-8608-2d07cb6d31a5.png">

**Additional tasks:**
- [ ] Check that Angular 12 correctly imports without tilde
- [ ] Add migration for this case

**Comment by waterplea** [comment]
I think it is also not necessary for LESS, please check it.

**Comment by splincode** [comment]
less:
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/12021443/213710438-67f8975b-bcc5-4b0d-926c-f5205615d464.png">
