### ISSUE TITLE
🚀 - Option for having the `tui-dropdown` span the entire `tui-hosted-dropdown`, but have it only triggered on a certain element

### ISSUE THREAD

**Issue by arndwestermann** [Tinkoff/taiga-ui#3392]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

core

### Description

I can create a `tui-hosted-dropdown` like this, where I can specify with `tuiHostedDropdownHost ` which element is is hoverable for the dropdown to be opened.

```
<tui-root>
  <tui-hosted-dropdown
    [content]="dropdown"
    [(open)]="open"
    [tuiDropdownOffset]="0"
    [tuiDropdownAlign]="'left'"
    [tuiDropdownLimitWidth]="'fixed'"
    tuiDropdownHover
    [tuiDropdownShowDelay]="0"
    [tuiDropdownHideDelay]="0"
  >
    <div tuiGroup>
      <button
        tuiButton
        type="button"
        size="l"
        class="tui-group__auto-width-item"
        (click)="test()"
      >
        Button
      </button>
      <button
        tuiHostedDropdownHost <---- this
        tuiIconButton
        type="button"
        title="Menu"
        size="l"
        class="tui-group__auto-width-item"
        [iconRight]="icon"
      ></button>
      <ng-template #icon>
        <tui-svg
          src="tuiIconChevronDown"
          class="icon"
          [class.icon_rotated]="open"
        ></tui-svg>
      </ng-template>
    </div>
  </tui-hosted-dropdown>
  <ng-template #dropdown> Hello, World! </ng-template>
</tui-root>
```

This results in this

![image](https://user-images.githubusercontent.com/58134597/211496545-22321896-17db-4164-a039-0d8f4e6d7978.png)

But it would be nice to have an option that gives me the above functionality, but with this result, that the dropdown spans the whole host

![image](https://user-images.githubusercontent.com/58134597/211496710-d44ba871-bb24-44de-ac7a-403f51689718.png)

**Comment by waterplea** [comment]
I thought it behaved this way by default, that's what `tuiHostedDropdownHost` was for. Perhaps it got broken during complete rewrite of dropdowns for 3.0.
