### ISSUE TITLE
🚀 - Provide taiga-ui-theme.scss

### ISSUE THREAD

**Issue by jekru** [Tinkoff/taiga-ui#3396]
### Description

# Current State

There exists only a Less version of `taiga-ui-theme` : `@taiga-ui/core/styles/taiga-ui-theme.less`.

## Requested feature

It would be nice to also have a Sass version of `taiga-ui-theme`: `@taiga-ui/core/styles/taiga-ui-theme.scss`.

**Comment by nsbarsukov** [comment]
Hi!

You can use `taiga-ui-theme.less` with your pure CSS, SCSS and other projects. Angular resolves this less files automatically.

See https://taiga-ui.dev/getting-started#styles
<img width="756" alt="Screenshot 2023-01-10 at 17 14 32" src="https://user-images.githubusercontent.com/35179038/211574432-fcbc375e-f533-4b19-9f92-c4b55cbfeae5.png">

**Comment by jekru** [comment]
> You can use `taiga-ui-theme.less` with your pure CSS, SCSS and other projects. Angular resolves this less files automatically.

Currently we are using this option but it would be nice if it would be possible using `@import` to avoid implicit importing.

**Comment by nsbarsukov** [comment]
@jekru 
Unfortunately, it is too difficult to support both versions (`.less` + `.scss`) of the this file.

`taiga-ui-theme.less` contains only 4 imports (at the first glance, looks simple):
https://github.com/Tinkoff/taiga-ui/blob/e3bcca0239217c507cb2736b079b2e70132fe47e/projects/core/styles/taiga-ui-theme.less#L1-L4

But all of this imports contain huge amount of other imports.
For example, see one of them:
https://github.com/Tinkoff/taiga-ui/blob/e3bcca0239217c507cb2736b079b2e70132fe47e/projects/core/styles/theme/wrapper.less#L1-L12

To create `taiga-ui-theme.scss`-version, we should duplicate enormous amount of `.less`-files.
It is strictly violates DRY-principle without much need. 

I understand your desire to have possibility to import this file explicitly.
But if angular-way works, let's keep only this approach.

However, if you face any bugs with this approach, let's know.
We are ready to fix any bugs!
