### ISSUE TITLE
🚀 - `InputDate` & `InputDateRange` add `[valueContent]`-property

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#3401]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

New input-property should be similar to the same property from another components:

* https://taiga-ui.dev/components/multi-select/API?valueContent$=1
* https://taiga-ui.dev/components/input-slider/API?valueContent=TOP%20SECRET

**Example:**
![date-value-content-examples](https://user-images.githubusercontent.com/35179038/211756356-18c9057d-8d79-4fc2-9965-7ea3be74fd40.png)

becomes `10 March 2018 - 20 April 2018` on blur.

**Comment by waterplea** [comment]
Decided against that with design team.
