### ISSUE TITLE
🐞 - Providers are not injected in components instantiated with TuiDialogService.open in lazy modules

### ISSUE THREAD

**Issue by stanislav-osipov** [Tinkoff/taiga-ui#3406]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Is this issue blocking you?

Non-Blocking

### Description

After upgrading from Angular 13.x.x to 14.x.x providers are not injected into components opened/instantiated through `TuiDialogService.open(new PolymorpheusComponent(PopupComponent, this.injector))` in lazy modules. Error looks the same as injector is not provided as second argument to `PolymorpheusComponent` constructor at all.

Working example: https://stackblitz.com/edit/angular-wtq3mc?file=src%2Fapp%2Fmain%2Fmain.module.ts (Angular 14, taiga 3)
It worked with Angular 13 and taiga v2.69.0 as well and stopped working after upgrading to Angular 14.

### Angular version

14.2.12

### Taiga UI version

2.69.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
@stanislav-osipov so it doesn't work in Taiga 2 + Angular 14, but does work in Taiga 3 + Angular 14? I'm not sure we can spend resources fixing that as Taiga 2 is build with Angular 9, since Angular 12 it is recommended to use Taiga 3 because of complete abandonment of ViewEngine and switch to Ivy distribution.

**Comment by stanislav-osipov** [comment]
@waterplea correct, it works in taiga 3 and angular 14.

Got it. I was excpecting that it is not an easy fix when I researched the difference in dialog components instantiation between taiga 2 and 3.

We ended up putting required providers in app module before we upgrade to taiga 3.

Maybe it's worth to mention somewhere in docs, though?

**Comment by waterplea** [comment]
Ok, then I'm closing it as no fix planned because it works on latest version.
