### ISSUE TITLE
🚀 - tuiDropdownAlign support for 'center'

### ISSUE THREAD

**Issue by ParadoxSpiral** [Tinkoff/taiga-ui#3416]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

core, cdk

### Description

The current options for `tuiDropdownAlign` are `right` and `left`.

Is there an easy way to center-align a dropdown relative to the host element? I tried using negative margins, however that did not quite work out. If there is no easy way an option to `center` the dropdown would be a nice addition.

**Comment by waterplea** [comment]
Duplicate of https://github.com/Tinkoff/taiga-ui/issues/3704
