### ISSUE TITLE
🐞 - TS2415: Class 'TuiItemsWithMoreService' incorrectly extends base class 'Observable<number>'

### ISSUE THREAD

**Issue by DrBronsy** [Tinkoff/taiga-ui#3426]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Blocking

### Description

Error: node_modules/@taiga-ui/kit/components/items-with-more/items-with-more.service.d.ts:5:22 - error TS2415: Class 'TuiItemsWithMoreService' incorrectly extends base class 'Observable<number>'.
  Property 'max' is private in type 'TuiItemsWithMoreService' but not in type 'Observable<number>'.

5 export declare class TuiItemsWithMoreService extends Observable<number> {

<img width="972" alt="image" src="https://user-images.githubusercontent.com/79018425/212338011-a210ac32-c0ae-4c04-9925-d266c0f490b9.png">

### Angular version

14.2.7

### Taiga UI version

3.15.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
fixed by v3.16
