### ISSUE TITLE
🐞 - Bug in InputDateTime component when trying to overwrite it

### ISSUE THREAD

**Issue by sussie96** [Tinkoff/taiga-ui#3436]
### Which @taiga-ui/* package(s) are the source of the bug?

cdk

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/input-date-time/API

### Is this issue blocking you?

Blocking

### Description

There is a bug in the InputDateTime component.

**Reproducing** 
Type "01.11.2023, 11:11" and then press "Pos1" button it is not possible to type a new number. Same problem with "
10.11.2023, 23:15" and "05.02.1982, 02:54".
Following date works "12.12.1212, 12:12"

Therefore, it is not possible to use the component as an user correctly

### Angular version

14.0

### Taiga UI version

3.15.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Looks like a mask issue, completely new mask is under development right now, it would most likely solve this.
