### ISSUE TITLE
🚀 - custome colors for radio buttons

### ISSUE THREAD

**Issue by AchrafLance** [Tinkoff/taiga-ui#3442]
### Description

Hi, l am trying to create a block of radio buttons each with different color when selected. 
it seems like the wrapper is the way to go https://taiga-ui.dev/wrapper, but l don't seem to get anywhere with it since it changes the color of all the radio buttons at once.
is there a way to achieve this?

**Comment by AchrafLance** [comment]
idk if it's the optimal way, but l ended up creating three directives for the three colors, and in each directive l configured the dependency injection, example: 
`{
      provide: TUI_RADIO_OPTIONS,
      useValue: {
        ...TUI_RADIO_DEFAULT_OPTIONS,
        size: 'l',
        appearances: {
          checked: 'yellowRadio',
        },
      },
    },`

**Comment by waterplea** [comment]
Maybe it would be easier to override CSS variables like done here:
https://taiga-ui.dev/charts/legend-item#toggle

**Comment by waterplea** [comment]
I think I'll close this issue because there are already 2 valid ways to change colors, either with DI like you've implemented, or with CSS variables.
