### ISSUE TITLE
🚀 - Ability to define custom css variable for night theme

### ISSUE THREAD

**Issue by YuliaTsareva** [Tinkoff/taiga-ui#3446]
### Description

I would like to define CSS variable for color which has different values based on theme: one color for light theme and other color for night theme. As I only need one such variable, it would be great to be able to do it without creating whole custom theme.

**Comment by waterplea** [comment]
If you only have one such variable you can add binding next to night theme, for more complex styles you can create your own theme component and put next to the night theme:
```html
<tui-theme-night *ngIf="night"></tui-theme-night>
<tui-root [style.--my-var]="night ? 'black' : 'white'"></tui-root>
```
```html
<tui-theme-night *ngIf="night"></tui-theme-night>
<my-night *ngIf="night"></my-night>
```
