### ISSUE TITLE
🐞 - error TS2339: Property 'onMobileClick' does not exist on type 'TuiInputDateComponent' since 3.10.0

### ISSUE THREAD

**Issue by hheexx** [Tinkoff/taiga-ui#3448]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-mobile

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Blocking

### Description

error TS2339: Property 'onMobileClick' does not exist on type 'TuiInputDateComponent'.

179       this.input.onMobileClick();

since 3.10.0

### Angular version

14 or 15

### Taiga UI version

3.10.0

### Which browsers have you used?

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Sorry, do you have reproduction for current problem (stackblitz, github repo)?

**Comment by hheexx** [comment]
No, I don't see benefit of that.

onMobileClick function was removed in 3.10.0 from TuiInputDateComponent

I need workaround or any clue to what happened as I can't find anything relatable in changelog.

**Comment by splincode** [comment]
you can use `onIconClick` instead of `onMobileClick`

https://github.com/Tinkoff/taiga-ui/pull/2966

**Comment by hheexx** [comment]
thanks, thats it
