### ISSUE TITLE
📚 - Palette in dropdown code example is wrong

### ISSUE THREAD

**Issue by atoyansk** [Tinkoff/taiga-ui#3455]
### What is the affected URL?

https://taiga-ui.dev/next/components/color-picker#palette

### Description

The **Palette in dropdown** sample code was published just like its predecessor, **ColorSelector in dropdown**

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Sorry, I don't understand what is meant

**Comment by atoyansk** [comment]
> Sorry, I don't understand what is meant

In the documentation page https://taiga-ui.dev/next/components/color-picker there are 3 sample codes: "InputColor", "ColorSelector in dropdown" and "Palette in dropdown". If you check in Typescript and HTML tabs, you will see the same code for both "ColorSelector in dropdown" and "Palette in dropdown", but clearly the second one is wrong (it should be different code)

**Comment by splincode** [comment]
Oh, thank you, fixed: https://github.com/Tinkoff/taiga-ui/pull/3456
