### ISSUE TITLE
🐞 - Mobile Calendar opens on year 1900

### ISSUE THREAD

**Issue by hheexx** [Tinkoff/taiga-ui#3464]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-mobile

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Blocking

### Description

From few days ago (date triggered, not by taiga update) we have a problem with mobile calendar that it opens up on year 1900. Any ideas?

I am trying to debug this but as its urgent problem for us any hing would be useful.....

thanks.

![image](https://user-images.githubusercontent.com/103767/213442130-a5470cdb-a895-4d19-b2a6-cbee017a60cc.png)

### Angular version

14

### Taiga UI version

3.9, 3.15 tested

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by hheexx** [comment]
Part of code that I believe to be relevant. It sets activeYear to 1900.
![image](https://user-images.githubusercontent.com/103767/213446857-f4c9bd07-873f-4a04-923c-dd7d936a5dbe.png)

**Comment by splincode** [comment]
@hheexx create a PR please for fix

**Comment by hheexx** [comment]
I don't have fix yet.
I still don't understand why.

**Comment by hheexx** [comment]
I fixed problem by changing STARTING_YEAR to 2023.

I believe problem may be actually in cdk-virtual-scroll-viewport as it fires event scrolledIndexChange with parameter 2 when it should not.

**Comment by waterplea** [comment]
Thank you for investigating it. If you want, you can continue looking into it and fix is very welcome, because I'm not sure when we will be able to get to this task as we currently have a lot on out plate we must prioritize over this.
