### ISSUE TITLE
🐞 - InputSlider BUG

### ISSUE THREAD

**Issue by npc109** [Tinkoff/taiga-ui#3480]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/input-slider

### Is this issue blocking you?

Non-Blocking

### Description

When using firefox, the slider stretches only part of the length.  Firefox version 109.0

### Angular version

14

### Taiga UI version

3.15

### Which browsers have you used?

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
firefox

<img width="771" alt="image" src="https://user-images.githubusercontent.com/12021443/214036825-a6d900db-d7f6-40c1-a0bc-73e8e0b298c2.png">

chrome 

<img width="724" alt="image" src="https://user-images.githubusercontent.com/12021443/214036876-0299cafd-1a59-4af8-ba36-9ce3e7123a6a.png">
