### ISSUE TITLE
🚀 - Allow for forms in Text Editor

### ISSUE THREAD

**Issue by KhaledGabr** [Tinkoff/taiga-ui#3508]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

addon-editor

### Description

There is often a need to allow for specific elements to be in your text.  For example, a user may need to add a button, or an image with specific width style, etc. 

ex: Adding a button within text. 
- Button Label
- Button Url
- Button Color

ex: Adding an image with specific style:
- Image Url
- Image Alt text 
- Image caption
- Image size

![image](https://user-images.githubusercontent.com/17038667/214555372-f7ed7dd9-5412-462f-a4cd-8e49ac10ad8c.png)
![image](https://user-images.githubusercontent.com/17038667/214552660-c9f8867e-c9e0-4915-8a96-3d6a22a8c9ee.png)

In the example above, an image form group was defined to show image with a specific width. 

Would it be possible to define a **form component** (that can contain fields for any arbitrary need) that would be displayed within the text-editor, and defining **display component** that will display the element based on the data provided in the form.

**Comment by splincode** [comment]
Closed in favor of https://github.com/Tinkoff/tui-editor/issues/19
