### ISSUE TITLE
🐞 - ngZoneEventCoalescing without animations causes wrong initial position on some components

### ISSUE THREAD

**Issue by juanfran** [Tinkoff/taiga-ui#3514]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-mrvppt-jsouuz

### Is this issue blocking you?

Non-Blocking

### Description

Go to [stackblitz](https://stackblitz.com/edit/angular-mrvppt-jsouuz), open the hint by click or the select.

This is caused by  `ngZoneEventCoalescing: true`.

And disabling the animations.

```ts
{
  provide: TUI_ANIMATIONS_DURATION,
  useFactory: () => 0,
},
```
slowed down video:

![icon](https://user-images.githubusercontent.com/905195/214582924-56d8d730-474b-4093-9cf5-b65e5855b641.gif)

![input](https://user-images.githubusercontent.com/905195/214582935-394dd010-bc18-4e70-9d64-7f57efe9de42.gif)

### Angular version

15.0.0

### Taiga UI version

3.16.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
We should probably apply `visibility: hidden` to portals (hints, dropdowns) until first positioning data comes in from position accessor.

**Comment by juanfran** [comment]
Trying to fix the issue, I discovered another problem with the select component initial position. In this example, the dropdown is hidden until a position is set, so it is not the same issue as in my previous gif.

![select2](https://user-images.githubusercontent.com/905195/215069722-2e8dbe3b-4424-4305-9a7d-c96247c44f46.gif)

What is happening in this example is that the first render is done with an incorrect dropdown width. Then, the `TuiPositionService` runs again, this time with the correct dropdown width that is set in the `TuiDropdownComponent.update`. Therefore, we need two updates to correctly render the select.

The `console.log` is the left position.
