### ISSUE TITLE
🚀 - color input ability to hide mode and alpha, to change output format and to provide mask

### ISSUE THREAD

**Issue by KarimovDev** [Tinkoff/taiga-ui#352]
# 🚀 Feature request

### Is your feature request related to a problem?

 It would be great if we have ability to hide modes and alpha channel in color selector. Also it would be nice if we can change output formats and provide mask inside color input

### Describe the solution you'd like

 I've already done it. Look through PR, please

**Comment by splincode** [comment]
Close in favor of https://github.com/Tinkoff/tui-editor/issues/17
