### ISSUE TITLE
🐞 - Table Icons not found

### ISSUE THREAD

**Issue by KlyukinM** [Tinkoff/taiga-ui#3523]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-table

### Is this issue blocking you?

Non-Blocking

### Description

Table with virtual scroll is looking for tuiIconSortAscending.svg & tuiIconSortDescending.svg icons while sorting columns which are not included in folder 'node_modules/@taiga-ui/icons/src'.

Moreover these icons look exactly like tuiIconSortDown.svg & tuiIconSortUp.svg.

### Angular version

15.1

### Taiga UI version

3.15

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
Must be related to #3443 Did you update `@taiga-ui/icons` to the latest version?

**Comment by splincode** [comment]
`Did you update @taiga-ui/icons`
Yes, of course https://github.com/Tinkoff/taiga-ui/blob/main/projects/icons/package.json#L3
https://www.npmjs.com/package/@taiga-ui/icons/v/3.16.0

Check please, do you have `@taiga-ui/icons@3.16` inside node_modules?

`npm ls @taiga-ui/icons`

**Comment by hakimio** [comment]
@splincode the `@taiga-ui/icons` version question was directed to @KlyukinM

**Comment by KlyukinM** [comment]
Thanks guys! I had 3.15 version of icons and update solved the problem.
