### ISSUE TITLE
🐞 - Data list items truncated when window scale isn't equal 100%

### ISSUE THREAD

**Issue by sFeels** [Tinkoff/taiga-ui#3540]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Non-Blocking

### Description

Zoom in browser window using mousewheel  + ctrl/touchpad, then open dropdown and there won't be all items present in the list, and also it's impossible to scroll to them or find the missing options by search. 
After zooming out to normal scale everything works as usual.

UIKIT-6263

### Angular version

12.2.16

### Taiga UI version

2.58.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I'm having trouble reproducing it, can you record a video of this issue?

**Comment by splincode** [comment]
@sFeels Hello, please provide video reproduction bug in v3.x

**Comment by splincode** [comment]
Please, upgrade to v2.75 or v3.15 before

**Comment by waterplea** [comment]
We discussed this issue and it is caused by embedding Taiga UI section in a page as a web component and other pieces of the page overlay the edge of data list. We need to add `TUI_VIEWPORT` token to be able to provide custom edges of the screen to fix such cases and dropdowns being chopped in Editor. I'll make a PR for it.

**Comment by splincode** [comment]
@waterplea Do we have to make a cherry pick to v2.x?

**Comment by waterplea** [comment]
> @waterplea Do we have to make a cherry pick to v2.x?

No, that's a big feature, Dropdowns in 2.x behaved very differently.
