### ISSUE TITLE
🚀 - Implement country flags

### ISSUE THREAD

**Issue by axlito** [Tinkoff/taiga-ui#3562]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

icons

### Description

Implement **TuiCountryIsoCode** flags icons on **TuiSelectModule** or **TuiDataListModule**

**Comment by waterplea** [comment]
Probably a pipe `tuiFlag` would be a good solution:
```html
<img [src]="'AE' | tuiFlag" alt="United Arab Emirates" />
```
