### ISSUE TITLE
📚 - Stackblitz Starter is broken

### ISSUE THREAD

**Issue by evgeniy-em** [Tinkoff/taiga-ui#3578]
### What is the affected URL?

https://taiga-ui.dev/stackblitz

### Description

Open https://taiga-ui.dev/stackblitz

There is an error:

Error in turbo_modules/@taiga-ui/addon-editor@3.16.0/bundles/taiga-ui-addon-editor-extensions-starter-kit.umd.js

The entrypoint for '@tiptap/extension-blockquote' could not successfully be resolved. The file '/turbo_modules/@tiptap/extension-blockquote@2.0.0-beta.212/dist/index.d.cjs' does not exist. Please log an issue with the package author or check for an updated version of the package.

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Possible fix: https://github.com/Tinkoff/taiga-ui/pull/3576

**Comment by splincode** [comment]
https://github.com/ueberdosis/tiptap/issues/3717

**Comment by nsbarsukov** [comment]
@splincode should we close this issue ?
