### ISSUE TITLE
[TECH-DEPT] Investigate lightweight tokens pattern 

### ISSUE THREAD

**Issue by waterplea** [Tinkoff/taiga-ui#358]
See where we inject optional directives or use directives in queries see if we can improve bundle size by utilizing this pattern:
https://angular.io/guide/lightweight-injection-tokens#use-the-lightweight-injection-token-for-api-definition

**Comment by splincode** [comment]
is it relevant?

**Comment by waterplea** [comment]
In theory yes, but I'm not sure we have resources for this. I'll close it for now.
