### ISSUE TITLE
When current step is not the 1st Stepper doesn't scroll to active step

### ISSUE THREAD

**Issue by A1ternative** [Tinkoff/taiga-ui#3616]
### Which @taiga-ui/* package(s) are the source of the bug?

testing

### Is this issue blocking you?

Non-Blocking

### Description

Prerequisite: 1. there is a page with steps which contains stepper on top of the page. Complete this page till in example 3 step  ![Screenshot 2023-02-06 at 20 02 59](https://user-images.githubusercontent.com/43028709/217222736-f25fef6a-9897-4885-9d4e-49f2ee4306c2.png) 
2. close this page 

Test case: 
Open page from prerequisite again

Expected results: 
page opens on last saved step 3 and stepper scrolls to this active step

Actual results: 
page opens on last saved step, but stepper shows the begging of steps which are not active. Stepper doesn't scroll to active step: 
![Screenshot 2023-02-06 at 19 54 33](https://user-images.githubusercontent.com/43028709/217223005-d3d0e64a-9d98-43db-af15-f6abba7a54fa.png)

RU comment: степпер скролит шаги к текущему активному шагу, если передвигаться от 1го к последнему. Но если текуший активный шаг страницы не первый и страница ранее была закрыта (или например заполнялась на другом устройстве ранее), то при открытии степпер не покажет текущий активный шаг, а отмотает к первому

### Angular version

15.0.4

### Taiga UI version

2.74.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [X] Android

**Comment by A1ternative** [comment]
related to https://github.com/Tinkoff/taiga-ui/issues/3405

**Comment by splincode** [comment]
@A1ternative fixed by v2.76

**Comment by splincode** [comment]
Please reopen this issue, if it's still doesn't work in v2.76

**Comment by A1ternative** [comment]
it looks there is no way to reopen this issue, I'll raise one more

**Comment by A1ternative** [comment]
done

**Comment by splincode** [comment]
`it looks there is no way to reopen this issue` wow, sorry
