### ISSUE TITLE
🐞 - When current step is not the 1st Stepper doesn't scroll to active step

### ISSUE THREAD

**Issue by A1ternative** [Tinkoff/taiga-ui#3629]
### Which @taiga-ui/* package(s) are the source of the bug?

testing

### Is this issue blocking you?

Non-Blocking

### Description

Prerequisite: 1. there is a page with steps which contains stepper on top of the page. Complete this page till in example 3 step  ![Screenshot 2023-02-06 at 20 02 59](https://user-images.githubusercontent.com/43028709/217222736-f25fef6a-9897-4885-9d4e-49f2ee4306c2.png) 
2. close this page 

Test case: 
Open page from prerequisite again

Expected results: 
page opens on last saved step 3 and stepper scrolls to this active step

Actual results: 
page opens on last saved step, but stepper shows the begging of steps which are not active. Stepper doesn't scroll to active step: 
![Screenshot 2023-02-06 at 19 54 33](https://user-images.githubusercontent.com/43028709/217223005-d3d0e64a-9d98-43db-af15-f6abba7a54fa.png)

RU comment: степпер скролит шаги к текущему активному шагу, если передвигаться от 1го к последнему. Но если текуший активный шаг страницы не первый и страница ранее была закрыта (или например заполнялась на другом устройстве ранее), то при открытии степпер не покажет текущий активный шаг, а отмотает к первому. 

Additional info: 
this issue has been raised following by decision in https://github.com/Tinkoff/taiga-ui/issues/3616

### Angular version

15.0.4

### Taiga UI version

2.75.0

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [X] Android

**Comment by splincode** [comment]
@A1ternative do you use v2.76 or v2.74?
<img width="353" alt="image" src="https://user-images.githubusercontent.com/12021443/217516715-b28d7365-3de7-40c5-b76b-84bd57fe09fe.png">

**Comment by A1ternative** [comment]
Sorry. double checked with developers of our team 
taiga - 2.75
angular - 15

**Comment by splincode** [comment]
@vladimirpotekhin Hello, could you help please, what do you think is it related?

https://github.com/Tinkoff/taiga-ui/pull/3080
https://github.com/Tinkoff/taiga-ui/pull/3457

**Comment by vladimirpotekhin** [comment]
@splincode Hello, before #3080 / #3457 there was no automatic scrolling when changing the input at all. So that's not the reason

I can't reproduce the bug on [2.79](https://taiga-ui.dev/v2/navigation/stepper/API?tuiMode=null&activeItemIndex=3) - auto scroll works after demo page refresh 🤔 
Can you please check the latest 2.x or provide a reproduction on a stackblitz?

**Comment by vladimirpotekhin** [comment]
Hi, @A1ternative Can you please check the latest 2.x or provide a simple reproduction on a stackblitz?
I can't reproduce it in our demo. Check this link: stepper scroll to active item after page load https://taiga-ui.dev/v2/navigation/stepper/API?tuiMode=null&activeItemIndex=4

**Comment by A1ternative** [comment]
Hey @vladimirpotekhin, 
it looks strange. I see that it works in link you've provided: 
![image](https://user-images.githubusercontent.com/43028709/228449700-fffbcfc9-445f-4676-bcf1-b079a02c3fa3.png)
But it doesn't work in our application: the current active step is out of screen
![image](https://user-images.githubusercontent.com/43028709/228450096-04009f60-13f0-40bd-bf1b-06de5139e577.png)
Take a look at versions which we are using on the screenshot - 2.81

**Comment by waterplea** [comment]
@vladimirpotekhin we probably just need this in 2.x:
https://github.com/Tinkoff/taiga-ui/pull/4009

**Comment by splincode** [comment]
Reproduce:
https://github.com/Tinkoff/taiga-ui/pull/4039#issuecomment-1495373296
https://github.com/Tinkoff/taiga-ui/pull/4039#issuecomment-1495374673
