### ISSUE TITLE
🐞 - link component with icon

### ISSUE THREAD

**Issue by gennadiipetrov** [Tinkoff/taiga-ui#3642]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Is this issue blocking you?

Non-Blocking

### Description

link component from core has icon and distance between so distant, because icon 24px.

### Angular version

15.0.4

### Taiga UI version

3.15.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
We need to add CSS variable and use it for the icon size inside link component.
