### ISSUE TITLE
🐞 - Calendar month pagination doesn't work with Angular v15

### ISSUE THREAD

**Issue by ZhukAnna** [Tinkoff/taiga-ui#3648]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-6je2tk?file=src/app/app.component.ts

### Is this issue blocking you?

Non-Blocking

### Description

Calendar month pagination doesn't work with Angular v15. That issue is only in simple Calendar component, CalendarRange works well.

### Angular version

15.1.4

### Taiga UI version

3.17

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
The issue with this example is that you recreate `TuiDay` on each change detection cycle. It becomes a new object which is passed to `[value]` which in turn switches month back to the month of that value. If you memoize it, it would work.
