### ISSUE TITLE
🤖 - Stackblitz Codeflow project serve does not work

### ISSUE THREAD

**Issue by olegnowikow** [Tinkoff/taiga-ui#3655]
### Description

**My build:**
![image](https://user-images.githubusercontent.com/2184564/218185758-b49d7cfd-26d8-4428-958d-e0fd45ae8c4c.png)
**Another:**
![image](https://user-images.githubusercontent.com/2184564/218185820-6b21da43-ec4a-4f33-8a59-d22b376f4b91.png)

**Comment by splincode** [comment]
I can't reproduce now
