### ISSUE TITLE
🐞 - Multiple input in table

### ISSUE THREAD

**Issue by alexKefa** [Tinkoff/taiga-ui#3663]
### Which @taiga-ui/* package(s) are the source of the bug?

cdk

### Is this issue blocking you?

Blocking

### Description

When I am trying to access multiple input fields, the last one is only focusable and all the other inputs before this are not targetable. Acting as they do not exist. 

I tried to inspect and examine the behavior of the last input element compared to the other ones. Noticed no differences. 

Came to the conclusion that the autofill class or something is the issue. But can't target it either in html or css. (Tui table).

![image](https://user-images.githubusercontent.com/44241878/218424559-ce3baa5e-856b-46cc-853a-adcda1014c89.png)

Notice that the last input field is only targetable. The previous ones are ignored.

### Angular version

14.2

### Taiga UI version

Latest

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
@alexKefa Could you please add stackbtliz example?

**Comment by alexKefa** [comment]
Unfortunately, I can't reproduce the case on Stackblitz, hence the requests and the scenario seems to be unique.

**Comment by alexKefa** [comment]
I am pretty sure it's table.less file on the :before: , :after: pseudo elements. I inspect the DOM and that's what actually triggers. Any tip there?

**Comment by waterplea** [comment]
before/after elements in table are supposed to have pointer-events: none as they are just cosmetic. Can you maybe create a GitHub repo, if it's not possible to reproduce on StackBlitz?

**Comment by waterplea** [comment]
Also before/after elements are part of `appearance="table"` which is enabled in `tuiTable` component for inputs, but on your screenshot inputs look like regular textfields.

**Comment by waterplea** [comment]
@alexKefa any change you can create a GitHub repo? Otherwise I don't think we will be able to help.

**Comment by waterplea** [comment]
I guess this issue is stale and can be closed. Feel free to let us know if you still need help.
