### ISSUE TITLE
🐞 - Cursor freeze in case delete digits by DELETE button

### ISSUE THREAD

**Issue by MarenkovIgor** [Tinkoff/taiga-ui#3664]
### Which @taiga-ui/* package(s) are the source of the bug?

core, kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-tbtqsy?file=src/app/app.component.ts

### Is this issue blocking you?

Non-Blocking

### Description

inputNumber интересно себя ведёт при удалении цифр кнопкой delete:  delete не удаляет с переходом между группами разрядов. Пример удаляя от 1 000 000 нули, курсор и кнопка останавливается на пробеле не переходя в следующую группу разрядов.

Steps to reproduce:
1) Open https://stackblitz.com/edit/angular-tbtqsy?file=src/app/app.component.ts
2) Place cursor here: 1 |000 000
3) Press DELETE button (windows) 3 times, now you see 1| 000
4) Press DELETE again
5) Nothing happend

### Angular version

12.2.17

### Taiga UI version

3.17.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by Reactiver** [comment]
Got the same problem

https://user-images.githubusercontent.com/38430641/223370760-5006adfa-514e-431c-bccf-ae8286f9b6bc.mov
