### ISSUE TITLE
🐞 - Scroll to date isn't working in Mobile Calendar

### ISSUE THREAD

**Issue by sakuranasty** [Tinkoff/taiga-ui#3707]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-mobile

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts

### Is this issue blocking you?

Non-Blocking

### Description

Set date control 3 month after current date or open calendar and select that date.

Open calendar again.

Expected result: calenar is opened at the month of selected date.
Actual result: calendar opens at current date month.

Can be reproduced on ver. 3.x and 2.x

### Angular version

12

### Taiga UI version

2.64.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [X] Android

**Comment by splincode** [comment]
@sakuranasty hello, please provide stackblitz example

**Comment by sakuranasty** [comment]
https://stackblitz.com/edit/angular-z3rvyp?file=src/app/app.component.ts
https://angular-z3rvyp.stackblitz.io

In case these links don't work, you can open the first stackblitz example here 
https://taiga-ui.dev/v2/components/mobile-calendar#dropdown

**Comment by splincode** [comment]
please check here in v3:
https://taiga-ui.dev/components/mobile-calendar#dropdown

**Comment by sakuranasty** [comment]
Still doesn't work, the date is set for october 3 2020, but it scrolls to current date. Same for  year 2024. I'd like 2.x version patched too, because we can not switch to 3.x
