### ISSUE TITLE
🚀 - one toolbar for multiple editor windows

### ISSUE THREAD

**Issue by Meruem-Senpai** [Tinkoff/taiga-ui#3730]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

addon-editor

### Description

Add the ability to cut the toolbar from editors and make it the same for several editor windows.

Something like that

![issue](https://user-images.githubusercontent.com/57382654/220129174-7ccde823-5f18-4049-89e7-b08f0b39726a.png)

//edited

The structure of the component for which we need a separate toolbar

![Структура](https://user-images.githubusercontent.com/57382654/220143795-be33da66-e48d-4ecf-9b07-d72252d36d4a.png)

**Comment by splincode** [comment]
Closed in favor of https://github.com/Tinkoff/tui-editor/issues/21

**Comment by splincode** [comment]
@MerueMq-Dev https://taiga-family.github.io/editor/toolbar/shared
