### ISSUE TITLE
🐞 - Пропал нижний паддинг для первого шага tui-timeline-step

### ISSUE THREAD

**Issue by helennik** [Tinkoff/taiga-ui#3750]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Non-Blocking

### Description

Пропал нижний паддинг для первого шага tui-timeline-step из пакета proprietary-banking

![image](https://user-images.githubusercontent.com/25726433/220607107-9f16ca29-7286-4d62-9dd4-55bda87f7feb.png)

### Angular version

12.x.x

### Taiga UI version

2.78.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by vladimirpotekhin** [comment]
Fixed. It will be in the next release
