### ISSUE TITLE
🐞 - Custom passwordMatchValidator is not working using tui-error

### ISSUE THREAD

**Issue by corentingosselin** [Tinkoff/taiga-ui#3769]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Non-Blocking

### Description

My custom validator does not display the error, but can display other error like required.   

```    
 <tui-error
            formControlName="confirmPasswordControl"
            [error]="[] | tuiFieldError | async"
          ></tui-error>
```   
control:   

```  readonly form = new FormGroup(
    {
      emailControl: new FormControl('', [
        Validators.required,
        Validators.email,
      ]),
      passwordControl: new FormControl('', [
        Validators.required,
        passwordValidator(),
      ]),
      confirmPasswordControl: new FormControl('', [Validators.required]),
      lastNameControl: new FormControl('', [Validators.required]),
      firstNameControl: new FormControl('', [Validators.required]),
      pseudoControl: new FormControl('', [Validators.required]),
    },
    { validators: [matchPasswordValidator()] }
  );
```    

provider:   

``` 
 providers: [
    {
      provide: TUI_VALIDATION_ERRORS,
      useValue: {
        required: 'The value is required',
        email: 'Enter a valid email',
        invalidPassword:
          'Password must contain at least 8 characters, 1 uppercase, 1 lowercase, 1 number and 1 special character',
        passwordsDoNotMatch: 'Passwords do not match',
      },
    },
  ],
```     

### Angular version

15.1.0

### Taiga UI version

3.19.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by corentingosselin** [comment]
Found another way to bypass by using other custom validator:
https://dev.to/jdgamble555/angular-confirm-password-validation-custom-validator-3pkl

**Comment by waterplea** [comment]
Seems like the issue was with the validator since another one worked. Feel free to let us know if you still face this issue. Please provide StackBlitz reproduction in that case.
