### ISSUE TITLE
🐞 - Mobile keyboard overlaps dialog

### ISSUE THREAD

**Issue by viktorzdanovich** [Tinkoff/taiga-ui#3775]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://github.com/viktorzdanovich/taiga-ui-issues

### Is this issue blocking you?

Blocking

### Description

Steps to reproduce:
1) Tap "Pay" button
2) Tap "New card" button
3) Tap somewhere outside to dismiss focused field and hide the keyboard
4) Tap the card field

<details>
  <summary>Demo</summary>

  
![Simulator Screen Recording - iPhone 14 Pro Max - 2023-02-28 at 13 51 00](https://user-images.githubusercontent.com/19538300/221819435-acd12364-c7fe-41ee-ac05-1d7dff52fdfe.gif)

</details>

### Angular version

14.2.0

### Taiga UI version

3.19.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by splincode** [comment]
Please provide Safari/iOS version

**Comment by viktorzdanovich** [comment]
@splincode I've tested this on iPhone simulator on MacOS with the following setup:
- iPhone 14 Pro Max
- iOS 16.0

but I guess the issue can be reproduced on other setup as well

**Comment by waterplea** [comment]
@splincode I don't think that PR fixes it. The issue was with manual focus after dialog is already open.

**Comment by splincode** [comment]
`manual focus after dialog is already open` it's not possible in iOS, but:

<img width="1792" alt="ios-keyboard" src="https://user-images.githubusercontent.com/12021443/222735533-4493c273-183f-4f66-aa97-f3e3b997008f.png">

You can open the keyboard in advance until you need to focus on any element

https://user-images.githubusercontent.com/12021443/222735859-a7ff7ab4-30ac-464c-a8b9-cde6cb550fb2.mp4

**Comment by splincode** [comment]
the video shows that we first open the keyboard, and wait until the element we need appears and then call the focus method again

**Comment by waterplea** [comment]
Original issue was, user opens dialog, does something with input field, taps away. Then taps back to the input field and keyboard overlapped the dialog.

**Comment by splincode** [comment]
@waterplea I cant reproduce on our demo

https://user-images.githubusercontent.com/12021443/226096511-ff486924-6fd4-4fb9-8370-b946283fb7f0.MOV
