### ISSUE TITLE
🐞 - tui-reorder does not work correctly

### ISSUE THREAD

**Issue by vmcfire** [Tinkoff/taiga-ui#3780]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-table

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-f7o68u

### Is this issue blocking you?

Non-Blocking

### Description

the visible/invisible switch only works for the first element

https://www.awesomescreenshot.com/video/15220213?key=bb75e24de56666451654216d5160fb77

### Angular version

15.1.0

### Taiga UI version

3.17.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Hi @vmcfire, the video link doesn't work. I tried reordering and toggling items on/off on the stackblitz and it seems to work fine there. Could you please elaborate on the issue?

**Comment by vmcfire** [comment]
> Hi @vmcfire, the video link doesn't work. I tried reordering and toggling items on/off on the stackblitz and it seems to work fine there. Could you please elaborate on the issue?

HI @waterplea 
I updated the video link in the description, please check it. In the current version, I can't reproduce this issue. The tui-reorder is working correctly now. I will return this component to my project and reassemble the feedback from users. Thank you.
