### ISSUE TITLE
🐞 - Wrong dropdown position, if it's inside a fixed container on IOS

### ISSUE THREAD

**Issue by NikVolosatov** [Tinkoff/taiga-ui#3804]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-il7bfg

### Is this issue blocking you?

Blocking

### Description

 Steps to reproduce:

1. Tap "Account" field
2. Write something

### Angular version

15.*

### Taiga UI version

3.19.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by splincode** [comment]
Please, provide your Safari/iOS version

**Comment by NikVolosatov** [comment]
@splincode, I reproduced this on IOS16.1. But I believe it happens in other versions as well.

**Comment by waterplea** [comment]
Fixed by https://github.com/Tinkoff/taiga-ui/pull/3940 coming in next release
