### ISSUE TITLE
🐞 - upgrade ng-morph dependency in @taiga-ui/cdk

### ISSUE THREAD

**Issue by zoran995** [Tinkoff/taiga-ui#3805]
### Which @taiga-ui/* package(s) are the source of the bug?

cdk

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Blocking

### Description

`@taiga-ui/cdk@3.19.0` lists `ng-morph@2.1.0` as an optional dependency and it is no longer possible to install a new version locally and with that force a newer dependency version for `taiga-ui` as it was possible in 3.18.0. If I see correctly `taiga-ui` switched to the exact dependency version in 3.19.0.  
The reason why I am requesting a version upgrade is that ng-morph@3.1.0 depends on a vulnerable version of `minimatch`, can we fix this?

p.s.  npm audit is reporting this as a vulnerability issue and the recommended fix is to downgrade taiga-ui to 3.18.0

### Angular version

15.2.0

### Taiga UI version

3.19.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Feel free to provide PR fixing the version. I thought renovate would take care of that, @splincode ?

**Comment by splincode** [comment]
@waterplea we just ignore optionalDeps in renovate config, I think we can change it

**Comment by waterplea** [comment]
Sure, let's go for it.
