### ISSUE TITLE
🚀 - need help in docs

### ISSUE THREAD

**Issue by golu7679** [Tinkoff/taiga-ui#3808]
### Description

How can we modify the global color schema or color palette? eg: tui-primary color
can you please add another section in the docs where the user can see all the available classes listed in a categorized manner?
if both the things already exists in website, kindly share the link.

**Comment by hakimio** [comment]
> How can we modify the global color schema or color palette? eg: tui-primary color

Simply override the CSS variables in your global `theme.scss`
```css
:root {
    --tui-text-01: purple;
}
```
[Color docs page](https://taiga-ui.dev/colors)

You can find more info about CSS classes in [Foundations -> Styles](https://taiga-ui.dev/shadows).
