### ISSUE TITLE
[BUG] Cannot display table data

### ISSUE THREAD

**Issue by manhnd98** [Tinkoff/taiga-ui#381]
# 🐞 Bug report

### Description

- AfterViewInit - table display as expected
- When the user clicks on the button "click me" (link below), the table display list of rows without cells

https://user-images.githubusercontent.com/64095625/117581782-c5c8a000-b128-11eb-9b2c-c8a478775124.mov

### Reproduction

https://stackblitz.com/edit/angular-ass4ff

**Comment by waterplea** [comment]
Looks like an issue with auto-generated cells. It works of you explicitly define cells with structural directive (commented part). I'll look into it.

**Comment by splincode** [comment]
is it relevant?

**Comment by waterplea** [comment]
Seems like it is not, now that we are supposed to use `*ngFor` to iterate rows.
