### ISSUE TITLE
📚 - Stackblitz examples for Editor don't work

### ISSUE THREAD

**Issue by YuliaTsareva** [Tinkoff/taiga-ui#3815]
### Description

All the Stackblitz examples of Editor with images don't work for me.

https://taiga-ui.dev/editor/images/resizable
Error: NullInjectorError: No provider for HttpClient!

https://taiga-ui.dev/editor/images/preview
Error: Could not find template file './image-preview.template.html' (template should be inside image-preview folder, not in the app folder)

https://taiga-ui.dev/editor/images/upload
Error: Cannot find module '../../../../../../../environments/environment' or its corresponding type declarations.

But even if I fix errors, I still cannot attach image because of this console error: "Error: Class constructor NodeView cannot be invoked without 'new'"

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Also

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/12021443/226563403-b28ce647-6f75-47d3-b59c-b716a15421b4.png">

**Comment by YuliaTsareva** [comment]
Also it would be great to have a stackblitz example with default editor configuration like this one https://taiga-ui.dev/editor/setup/API

It will allow to explorer Editor features and reproduce bugs without pain.
