### ISSUE TITLE
🐞 - Multiselect: placeholder is clipped

### ISSUE THREAD

**Issue by maratkanatbaev** [Tinkoff/taiga-ui#3820]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-fc8wkp-rgxrn3?file=src/app/app.component.html

### Is this issue blocking you?

Non-Blocking

### Description

Placeholder is clipped
![Снимок экрана 2023-03-07 в 16 16 53](https://user-images.githubusercontent.com/13832499/223433136-2fa79f02-a271-4e5d-a760-d17c2ed09d55.png)

### Angular version

14.2.10

### Taiga UI version

3.19.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by hakimio** [comment]
@vladimirpotekhin Most likely PR #3339 caused the bug.

**Comment by vladimirpotekhin** [comment]
> @vladimirpotekhin Most likely the bug was introduced in PR #3339.

Thanks
