### ISSUE TITLE
🐞 - TuiPdfViewerService does not support long label

### ISSUE THREAD

**Issue by DerSizeS** [Tinkoff/taiga-ui#3837]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Non-Blocking

### Description

When TuiPdfViewerService#open called with long label and viewport width is not enough to display it, then it wraps to the next line, but header height does not increase, which leads to overlay of the label on viewer content

### Angular version

12.2.17

### Taiga UI version

2.64.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Needs white-space: nowrap + ellipsis.
