### ISSUE TITLE
📚 - `LineClamp` add `overflownChange` output to API page

### ISSUE THREAD

**Issue by karthikaruchamy** [Tinkoff/taiga-ui#3857]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.html

We have requirement where we need to show the shore more (toggle) button only when the number of lines in <=2. [Content] comes from the API and it may be either single line or 20 lines. We should show the button (Show More / Show Less) only if it has more than 2 lines and should be hidden if not. Is there any way we can achieve in <tui-line-clamp>

**Comment by waterplea** [comment]
`LineClamp` component has an undocumented output `overflownChange` which you can rely upon. I'll change this issue into documentation ticket so it would be added to the API page.

**Comment by karthikaruchamy** [comment]
overflownChange - Is it to show/hide? Is there way to check the folded line? I mean when I have the lengthy text without \n, how to check the multi folded line is > 2 lines?

**Comment by splincode** [comment]
Contributions welcome

**Comment by Suldenkov** [comment]
I met with a similar situation for one line. When the component loaded, overflownChange returned true when all content was show. After that, if I hid part of the content and showed it again, then overflownChange returned false

**Comment by waterplea** [comment]
This issue is about documentation, which now has a PR, I have created a new one regarding it falsely emitting `true`:
https://github.com/Tinkoff/taiga-ui/issues/4514
