### ISSUE TITLE
🐞 - Gigantic calendars in dropdown of InputDateRange

### ISSUE THREAD

**Issue by KlyukinM** [Tinkoff/taiga-ui#3859]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Non-Blocking

### Description

InputDateRange as well as all other dropdowns with calendar has huge font size and I found no way how to make it smaller:
![image](https://user-images.githubusercontent.com/108258153/224922557-5edb476e-07e1-49a1-971e-8de9d983ff94.png)

Meanwhile examples in the docs have no such problems:
![image](https://user-images.githubusercontent.com/108258153/224923300-096ad4f9-24e4-4aa3-8d19-e04203bbf2c3.png)

### Angular version

15.1

### Taiga UI version

3.20

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
`InputDateRange as well as all other dropdowns with calendar has huge font size and I found no way how to make it smaller:` 

@KlyukinM could you add an example to the stackblitz or github repository?

**Comment by KlyukinM** [comment]
Already found the root of the problem. Since all font sizes are in rem units they are depend on font size of the root html element which was 18px in my case. I change value to 16px and solved the problem.
