### ISSUE TITLE
🐞 - InputTime looks like focused when it is not

### ISSUE THREAD

**Issue by YuliaTsareva** [Tinkoff/taiga-ui#3885]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/stackblitz

### Is this issue blocking you?

Non-Blocking

### Description

I click on input-time and then on any other field on the page. Obviously, input-time is not focused anymore, but still looks focused.

You can reproduce it even [on the demo page](https://taiga-ui.dev/components/input-time#base). 

### Angular version

15.2.1

### Taiga UI version

3.19.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Confirmed
