### ISSUE TITLE
🐞 - Phone number for Mauritius is not good

### ISSUE THREAD

**Issue by Farhaanbeeharry** [Tinkoff/taiga-ui#3897]
### Which @taiga-ui/* package(s) are the source of the bug?

i18n

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/input-phone-international

### Is this issue blocking you?

Blocking

### Description

The length for Mauritius phone number can be either 7 or 8 digits but i18n allows only 7

Mauritius phone number can be in this format:
EITHER +230 XXX XXXX OR +230 XXXX XXXX

### Angular version

15.2.1

### Taiga UI version

3.20.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by Nurmaan** [comment]
Having same issue. Is there a timeline on the fix please?

**Comment by Jameel04** [comment]
Please fix the issue as I am having the same problem

**Comment by FuadTwaheerP** [comment]
Having the same issue from my side. Can't add the correct phone number. See the image below
![image](https://user-images.githubusercontent.com/128147357/225905032-e12556f6-5f96-4b79-8bba-07de703a8fba.png)

**Comment by Ouweshs28** [comment]
facing the same issue

**Comment by nsbarsukov** [comment]
As temporary fast workaround, I've opened this PR.
* https://github.com/Tinkoff/taiga-ui/pull/3901

It will change
```
+230 XXX XXXX => +230 XXXX XXXX
```

Now both phone formats can be typed (short and long).
Yes, I understand that short version of the mask is not visually perfect.
But it becomes less critical than previous version.
Other cosmetic improvement will be done in this issue later (it requires more complex refactoring to add support of conditional masking):
* https://github.com/Tinkoff/taiga-ui/issues/3900
