### ISSUE TITLE
🐞 - InputFiles size is not changing

### ISSUE THREAD

**Issue by GrinJ** [Tinkoff/taiga-ui#3898]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://taiga-ui.dev/components/input-files/API?size=m

### Is this issue blocking you?

Non-Blocking

### Description

Option size=m/l doesnt change the size of `<input-file />`, height is always 56px

### Angular version

15

### Taiga UI version

2 or 3

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
You are supposed to use CSS height for that as there is not such input as `size`. That being the case, looks like vertical padding is set so you cannot go below 56px, as well as `min-height` is present internally. This is what needs to be addressed in this ticket.
