### ISSUE TITLE
TuiPortalService - show use cases.

### ISSUE THREAD

**Issue by AnteaterKit** [Tinkoff/taiga-ui#39]
# 🚀 Could you describe some examples to use this API.

**Comment by waterplea** [comment]
Hello @AnteaterKit 

Thank you for your interest in our library. CDK is the base layer for more to come. We are in the process of open sourcing the rest. This service is used for dropdowns so show in "portals" above everything else. When we will release the rest of the library, I will come back here and direct you to the usage examples.

**Comment by waterplea** [comment]
Hi again. Here's an article where I explain the concept:
https://indepth.dev/posts/1417/demystifying-taiga-ui-root-component-portals-pattern-in-angular

If you have any more questions, feel free to start one in Discussions section
