### ISSUE TITLE
🐞 - It is not possible to specify inputmode in tui-input

### ISSUE THREAD

**Issue by meridos** [Tinkoff/taiga-ui#3902]
### Which @taiga-ui/* package(s) are the source of the bug?

core, kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-rtk3v8

### Is this issue blocking you?

Non-Blocking

### Description

In `tui-input`, you cannot specify input mode to display the numeric keypad, for example.

Because `tui-input-number` displays the default numeric keypad in ios, you cannot enter a negative value.

### Angular version

*

### Taiga UI version

3.20.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [ ] Android

**Comment by nsbarsukov** [comment]
It is strange because I remember that I already fixed it earlier:
* https://github.com/Tinkoff/taiga-ui/pull/2061

Something broken again.

**Comment by nsbarsukov** [comment]
@splincode probably it is connected with broken safari detection
* https://github.com/Tinkoff/taiga-ui/pull/3855

**Comment by splincode** [comment]
@nsbarsukov https://github.com/Tinkoff/taiga-ui/pull/3899
