### ISSUE TITLE
🐞 - if there is a lot of text in tui-legend-item, then dot icon shrinks

### ISSUE THREAD

**Issue by DerSizeS** [Tinkoff/taiga-ui#3903]
### Which @taiga-ui/* package(s) are the source of the bug?

addon-charts

### Is this issue blocking you?

Non-Blocking

### Description

If there is a lot of text in tui-legend-item, then dot icon shrinks

![image](https://user-images.githubusercontent.com/12021443/225965769-8bb193f5-8724-47d2-8afc-cb659ac39bea.png)

### Angular version

12.2.16

### Taiga UI version

2.78.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
`flex-shrink: 0` is needed
