### ISSUE TITLE
🐞 - TUI_ARROW_MODE doesn't work properly

### ISSUE THREAD

**Issue by sm4shz** [Tinkoff/taiga-ui#3927]
### Which @taiga-ui/* package(s) are the source of the bug?

kit

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-g55cb7

### Is this issue blocking you?

Non-Blocking

### Description

For now `interactive` and `disabled` fields of `TUI_ARROW_MODE` token accept only `PolymorpheusContent<T>` as their values. Expected that this will work with icon names passed as strings too.

### Angular version

12.2.17

### Taiga UI version

3.20.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
You can change icon by the name using `tuiArrowOptionsProvider`, `TUI_ARROW_MODE` is more for a complete change of the behavior of the icon and removing it altogether. Does this satisfy your needs?

**Comment by waterplea** [comment]
Ok, since no reply was given in a week and my message above explains this behavior and provides a workaround, I'm closing this as working as expected. Feel free to let us know if you still need some help with this.
