### ISSUE TITLE
🐞 - tui-svg cuts out big piece of svg, so it's doesn't show

### ISSUE THREAD

**Issue by echoinsane** [Tinkoff/taiga-ui#3936]
### Which @taiga-ui/* package(s) are the source of the bug?

core

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/angular-izcdjx?file=src%2Fapp%2Fapp.component.html

### Is this issue blocking you?

Non-Blocking

### Description

When using tui-svg, it cuts out big piece of svg, so final result doesn't show the image.

### Angular version

12.2.17

### Taiga UI version

3.21.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
That is DOMPurify config issue, unrelated to Taiga UI. As for `tuiSvgLinearGradientProcessor` problem see this issue:
https://github.com/Tinkoff/taiga-ui/issues/3952
