### ISSUE TITLE
🐞 - Квадратные тени на элементах

### ISSUE THREAD

**Issue by helennik** [Tinkoff/taiga-ui#3939]
### Playground Link

https://business.tinkoff.ru/sme/

### Description

Сломалось после обновления на mac os ventura
В хроме  Версия 111.0.5563.64 (Официальная сборка), (x86_64) отображаются квадратные тени на элементах  

### Angular version

-

### Taiga UI version

-

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
There's nothing we can do other than wait for Chrome to fix it.
