### ISSUE TITLE
🐞 - Editor: Code Block can be added via keyboard if field is empty

### ISSUE THREAD

**Issue by YuliaTsareva** [Tinkoff/taiga-ui#3941]
### Playground Link

Sorry, not this time :)

### Description

I'am trying to add code block via keyboard (```). If Editor is empty, backticks just disappear as soon as I press enter.
But if Editor already contains some text, then code block is added as it should be.

### Angular version

15.2.1

### Taiga UI version

3.21.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Also: https://tiptap.dev/api/nodes/code-block-lowlight
