### ISSUE TITLE
🐞 - Ошибка при создании текстовых полей с автоподстановкой

### ISSUE THREAD

**Issue by divnvp** [Tinkoff/taiga-ui#3959]
### Playground Link

https://taiga-ui.dev/components/input#autofill

### Description

При автоподстановке в текстовое поле сыпется ошибка в консоль:

![image](https://user-images.githubusercontent.com/74641968/227131573-3eb00533-e60a-4ae5-90b0-bf1b02bc6dca.png)

* Путём наблюдений было выявлено, что если убрать из input атрибут autocomplete, то ошибка не возникает.
* Также выявлено, что при старой версии такой ошибки не было. Появилась только при переходе на новую версию 3.21.0.

Всё бы ничего, но при использовании в своём проекте текстового поля с атрибутом autocomplete в консоль сыпется точно такая же ошибка, уже локально. А это не очень хорошо.

### Angular version

15.2.4

### Taiga UI version

3.21.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
@splincode please have a look. Most likely inputmode related.
