### ISSUE TITLE
🚀 - Make PullToRefresh work with scrollable content

### ISSUE THREAD

**Issue by VictorienTardif** [Tinkoff/taiga-ui#3979]
### Which @taiga-ui/* package(s) are relevant/related to the feature request?

addon-mobile

### Description

For now PullToRefresh disable the possibility to scroll but it is more common to have a scrollable content that triggers refresh when scrollTop is 0.

**Comment by AniramOcean** [comment]
PullToRefresh has only one type of loader, I would like to be able to select spinner with advanced features (like size, color, form, etc.)
It would be great to set custom height of refresh (like `distanceForRefresh` attribute in [ngx-pull-to-refresh](https://github.com/YeongCheon/ngx-pull-to-refresh/blob/master/README.org#attribute))
