### ISSUE TITLE
🐞 - New dependency that breaks build in 3.21(at least)

### ISSUE THREAD

**Issue by Alexander-Panimash** [Tinkoff/taiga-ui#3982]
### Playground Link

https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.html&hideExplorer=1

### Description

After upgrading from taiga-ui 3.15 to 3.21 there is new dependency that breaks the build
for example you can check this repository
https://github.com/Alexander-Panimash/test-taiga-ui/tree/master/test-taiga-ui
<img width="1197" alt="image" src="https://user-images.githubusercontent.com/56683240/227562284-df30c9ef-2606-4563-9cb8-5af1249f8b68.png">

### Angular version

14, 15

### Taiga UI version

3.21

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by Alexander-Panimash** [comment]
The Issue reason was on my side, thank you!

**Comment by splincode** [comment]
@Alexander-Panimash please, explain me about

**Comment by Alexander-Panimash** [comment]
Sorry, i changed the information in .npmrc but the issue is still reproducible for me
