### ISSUE TITLE
🚀 - Add `tuiIsPresent` pipe to v2

### ISSUE THREAD

**Issue by ddubrava** [Tinkoff/taiga-ui#3991]
### Which @taiga-ui/* package(s) are relevant/related to the feature request?

cdk

### Description

It would be great to add a [tuiIsPresent](https://github.com/Tinkoff/taiga-ui/tree/main/projects/cdk/pipes/is-present) pipe to v2 since only an exported function is currently available.

**Comment by ddubrava** [comment]
Let me know if I can work on this

**Comment by splincode** [comment]
Could you create a cherry pick to v2?

**Comment by ddubrava** [comment]
Sure
