### ISSUE TITLE
🐞 - incorrect work nested dropdown using `tuiDropdownHover`

### ISSUE THREAD

**Issue by olegnowikow** [Tinkoff/taiga-ui#4056]
### Playground Link

https://stackblitz.com/edit/angular-fwx3yj?file=src%2Fapp%2Fapp.component.html

### Description

https://user-images.githubusercontent.com/2184564/228928050-d7019ba3-9c29-4ed3-b93d-e0789d9c3cc0.mp4

### Angular version

15.2.3

### Taiga UI version

3.20.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
After updating to the new version, please also move `ng-template` under `tui-hosted-dropdown` so that it is under `tuiDropdownHover` in DI tree.
