### ISSUE TITLE
📚 - How to close a custom dialog by outside click?

### ISSUE THREAD

**Issue by omqmo** [Tinkoff/taiga-ui#4075]
### Description

How to close a custom dialog by outside click? 
How to redo this example (https://taiga-ui.dev/dialog/custom) so that the dialog close when you click on overlay layer?

**Comment by waterplea** [comment]
Logic for outside click and Escape button is isolated in `TuiDialogCloseService`. You need to provide it in your custom dialog, [subscribe to it and close dialog upon emission](https://github.com/Tinkoff/taiga-ui/blob/main/projects/core/components/dialog/dialog.component.ts#L61-L74). I have updated the example on the page you linked.
