### ISSUE TITLE
🚀 - Add a small guide about using ng-polymorpheus from within taiga-ui

### ISSUE THREAD

**Issue by evantrimboli** [Tinkoff/taiga-ui#4080]
### Description

```
<ng-template #template="polymorpheus" [polymorpheus]="context" let-item>
    {{ item.toFixed(2) }} <-- type 'number'
</ng-template>
```

I want to be able to strongly type some templates and `ng-polymorpheus` came up as a result on Google. However, I saw some posts indicating that I shouldn't install it separately and it's already included in the CDK. How do I use it from within `taiga-ui`? A couple of small examples would be great.

**Comment by waterplea** [comment]
That should rather be a [Discussion](https://github.com/Tinkoff/taiga-ui/discussions), not an issue. Yes, it is installed with `@taiga-ui/cdk`. Polymorpheus v3 is with Taiga UI v2 and Polymorpheus v4 with Taiga UI v3. You can check out [the code for the template](https://github.com/Tinkoff/ng-polymorpheus/blob/master/projects/ng-polymorpheus/src/directives/template.ts) directive. You have posted code snippet in your message, if you then want to use the typed template you can just pass `template.template` to wherever you need a template (`template: TemplateRef<C>` is a public property of `PolymorpheusTemplate` directive). If you plan on using `*polymorpheusOutlet` directive, you can pass the entire `template`. It would then try to sync change detection of _declaration_ and _instantiation_ views through `check` public method of `PolymorpheusTemplate`.
