### ISSUE TITLE
🐞 - Remove icon doesn't disappear after dragging in

### ISSUE THREAD

**Issue by GrinJ** [Tinkoff/taiga-ui#4117]
### Playground Link

https://taiga-ui.dev/components/input-files#multiple

### Description

Steps to reproduce:
1. Add some files (2 or more)
2. Hover the file
3. Press the X mark with left-click and drag it
4. X button will be there forever and focusOut doesn't hide it
5. After hover another file you can see 2 X buttons
![image](https://user-images.githubusercontent.com/4682965/230064740-16c9dccf-2be0-4bf2-9bbc-37443993c94e.png)

### Angular version

15

### Taiga UI version

2 & 3

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Focus out does hide it. It remains visible because it is focused. If you click away or press `Tab` it would disappear. I'll add `:focus-visible` style so it is more apparent when you focus it with keyboard, but for mouse this behavior is expected.

**Comment by waterplea** [comment]
Actually, I just removed focus from mouse as it seems unnecessary. Now PR completely solved the describe issue.
