### ISSUE TITLE
🚀 - Demo modules as an npm package

### ISSUE THREAD

**Issue by constantant** [Tinkoff/taiga-ui#4119]
### Description

While theme customising it always needs to check how all core Taiga components look and feel depending on the changing css variables. For today it costs a lot to move and support `demo`.

I suppose it must be an additional to `@taiga-ui/addon-doc` package which contains all demos represented on `demo`. 

As an example you can look at [resources](https://github.com/angular/material2-docs-content) for [material.angular.io](https://github.com/angular/material.angular.io/blob/main/package.json#L38) .

I believe it will enhanced the way of migration to the library for many teams.

**Comment by waterplea** [comment]
I don't think this is something we would invest resources into. You might just as well clone our repository, add this to `package.json`:
```json
"your_library": "path_to_github_or_local_folder",
```
Add `<your-custom-theme />` at the bottom of our `app.template.html` and do pulls whenever you want to update it to check the latest code with your custom theme. Same with DI customizations.

**Comment by constantant** [comment]
@waterplea exactly this way you talking about is too expensive and messy. I have  monorepo with bunch of libs and apps, so I would love to avoid cloning 50+ Mb into it yet.

**Comment by waterplea** [comment]
You can also use Git submodule or any other solution at your end. Borderline is, the code is out in public and we don't have the resources to dedicated to this task.
