### ISSUE TITLE
🤖 - `No use of tuiAssert without ngDevMode` eslint rule

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#4150]
### Description

<img width="418" alt="image" src="https://user-images.githubusercontent.com/12021443/230601156-d9e80f72-d283-4b4f-a7e2-1af5b83699fc.png">

**Comment by waterplea** [comment]
@ddubrava if you want to help with linters again, it would be appreciated :)

**Comment by ddubrava** [comment]
hey, ye, will work on this
