### ISSUE TITLE
🐞 - Broken `z-index` for 2-dimensional sticky tables

### ISSUE THREAD

**Issue by waterplea** [Tinkoff/taiga-ui#4151]
### Playground Link

https://taiga-ui.dev/components/table#editable

### Description

![image](https://user-images.githubusercontent.com/11832552/230614618-936367e7-b6a9-4f78-a4e5-527238086952.png)

### Angular version

any

### Taiga UI version

3.22.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by sumitshinde-84** [comment]
I would like to work on this issue,  can you please assign it to me?

**Comment by splincode** [comment]
@sumitshinde-84 sure

**Comment by sumitshinde-84** [comment]
may be issue is already resolved, if not please tell me issue is exactly where?
![Screenshot_2023-04-10_10-27-57](https://user-images.githubusercontent.com/110285294/230830118-ede61d17-d825-4823-8163-c72e704b4378.jpg)

**Comment by waterplea** [comment]
> may be issue is already resolved, if not please tell me issue is exactly where?
> ![Screenshot_2023-04-10_10-27-57](https://user-images.githubusercontent.com/110285294/230830118-ede61d17-d825-4823-8163-c72e704b4378.jpg)
> 
> 

It happens when you make the screen width smaller and scroll the table horizontally.
