### ISSUE TITLE
🐞 - `TuiSheet` opens not it the bottom of the page with height less than 100vh

### ISSUE THREAD

**Issue by evgeniy-em** [Tinkoff/taiga-ui#4166]
### Playground Link

https://stackblitz.com/edit/angular-9tk9kb

### Description

When page has not enough content to fill 100vh, TuiSheet opens in the bottom of page content, not in the bottom of the browser window

### Angular version

12

### Taiga UI version

3.23.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Looks like we're missing `height: 100%` on the `tui-root`, I wonder if we can safely put it there 🤔

**Comment by evgeniy-em** [comment]
> Looks like we're missing `height: 100%` on the `tui-root`, I wonder if we can safely put it there 🤔

I guess no, because otherwise there could be problem with vertically scrolled pages

**Comment by waterplea** [comment]
> > Looks like we're missing `height: 100%` on the `tui-root`, I wonder if we can safely put it there 🤔
> 
> I guess no, because otherwise there could be problem with vertically scrolled pages

There shouldn't be, because overflow: visible would still make them properly scrollable. However if we can fix it without that it would be better. The reason the sheets host is sticky at the bottom and not fixed is so it does properly stick to the bottom during the address bar disappearance on iOS.

**Comment by evgeniy-em** [comment]
> > > Looks like we're missing `height: 100%` on the `tui-root`, I wonder if we can safely put it there 🤔
> > 
> > 
> > I guess no, because otherwise there could be problem with vertically scrolled pages
> 
> There shouldn't be, because overflow: visible would still make them properly scrollable. However if we can fix it without that it would be better. The reason the sheets host is sticky at the bottom and not fixed is so it does properly stick to the bottom during the address bar disappearance on iOS.

I mean problem with TuiSheet again.
https://stackblitz.com/edit/angular-9tk9kb-3jjtcb

**Comment by waterplea** [comment]
Fixed in a new `SheetDialog` component that we plan to use instead of `Sheet`.
