### ISSUE TITLE
🐞 - Mobile keyboard overlaps dialog modal on Mi Browser

### ISSUE THREAD

**Issue by viktorzdanovich** [Tinkoff/taiga-ui#4167]
### Playground Link

https://taiga-ui.dev/components/dialog#pay

### Description

When opening a modal window with autofocused input, mobile keyboard overlaps a half of it on Android Mi Browser.
The issue is also reproducible when consequently defocusing and focusing the input.

See attachement.

https://user-images.githubusercontent.com/19538300/230859747-431d0089-b2d2-4c19-85f8-242b933817d0.mp4

### Angular version

15.2.0

### Taiga UI version

3.21.1

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [X] Android

**Comment by waterplea** [comment]
I got Xiaomi, will try to figure it out.

**Comment by waterplea** [comment]
This is a decade old issue with Mi Browser:
https://xiaomi.eu/community/threads/keyboard-is-overlapping-text-fields-in-miui-browser.9716/

Virtual keyboard overlays content so you cannot even access inputs at the bottom of regular page. Unfortunately, there's no way to tell when the virtual keyboard is open in Mi Browser - it doesn't support VirtualKeyboard API and does not change viewport size upon opening. So this is an issue we cannot fix. 

Considering this issue forbids proper use of any web page with inputs at the bottom and it remained so for over 10 years, I doubt Mi Browser has any reasonable user share. It is also filled with built-in ads and users can just install Chrome, I recommend some browser detection to show message to switch to a different browser.
