### ISSUE TITLE
🐞 - Strong background dimming when opening a dialog on top of the tui-sheet on mobile

### ISSUE THREAD

**Issue by Jonesso** [Tinkoff/taiga-ui#4183]
### Playground Link

https://stackblitz.com/edit/angular-t9kzga?file=src/app/app.component.ts

### Description

If you open a dialog on the top of `tui-sheet` in mobile resolution, it appears that their dimming effects are overlapping, causing the background beneath them to become almost completely black.

### Angular version

12.2.17

### Taiga UI version

2.77.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [X] iOS
- [X] Android

**Comment by waterplea** [comment]
Fixed in a new `SheetDialog` component that we plan to use instead of `Sheet`.
