### ISSUE TITLE
🚀 - Add possibility to disable pseudo-link text-decoration (v2, v3)

### ISSUE THREAD

**Issue by rpetrukhin** [Tinkoff/taiga-ui#4188]
### Description

Currently, if you use link component with the `[pseudo]` attribute, it adds text-decoration to the link (https://taiga-ui.dev/v2/components/link/API?tuiMode=null&pseudo=true). It would be great to be able to disable it using, for example, another attribute or css variable.

**Comment by waterplea** [comment]
That is per design. You can just use `<button tuiLink ...>` for the desired effect.
