### ISSUE TITLE
🚀 - Improve documentation for Svg component

### ISSUE THREAD

**Issue by ddubrava** [Tinkoff/taiga-ui#4248]
### Description

It's not clear how to use `TUI_SVG_OPTIONS`, `tuiSvgOptionsProvider` and how to migrate from deprecated `TUI_ICONS_PATH`.
See this page - https://taiga-ui.dev/components/svg

**Comment by waterplea** [comment]
> > Are you interested in contributing? :)
> 
> Hey, I can work on this, but it would be great if you provide some context how to work with `TUI_SVG_OPTIONS`. Should we just use `tuiSvgOptionsProvider` and that's it?

Basically, it works as ask other config DI options, you provide partial object and the rest is filled with defaults, so yes, using this method is recommended. As for the token — it's just an object combination of previous tokens available separately.

**Comment by ddubrava** [comment]
ok, that makes sense. So, there are many pages related to SVG, such as [icons](https://angular-kit-qa.tcsbank.ru/icons), [icon set](https://angular-kit-qa.tcsbank.ru/icon-set), [svg](https://angular-kit-qa.tcsbank.ru/components/svg), [marker icon](https://angular-kit-qa.tcsbank.ru/components/marker-icon), and [svg service](https://angular-kit-qa.tcsbank.ru/services/svg-service). All of these pages have certain prerequisites, such as `tuiSvgOptionsProvider` and `NgDompurifySanitizer` configurations. Would it be possible to create a general page that contains all of the necessary information? Currently, it is quite complicated to find the required setup since the information is spread out across multiple pages

**Comment by waterplea** [comment]
Yes, that could be a good idea. That new page can be put in See Also of all those existing page, related to SVGs.

**Comment by splincode** [comment]
https://taiga-ui.dev/icons/overview
