### ISSUE TITLE
🐞 - Checkbox Block is unable to adapt to a custom height size

### ISSUE THREAD

**Issue by constantant** [Tinkoff/taiga-ui#4259]
### Playground Link

https://stackblitz.com/edit/angular-m8v7na?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.less&hideExplorer=1

### Description

The [CheckboxBlock](https://taiga-ui.dev/components/checkbox-block) component has non-adapted checkbox positioning to a custom height size.
https://github.com/Tinkoff/taiga-ui/blob/main/projects/kit/components/checkbox-block/checkbox-block.style.less#L86-L116

It causes the following issue

![checkbox-block-l](https://user-images.githubusercontent.com/5537730/233440612-70804e1a-12c0-46c2-b1f5-1f8600cee866.gif)

### Angular version

12.2.7

### Taiga UI version

3.25.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Our design system requires it to be aligned - to top. I believe it can be solved by using padding-top: calc(var(--tui-height-xxx) / 2) and transform: translateY(-50%) on the checkbox.
