### ISSUE TITLE
🐞 - Icons are broken and cropped

### ISSUE THREAD

**Issue by ddubrava** [Tinkoff/taiga-ui#4268]
### Playground Link

I can't reproduce it, it seems that the problem is only with proprietary icons.

### Description

Dialog icons (and not just dialogs) are cropped in version `3.25.0`.

![image](https://user-images.githubusercontent.com/22116465/233642803-fecf3717-d408-4a80-bfa7-df657b98dc53.png)

In version `3.24.0`, icons are also cropped when using `tuiSvgOptionsProvider` instead of `TUI_ICONS_PATH`.

```
/**
 * @todo should be replaced with NgDompurifySanitizer
 *   but for now it's broken if used with a deprecated TUI_ICONS_PATH
 */
{
    provide: TUI_SANITIZER,
    useValue: unsafeSanitizer,
},
/**
 * @todo should be replaced with tuiSvgOptionsProvider
 *   but for now it's broken
 */
{
    provide: TUI_ICONS_PATH,
    useValue: tuiIconsPathFactory('assets/taiga-ui/icons/'),
}
```

<img width="86" alt="Screenshot 2023-04-21 at 15 57 40" src="https://user-images.githubusercontent.com/22116465/233641844-ab0c0bb5-41fa-41f3-94cd-56fc3f659aae.png">

### Angular version

12.2.16

### Taiga UI version

3.25.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I think `tuiSvgOptionsProvider` is broken, because proprietary packages have other props overridden. @splincode @nsbarsukov @vladimirpotekhin maybe we should change our provider helpers to optionally inject skipself of the token and use them with fallback to defaults?
