### ISSUE TITLE
🐞 - editor "undo" button cause deletion of all text without able to restore it

### ISSUE THREAD

**Issue by fullzero87** [Tinkoff/taiga-ui#4290]
Steps to reproduce ([video](https://youtu.be/XvGY680vEvI)):
- Open editor with or without initial value (for example [this page](https://taiga-ui.dev/editor/anchors))
- Press "undo" button (text will disappear)
- Pres "redo" button (nothing happens)

Expected:
- No undo action on initial value
- Redo should work always

**Comment by fullzero87** [comment]
> please also provide a video reproduce

https://youtu.be/XvGY680vEvI

**Comment by splincode** [comment]
Possible duplicate
https://github.com/Tinkoff/taiga-ui/issues/4293
