### ISSUE TITLE
🐞 - @taiga-ui/cdk migrations crashes with JavaScript heap out of memory

### ISSUE THREAD

**Issue by DerSizeS** [Tinkoff/taiga-ui#4305]
### Playground Link

none

### Description

Hello. It took me a long time to figure out why "nx migrate --run-migrations=migrations.json" crashes with the error "JavaScript heap out of memory" and if you increase the memory, then "Maximum call stack size exceeded"
As far as I understand @taiga-ui/cdk migrations includes temporary files, such as folders like "build dist coverage bundle-analyzer" and files like "stats.json"
After deleting the temporary files from the project, the migrations worked

### Angular version

12.2.18

### Taiga UI version

2.84.0/3.25.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
fixed by https://github.com/Tinkoff/taiga-ui/pull/4257/files
