### ISSUE TITLE
📚  - Improve documentation about `tuiMarkControlAsTouchedAndValidate`

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#4321]
### Description

See:
* https://t.me/taiga_ui/7924/10680
* https://github.com/Tinkoff/taiga-ui/blob/main/projects/cdk/utils/miscellaneous/mark-control-as-touched-and-validate.ts

**Comment by waterplea** [comment]
@AdrianKokot for some reason I cannot assign you to this issue, search doesn't work :thinking: can you post a message here so you will be added to suggested users?

**Comment by AdrianKokot** [comment]
Sure 😄
