### ISSUE TITLE
🚀 - Navbar

### ISSUE THREAD

**Issue by golu7679** [Tinkoff/taiga-ui#4335]
### Description

Please add an navbar component

**Comment by waterplea** [comment]
We got several components, dedicated to navigation:
![image](https://user-images.githubusercontent.com/11832552/235346592-060c6a9f-c39b-4f07-af16-fbd5061d945e.png)

Most recent additions are [AppBar](https://taiga-ui.dev/navigation/app-bar) and [TabBar](https://taiga-ui.dev/navigation/tab-bar), we don't plan on introducing more built-in components at this point. I believe `TabBar` might be what you are looking for.
