### ISSUE TITLE
🤖 - [UIKIT-6419]: Move ng-web-apis to Tinkoff

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#4345]
### Техническое задание

1) Накрутить там полноценную монорепу по нашим стандартам на Angular 12, как Тайга.
2) Демо проект взять отсюда и деплоить его на github pages:
https://github.com/ng-web-apis/ng-web-apis.github.io
3) Добавить туда, к примеру, вот эту либу:
https://github.com/ng-web-apis/resize-observer
4) Сделать так, чтобы демка этой либы была просто лейзи роутом от главного демо проекта.
5) Сделать полный пререндер демо проекта для публикации на гитхаб пейджес со всеми роутами.

Когда это будет готово — сменим владельца на Тинькофф и переименуем в ng-web-apis. После будем постепенно заносить туда остальные либы и переводить их старые репозитории в read-only со ссылкой на эту новую монорепу. Как я говорил, надо обратить внимание на то, что нужно использовать Karma и не терять контрибьютеров. Так же надо будет обновить лицензию и email в CODE_OF_CONDUCT.md. Нужно будет запилить какой-то общий README.md и продумать как релизить либы независимо друг от друга.

### TODO Libs

- [x] common
- [x] universal
- [x] audio
- [x] canvas
- [x] geolocation
- [x] intersection observer 
- [x] midi
- [x] mutation observer
- [x] payment request
- [x] permissions
- [x] resize observer
- [x] speech
- [x] storage
- [x] workers

**Comment by waterplea** [comment]
Great! For some reason when I click to common from the main landing and then back in my browser - it navigates back 2 steps to this page.

**Comment by splincode** [comment]
@waterplea https://github.com/ng-web-apis/common/tree/main/libs

I moved all the libraries, what should I do next?

1. move repo to `Taiga Family` organization and setup independent releases there? 
2. or setup releases in this `ng-web-apis/common` repository?
