### ISSUE TITLE
🐞 - scrollbars appear in dialog when preview closes

### ISSUE THREAD

**Issue by DerSizeS** [Tinkoff/taiga-ui#4346]
### Playground Link

none

### Description

If you open `TuiPreviewDialogService` preview inside `TuiDialogService` dialog and then close `TuiPreviewDialogService` preview, then scrollbars appear in the root.

I think the problem is [here](https://github.com/Tinkoff/taiga-ui/blob/v2.x/projects/core/components/root/root.component.ts#L30)

### Angular version

2.84.0

### Taiga UI version

12.2.16

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Yes, it should be combineLatest with sum of all lengths.
