### ISSUE TITLE
🐞 - The tuiDropdownMinHeight property in the tui-hosted-dropdown component does not work.

### ISSUE THREAD

**Issue by erzenhaxhi** [Tinkoff/taiga-ui#4353]
### Playground Link

https://stackblitz.com/edit/angular-jawb27?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.less

### Description

The 'tuiDropdownMinHeight' property has no effect on the minimum height of the 'tui-hosted-dropdown' component.

### Angular version

12.2.13

### Taiga UI version

3.25.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
`tuiDropdownMinHeight` is not about minimum height of the dropdown like CSS `min-height`. It means the minimum size down to which dropdown will shrink as it approaches the edge of the screen before it jumps to the other side. Say you have a select and a dropdown of 500px and you set `[tuiDropdownMinHeight]="200"`. You scroll page up and now dropdown hits the bottom of the screen. It would start to shrink and scrollbar will appear. Once its height is below 200px it would jump up and be shown above the select at its full height of 500px again. If you just want to make sure your dropdown has at least X px in height — wrap your content with some DIV and set its `min-height` with CSS.

**Comment by erzenhaxhi** [comment]
> `tuiDropdownMinHeight` is not about minimum height of the dropdown like CSS `min-height`. It means the minimum size down to which dropdown will shrink as it approaches the edge of the screen before it jumps to the other side. Say you have a select and a dropdown of 500px and you set `[tuiDropdownMinHeight]="200"`. You scroll page up and now dropdown hits the bottom of the screen. It would start to shrink and scrollbar will appear. Once its height is below 200px it would jump up and be shown above the select at its full height of 500px again. If you just want to make sure your dropdown has at least X px in height — wrap your content with some DIV and set its `min-height` with CSS.

I wrapped the dropdown content and set min-height, but the dropdown still has its own max-height.

Example: https://stackblitz.com/edit/angular-jawb27-uxvvd6?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.less
