### ISSUE TITLE
🚀 - `Documentation` tuiHoveredChange 

### ISSUE THREAD

**Issue by evgeniy-em** [Tinkoff/taiga-ui#4411]
### Description

Add info about tuiHoveredChange to documentation. Proposed path - Tools => Directives => HoveredChange

**Comment by AKdeBerg** [comment]
Greetings! I am new to open source contribution and eager to contribute to this particular project and found this _good first issue_. However, I'm having difficulty understanding the functionality of **_tuiHoveredChange_**. If I don't understand the functionality then it's kinda hard for me to write documentation about it. 
 For your information, I have already forked the repository and successfully run the project on my local machine.

**Comment by waterplea** [comment]
> Greetings! I am new to open source contribution and eager to contribute to this particular project and found this _good first issue_. However, I'm having difficulty understanding the functionality of **_tuiHoveredChange_**. If I don't understand the functionality then it's kinda hard for me to write documentation about it. Can anybody plz tell me how do I check functionality of **_tuiHoveredChange_** ?
>  For your information, I have already forked the repository and successfully run the project on my local machine.

HoveredChange is used to emit true/false when users hovers over an element or moves cursor away from it. A simple page like this one would be a good solution to this task:
https://taiga-ui.dev/directives/present

**Comment by AKdeBerg** [comment]
> HoveredChange is used to emit true/false when users hovers over an element or moves cursor away from it. A simple page like this one would be a good solution to this task: https://taiga-ui.dev/directives/present

aah ok then... I will start working on it.. Thanks for the guide.. Much appreciated..

**Comment by AKdeBerg** [comment]
@waterplea Hi I have made a PR for this issue. What should I do next? Should I just wait for the PR to be reviewed or need to do ask reviewers to review it? This is my first time contributing to OS hence asking haha..
Also it says the branch is out of date.. What to do about it?
<img width="1031" alt="Screenshot 2023-05-14 at 11 45 07 AM" src="https://github.com/Tinkoff/taiga-ui/assets/7089345/f0a677cf-b7f7-43b0-a41c-fff1b9f74206">

**Comment by waterplea** [comment]
Thank you for your PR!
