### ISSUE TITLE
🐞 - PromptDialog: buttons don't look good on mobile devices.

### ISSUE THREAD

**Issue by LozhkinIvan** [Tinkoff/taiga-ui#4439]
### Playground Link

-

### Description

When I open PromptDialog with long buttons text, it looks like that 
![image](https://github.com/Tinkoff/taiga-ui/assets/27954036/b5cb35ec-9236-4db7-b94f-a754ab40b836)

### Angular version

11

### Taiga UI version

2

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
fixed in proprietary v2.x
