### ISSUE TITLE
[FEATURE] Automatic accessible hint

### ISSUE THREAD

**Issue by waterplea** [Tinkoff/taiga-ui#444]
# 🚀 Feature request

### Is your feature request related to a problem?

We have DescribedBy directive and tuiHintId input to link hints with focusable elements so that they are shown on keyboard focus:
https://taiga-ui.dev/directives/described-by

Would be nice, however, if that worked automatically if hint is used on a focusable element!

**Comment by alejandrocoding** [comment]
Hi @waterplea 

I am having a look at this issue, I'd like to help with a PR. However, I might be missing some context so if you can help me to better understand the possible solution would be great.

`described-by` is a directive and `tuiHint` is another independent directive. Angular can't render dynamics directives. I have read something about calling the ngOnInit of the directive manually if the input is set, never tried tbh. What do you have in mind for this?

First thought was, if `tuiHintId` is set, and not `described-by` is found, add it automatically, but don't think that way will work.

**Comment by alejandrocoding** [comment]
Any comments on this @waterplea @MarsiBarsi

**Comment by waterplea** [comment]
Yes, sorry for a slow response, I'll try to look into it this week

**Comment by waterplea** [comment]
I think this can be closed now as of 3.0 — describedBy flow is simplified.
