### ISSUE TITLE
🐞 - DataListWrapper demo broken

### ISSUE THREAD

**Issue by evantrimboli** [Tinkoff/taiga-ui#4444]
### Playground Link

https://taiga-ui.dev/components/data-list-wrapper#custom

### Description

- Go to the "custom item content" example.
- Focus the combo, type "t"
- Click "Terry Jones"
- Note that the combo display `[object Object]` as the display

### Angular version

12.x

### Taiga UI version

3.26.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Right. `tui-input` should be changed to `tui-combo-box [stringify]="stringify". Would you be willing to provide a PR?
