### ISSUE TITLE
🐞 - demo uses large icons in small buttons

### ISSUE THREAD

**Issue by constantant** [Tinkoff/taiga-ui#4495]
### Playground Link

https://stackblitz.com/edit/angular-pdt7bj?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.less&hideExplorer=0

### Description

An icon loaded from the separate server and inserted as `innerHTML` within a `tuiIconButton` becomes cropped
<img width="31" alt="image" src="https://github.com/Tinkoff/taiga-ui/assets/5537730/3d5485f1-4e47-4c5b-af19-7f83af471e40">

### Angular version

15

### Taiga UI version

3.27.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
use `tuiIconLink` instead of `tuiIconLinkLarge` for `size="xs"`

**Comment by splincode** [comment]
fair enough

**Comment by constantant** [comment]
@splincode and I see that there is `overflow: visible` for `.t-svg` but no for `.t-src svg` which seems must be the same as `svg` is 100% expected in the `innerHTML$` stream
