### ISSUE TITLE
🚀 -  onDark mode in MultiSelect should look like MultiSelect in night theme

### ISSUE THREAD

**Issue by margogeo** [Tinkoff/taiga-ui#4497]
### Description

В MultiSelect в onDark mode в поле инпута цвет текста темный на темном фоне + выпадающий список такой же, как в светлой теме, и его сложно поменять(получилось только переприсваиванием css переменных на данный момент)
Готова сама внести правки после согласования

Обсуждение в канале в Time - https://time.tinkoff.ru/tinkoff/pl/ip6mxabowjb9ucbn9fpuycrrja

**Comment by waterplea** [comment]
Кастомизацию самой выпадашки сделать не так просто. Сделаем это в рамках другой задачи: https://github.com/Tinkoff/taiga-ui/issues/4393 а тут поправим плейсхолдер.
