### ISSUE TITLE
🐞 - Input Files: file size miscalculation

### ISSUE THREAD

**Issue by Bullettime23** [Tinkoff/taiga-ui#4518]
### Playground Link

https://angular-6pkxdk.stackblitz.io

### Description

Hello!
I use Taiga UI file input in an app, and I've found that the file size in UI is probably counted in Megabits, not in Megabytes:

![image](https://github.com/Tinkoff/taiga-ui/assets/51997061/aefd7435-9688-4ece-97f0-4c6d1922ae85)
![image](https://github.com/Tinkoff/taiga-ui/assets/51997061/43460ff9-c2b0-4a4b-bff5-309b2d5c0b40)

### Angular version

15

### Taiga UI version

3.27.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Kilobyte and megabyte was changed to 1000 bytes and 1000 kilobytes accordingly for over a decade now :)
https://en.wikipedia.org/wiki/Megabyte#:~:text=By%20the%20end%20of%202009%2C%20the%20IEC%20Standard%20had%20been%20adopted%20by%20the%20IEEE%2C%20EU%2C%20ISO%20and%20NIST.

https://ru.wikipedia.org/wiki/%D0%9C%D0%B5%D0%B1%D0%B8%D0%B1%D0%B0%D0%B9%D1%82#%D0%98%D1%81%D1%82%D0%BE%D1%80%D0%B8%D1%8F%20%D0%B2%D0%BD%D0%B5%D0%B4%D1%80%D0%B5%D0%BD%D0%B8%D1%8F:~:text=388%20608%20%D0%B1%D0%B8%D1%82-,%D0%98%D1%81%D1%82%D0%BE%D1%80%D0%B8%D1%8F%20%D0%B2%D0%BD%D0%B5%D0%B4%D1%80%D0%B5%D0%BD%D0%B8%D1%8F,-%5B%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C%20%7C
