### ISSUE TITLE
🐞 - `TuiInputComponent` возможно изменять значение заблокированного инпута

### ISSUE THREAD

**Issue by DenisVinokurov** [Tinkoff/taiga-ui#4536]
### Playground Link

https://stackblitz.com/edit/angular-yweh7v?file=src%2Fapp%2Fapp.component.ts,package.json,src%2Fapp%2Fapp.component.html&hideExplorer=1

### Description

Если указать FormControl при инициализации disabled (`new FormControl({ value: 'value', disabled: true });`) и обернуть `TuiInputComponent` в label, то внешне инпут заблокирован, но при фокусе можно изменять значения.
Воспроизводится при версии angular 15.2.0+, при версии 12.2.7 в stackblitz не воспроизводится

### Angular version

15.2.0

### Taiga UI version

3.28.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Очень странно, судя по истории именно такой баг 3 года назад исправляли, заменив `[disabled]="computedDisabled"` на `[attr.disabled]="computedDisabled | null"`.
