### ISSUE TITLE
🐞 - Некорректное отображение месяцев во всплывающем календаре

### ISSUE THREAD

**Issue by a-filyakov** [Tinkoff/taiga-ui#4544]
### Playground Link

https://stackblitz.com/edit/angular-wqogvh?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts&hideExplorer=1

### Description

Сегодня 29 мая. При наведении фокуса на поле с диапазоном дат и клике мышью -
во всплывающем календаре в левой части отображается июнь 2023, в правой - также июнь 2023 

### Angular version

12

### Taiga UI version

3.28

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
If a month on the left is forcefully moved forward due to min date, the month on the right should be plus one month.
