### ISSUE TITLE
🐞 - Cannot open "More" in TuiTabsWithMore when tabs has routerLinkActive

### ISSUE THREAD

**Issue by sviat9440** [Tinkoff/taiga-ui#4557]
### Playground Link

https://stackblitz.com/edit/angular-7sk89u-sbu7wy?file=src%2Fapp%2Fapp.component.html

### Description

Adding `routerLinkActive` to `tuiItem` inside `tui-tabs-with-more` leads to unexpected consequences when exceeding `itemsLimit`.

This code works fine:
```
  <tui-tabs-with-more [itemsLimit]="2">
    <button *tuiItem routerLink="/a" tuiTab>A</button>
    <button *tuiItem routerLink="/b" tuiTab>B</button>
    <button *tuiItem routerLink="/c" tuiTab>C</button>
    <button *tuiItem routerLink="/d" tuiTab>D</button>
  </tui-tabs-with-more>
```

This code is not working correctly:
```
  <tui-tabs-with-more [itemsLimit]="2">
    <button *tuiItem routerLink="/a" routerLinkActive tuiTab>A</button>
    <button *tuiItem routerLink="/b" routerLinkActive tuiTab>B</button>
    <button *tuiItem routerLink="/c" routerLinkActive tuiTab>C</button>
    <button *tuiItem routerLink="/d" routerLinkActive tuiTab>D</button>
  </tui-tabs-with-more>
```

In my project, this leads to the fact that the "More" button simply does not open. In Stackblitz, the project doesn't even start because of the eternal cycle.

### Angular version

15.0.0

### Taiga UI version

3.29.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Looks like you have multiple tabs that get matched as active. The code snippet you have presented is not valid, you cannot have multiple active router links at the same time. Could that be an issue?

**Comment by sviat9440** [comment]
In my project i have only one active route.

**Comment by sviat9440** [comment]
Hm, You are right, this is what leads to an eternal cycle in Stackblitz. Without this, everything works in Stackblitz. Give me a couple of minutes to figure out what's wrong with the project.

**Comment by sviat9440** [comment]
OK, I think I used tui-tabs-with-more incorrectly. Instead, it would be possible to use tui-hosted-dropdown for my purposes
