### ISSUE TITLE
Не удаляется файл, приатаченный на странице

### ISSUE THREAD

**Issue by A1ternative** [Tinkoff/taiga-ui#4574]
Сценарий: 
1. На странице присутствуют элементы для загрузки документов
2. Загрузить документ
3. Удалить загруженный документ

Ожидаемый результат: файл удален
Актуальный результат: файл открывается вместо удаления

Видео для демонстрации: https://github.com/Tinkoff/taiga-ui/assets/43028709/a19e864f-efa0-4980-bc9a-2a89830501cd
Версия тайги: 3.26
ангуляр: 16.0.3
<img width="1722" alt="Screenshot 2023-06-02 at 12 34 54" src="https://github.com/Tinkoff/taiga-ui/assets/43028709/30e35575-72a2-46e6-b00e-9ef096b7d621">

**Comment by vladimirpotekhin** [comment]
the problem was the wrong version of the `@tinkoff/ng-event-plugins` package.

solution: reinstall deps
