### ISSUE TITLE
🐞 - Divider in tuiMultiSelectGroup overlaps options if used without label

### ISSUE THREAD

**Issue by DerSizeS** [Tinkoff/taiga-ui#4575]
### Playground Link

https://stackblitz.com/edit/angular-21zc5f

### Description

Divider in tuiMultiSelectGroup overlaps options if used without label
Also tuiMultiSelectGroup label moved to the right and is not aligned with the divider

### Angular version

12.2.16

### Taiga UI version

3.25.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Let's improve this example to showcase all possible combinations so screenshot testing covers it:
https://taiga-ui.dev/components/multi-select#datalist
