### ISSUE TITLE
🐞 - Alert animation is repeated for all alerts instead of new one

### ISSUE THREAD

**Issue by pwespi** [Tinkoff/taiga-ui#4610]
### Playground Link

https://taiga-ui.dev/services/alert-service

### Description

When opening a second alert, the alert animation is repeated for all alerts, instead of only the second one. Same when alerts are closed.

The behavior changed somewhere between v3.24.0 and v3.30.0. Not sure which exact version.

Reproduction: 
- open https://taiga-ui.dev/services/alert-service
- click "Show" button several times

Current behavior (taiga-ui v3.30.0):

https://github.com/Tinkoff/taiga-ui/assets/24232962/a4834bd4-1874-4a88-939e-1b9ccf31a1c7

Expected behavior (taiga-ui v3.24.0):

https://github.com/Tinkoff/taiga-ui/assets/24232962/07cdb001-1d90-4488-9618-039327f55093

### Angular version

16

### Taiga UI version

3.30.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Possible related: https://github.com/Tinkoff/taiga-ui/pull/4561/files

**Comment by splincode** [comment]
Link problem: https://github.com/Tinkoff/taiga-ui/pull/4533
