### ISSUE TITLE
🐞 - TuiError is not visible after submit with ngModel

### ISSUE THREAD

**Issue by sFeels** [Tinkoff/taiga-ui#4625]
### Playground Link

https://stackblitz.com/edit/angular-vjy5cy-orswfk?file=src%2Fapp%2Fapp.component.ts

### Description

Press submit button on form with clean and untouched required form control, TuiError is expected to be shown, but it's not

### Angular version

12.2.16

### Taiga UI version

3.29.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
This is working as expected, the commented line in your StackBlitz is **required** and, as you stated, it works in StackBlitz but not in your project. You would have to figure out what's wrong with your project, it's not an issue with Taiga UI.
