### ISSUE TITLE
🚀 - Tree - add trackBy handler for child nodes

### ISSUE THREAD

**Issue by r0ss0neri** [Tinkoff/taiga-ui#4626]
### Description
We have some operations with tree which will require complete reloading for items or partial items replace. Hence all or some items can be completely rerendered causing this effects:
- blinking for styles, icons
- losing scroll position 

Good explanation when track by is needed [here](https://github.com/Tinkoff/taiga-ui/issues/1665#issuecomment-1119555534).

### Demo

https://github.com/Tinkoff/taiga-ui/assets/24474497/4f0df9cc-9181-49a0-82f7-f11650840053

https://github.com/Tinkoff/taiga-ui/assets/24474497/3274ecd5-d1e7-4d70-b8a3-e56bcde1c431

### Suggestion
Add `trackBy` function [here](https://github.com/Tinkoff/taiga-ui/blob/ec6534833e619c99039b5e7d70c22cbae0b7d3d4/projects/kit/components/tree/components/tree/tree.template.html#L12) and expose ability to configure item property name to track by.

**Comment by waterplea** [comment]
Sounds reasonable. Would you like to contribute a PR?

**Comment by r0ss0neri** [comment]
Yes will do
