### ISSUE TITLE
🐞 - @tuiPure do not work as ECMA decorator

### ISSUE THREAD

**Issue by sviat9440** [Tinkoff/taiga-ui#4641]
### Playground Link

-

### Description

[ECMA decorators](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#decorators) have been added to typescript 5. @tuiPure is incompatible with it.

![image](https://github.com/Tinkoff/taiga-ui/assets/13107421/61ed78ac-a862-4200-b650-3d0422031c14)

It is necessary to implement ECMA Decorators support with backward compatibility with Legacy Decorators.

In my project, the decorator implementation looks like this (maybe it can help you):

```
export const pure = <A extends unknown[], R>(
  target: (...args: A) => R,
  context: ClassMethodDecoratorContext | ClassGetterDecoratorContext,
) => {
  if (context.kind === 'method' || context.kind === 'getter') {
    let previousArgs: A | undefined;
    let result: R;
    return function (this: object, ...args: A): R {
      if (previousArgs?.length === args.length && previousArgs.every((item, index) => item === args[index])) {
        return result;
      }
      previousArgs = args;
      return (result = target.apply(this, args));
    };
  }
  return undefined;
};
```

### Angular version

16.1.0

### Taiga UI version

3.30.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
@sviat9440 would you be interested in making a PR, if you already have a working code?

**Comment by sviat9440** [comment]
Okay, I'll do it tomorrow
