### ISSUE TITLE
🤖 - Unit tests for `InputDateRange` fail with CPU 100%

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#4642]
### Description

<img width="966" alt="image" src="https://github.com/Tinkoff/taiga-ui/assets/12021443/31436927-d743-4dda-a66a-2d898fcbcdfe">
<img width="720" alt="image" src="https://github.com/Tinkoff/taiga-ui/assets/12021443/54b91d9b-aa6c-4f38-8f98-f91f13885475">

**Comment by nsbarsukov** [comment]
https://github.com/Tinkoff/taiga-ui/pull/4639/commits/fb22a6da70d1eb87190c3816dbfd210a4adb3249
