### ISSUE TITLE
🐞 - fonts loading error breaks global styles

### ISSUE THREAD

**Issue by evgeniy-em** [Tinkoff/taiga-ui#4661]
### Playground Link

https://taiga-ui.tcsbank.ru/

### Description

Fonts are imported in 'index.less'.
'index.less' is added to 'styles' in 'angular.json'

If we block URL with fonts (for example https://www.cdn-tinkoff.ru/frontend-libraries/npm/taiga/1.1.0/fonts.css), <link> with style doesn't remove "media"="print", which is added by Angular

### Angular version

12

### Taiga UI version

3.11.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Closing this as default Angular behavior.
