### ISSUE TITLE
🐞 - HintPointer wrong position

### ISSUE THREAD

**Issue by hovhannes-a-k** [Tinkoff/taiga-ui#4666]
### Playground Link

https://stackblitz.com/edit/angular-a5fq3y?file=src%2Fapp%2Fapp.component.html&hideExplorer=1

### Description

<img width="1050" alt="Screenshot 2023-06-14 at 16 56 09" src="https://github.com/Tinkoff/taiga-ui/assets/107367167/dcd2ea01-c581-448f-ad69-18e9f20761f8">

when refreshing the page, if you place the cursor on the card during the refresh.

### Angular version

14.2.9

### Taiga UI version

3.31.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Could you elaborate or maybe record a video? I'm not able to reproduce it following the bug description.

**Comment by hovhannes-a-k** [comment]
Sure, here's the video

https://github.com/Tinkoff/taiga-ui/assets/107367167/bc39d95a-6e70-42c0-8719-43abbac94ea7

see the tooltip in the top left corner.

**Comment by waterplea** [comment]
Still unable to reproduce neither on Windows nor on Mac. Hint does not appear at all during reload if I do not move the cursor. And when I do - it is shown in correct spot. Are there any errors in console?

**Comment by waterplea** [comment]
Ok, it is reproducible for me with network throttling.
