### ISSUE TITLE
🚀 - Сan't customize image preview with tui-input-files without ng-deep

### ISSUE THREAD

**Issue by DmitryShatalov** [Tinkoff/taiga-ui#4715]
### Description

I need to customize the thumbnail image size in tui-input-files. Now I managed to do it only using ng-deep. I wish there was a better way. And also to make the preview of the image available, according to the design of tui-input-files, since now you need to convert the file into a url. Below is a link to stackblitz, with the current implementation. Maybe I'm missing something, but I didn't find anything in the documentation.

### Demo
https://stackblitz.com/edit/angular-k8budp?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

**Comment by waterplea** [comment]
For `size="l"` you do not need to do anything for preview to show. To customize preview area you can pass `leftContent` for both size m and l, however the size of the preview area is set inside the component per our design specs and at this time we do not plan to allow to change it. Here's an example on how you can use `leftContent` to add image preview to a size m file:
https://stackblitz.com/edit/angular-kwisdk
