### ISSUE TITLE
🐞 - Enabling `REMOVE_STYLES_ON_COMPONENT_DESTROY` causes "leave" animations to misbehave

### ISSUE THREAD

**Issue by hakimio** [Tinkoff/taiga-ui#4736]
### Description

If you enable [REMOVE_STYLES_ON_COMPONENT_DESTROY](https://angular.io/api/platform-browser/REMOVE_STYLES_ON_COMPONENT_DESTROY) in Angular 16, all the "Taiga UI" component "leave" animations start to misbehave. The setting is disabled by default in Angular 16, but will be enabled in Angular 17 according to [the docs](https://angular.io/api/platform-browser/REMOVE_STYLES_ON_COMPONENT_DESTROY#description:~:text=This%20will%20be%20changed%20in%20the%20next%20major%20version.).

_Sidenote: Angular Material animations seem to be unaffected by this setting._

### Angular version

16.1.1

### Taiga UI version

3.32.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
it didn't exist in angular 12 yet

<img width="1296" alt="image" src="https://github.com/Tinkoff/taiga-ui/assets/12021443/766bccc5-85c0-4bb3-97e0-43868cb61620">

**Comment by hakimio** [comment]
Why does it matter?

**Comment by splincode** [comment]
yes I agree, just wanted to pin my message

**Comment by waterplea** [comment]
@hakimio can you please name a component that exhibits this, I'll try to isolate it on Stackblitz. I don't think we do many complicated stuff with leave animations, maybe that would boil down to a bug in Angular.

**Comment by hakimio** [comment]
hint, dropdown, notification toasts (`alertService.open()`), etc. 
All of them have buggy leave animations when `REMOVE_STYLES_ON_COMPONENT_DESTROY` is enabled.

**Comment by waterplea** [comment]
Closing this as an Angular bug:
https://github.com/angular/angular/issues/50791
