### ISSUE TITLE
🐞 - TUI_ANIMATION_OPTIONS not working on selects

### ISSUE THREAD

**Issue by juanfran** [Tinkoff/taiga-ui#4748]
### Playground Link

https://stackblitz.com/edit/angular-jzgrci?file=src%2Fapp%2Fapp.component.ts

### Description

I can't customize the animation duration with `TUI_ANIMATION_OPTIONS` (see stackblitz).

```ts
    providers: [
        {
            provide: TUI_ANIMATION_OPTIONS,
            useFactory: () => {
                return {
                    params: {
                        duration: 0,
                    },
                };
            },
        },
    ],
```

The issue was introduced in commit b50bd1e48a105effd0537e0593e957226182f933.

I suspect the problem was caused because 'value' is missing in the animation property.

This commit solves the issue for me, but I'm using deprecated code: https://github.com/juanfran/taiga-ui/commit/867ac0843868434aee5e037f1669e18689c4ddd8.

### Angular version

16.0.0

### Taiga UI version

3.32.0

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Hi @juanfran. You can just provide anything as `value` as well:
```ts
provide: TUI_ANIMATION_OPTIONS,
useValue: {
  value: '',
  params: {
    duration: 0,
  },
},
```
Keep in mind `TUI_ANIMATION_OPTION` is a utility token and you only need to work with it if you are overriding animations for a particular section of you app. If you want to disable animations completely you can provide `TUI_ANIMATIONS_SPEED` with 0 at the top level injector.
