### ISSUE TITLE
🐞 - `TuiInputCardGrouped` with `TuiAutofocusDirective` doesn't set prefilled cards

### ISSUE THREAD

**Issue by viktorzdanovich** [Tinkoff/taiga-ui#4752]
### Playground Link

https://taiga-ui.dev/components/dialog#pay

### Description

Along with the playground link the issues can be reproduced with `tuiAutofocus` directive set on `inputCardGrouped` in a dialog (without asynchronous loads in the dialog)

Steps to reproduce (tested in Safari on iOS 16.5):
1) [Save credit card information in Safari settings](https://support.apple.com/en-gb/guide/iphone/iphccfb450b7/ios)
2) Open playground link
3) Hit "Pay"
4) Hit "New card"
5) Hit saved card on the displayed keyboard

Expected result: card information is filled in the input
Got results: the input is still empty

<details>
  <summary>Demo</summary>

https://github.com/Tinkoff/taiga-ui/assets/19538300/96d45caf-3578-4460-9a01-53961df84b36

</details>

### Angular version

>= 12

### Taiga UI version

>= 3.24.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [X] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
Seems like there's no way to properly make Safari suggest autofill for autofocused field inside dialog in this case.
