### ISSUE TITLE
🐞 - hint not showing on barchart

### ISSUE THREAD

**Issue by cobaltutby** [Tinkoff/taiga-ui#4753]
### Playground Link

https://stackblitz.com/edit/angular-vjy5cy-fa6qnq?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.less

### Description

hint not showing on barchart if value is renewed

### Angular version

16

### Taiga UI version

3

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
That is expected. Never use getters for arrays, it creates a new instance on each change detection cycle thus removing and creating the elements again and you end up never hovering the same DOM element, therefore you don't get the hover effect and hint won't show up. Instead if you want to transform your data - use pure pipe. You can use `tuiMapper` and pass a transformation function for universal solution:
https://taiga-ui.dev/pipes/mapper
