### ISSUE TITLE
🚀 - Allow more customization of colour on toggle component

### ISSUE THREAD

**Issue by evantrimboli** [Tinkoff/taiga-ui#4765]
### Description

Similar to radio/checkbox, it would be nice to have the ability to customize the colours in an easier fashion.

**Comment by waterplea** [comment]
You mean adding `appearance` to `TUI_TOGGLE_OPTIONS` like it is done for checkbox/radio? Would you be willing to contribute a PR?

**Comment by evantrimboli** [comment]
Yeah, something along those lines. I wanted to have it appear with the accent colour. Happy to make a PR, however I wasn't sure how this would work best with `singleColor` as well.

**Comment by waterplea** [comment]
I think you can just keep current behavior with `singleColor` — use `checked` appearance for both states.
