### ISSUE TITLE
🐞 - EmptyContent in TuiDatalist gets wrong size

### ISSUE THREAD

**Issue by Formaceft** [Tinkoff/taiga-ui#4803]
### Playground Link

https://taiga-ui.dev/components/combo-box/API?tuiTextfieldSize=s

### Description

When search queries in datalist controls return empty value, it always has the same size (doesn't change depends on datalist size by itself)

### Angular version

12.2.17

### Taiga UI version

2.34.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
@AdrianKokot for some reason I cannot assign you to this issue, search doesn't work 🤔 can you post a message here so you will be added to suggested users?

**Comment by AdrianKokot** [comment]
Sure 😄
