### ISSUE TITLE
🚀 - tui-horisontal-stuck-scrollbar component

### ISSUE THREAD

**Issue by sviat9440** [Tinkoff/taiga-ui#4838]
### Description

Need to create a component (analogous to <tui-scrollbar>) but containing only a horizontal scrollbar that sticks to the lower border of the viewport.

In large tables, if there is a horizontal scrollbar, there is a problem with the availability of this scrollbar, because it is far below, and in order to scroll the table horizontally, you first need to go down to the scrollbar, scroll, and return up to the desired row. This is very inconvenient.

@waterplea @splincode If you agree, you can immediately assign it to me and I will create a pull request.

**Comment by waterplea** [comment]
This can be achieved with current components, see this example:
https://stackblitz.com/edit/taiga-horizontal-sticky-scroll
