### ISSUE TITLE
🚀 - События ошибки загрузки изображения tui-avatar

### ISSUE THREAD

**Issue by blackSunRiseE** [Tinkoff/taiga-ui#4845]
### Description

Для обработки ошибок загрузки изображения в tui-avatar используем fallback, но нам надо также ловить событие ошибки загурзуки, для изменения отображения

**Comment by waterplea** [comment]
Native `error` event on `img` tag does not bubble, but you can listen to it in capture phase which is possible with Taiga UI using a modifier:
```html
<tui-avatar (error.capture)="onError()" ...>
```
