### ISSUE TITLE
🐞 - поведение LineClamp 

### ISSUE THREAD

**Issue by Ultraviolence322** [Tinkoff/taiga-ui#4855]
### Playground Link

https://taiga-ui.tcsbank.ru/components/line-clamp/API?content=1241351151515&sandboxWidth=116

### Description

При наведении срабатывает ховер даже тогда, когда контент полностью виден
![image](https://github.com/Tinkoff/taiga-ui/assets/53703949/29d2e395-393e-465f-9094-037dbd0fdef6)
![image](https://github.com/Tinkoff/taiga-ui/assets/53703949/5067ab2f-9a58-42ef-b722-fc3734e71e71)

### Angular version

13.3.11

### Taiga UI version

3.3.0

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by splincode** [comment]
Interesting

https://taiga-ui.dev/components/line-clamp/API?content=1241351151515&sandboxWidth=85

<img width="354" alt="image" src="https://github.com/Tinkoff/taiga-ui/assets/12021443/654488db-f6e2-487d-aa3e-e8d6f5e5f22a">

**Comment by waterplea** [comment]
@Ultraviolence322 cannot reproduce it in Chrome on Windows, Chrome and Safari on Mac. Can you share your environment?

**Comment by Ultraviolence322** [comment]
https://taiga-ui.tcsbank.ru/components/line-clamp/API?content=123321445566&linesLimit=1&sandboxWidth=91 если тут в поле content добавить один символ и удалить его, потом навести, то появится ховер, в таком кейсе не думаю, что это баг..
