### ISSUE TITLE
🤖 - peerDeps

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#4899]
### Description

<img width="1159" alt="image" src="https://github.com/Tinkoff/taiga-ui/assets/12021443/4fcdd910-3f52-44a9-b8fa-10a48c0b8c7e">

**Comment by hakimio** [comment]
On a slightly related note:

![image](https://github.com/Tinkoff/taiga-ui/assets/768105/27c55252-5923-426b-b91c-37cc764db02e)

Is there a good reason for `ng-morph` to have those two dependencies?
