### ISSUE TITLE
🚀 - Want custom format for `Input Date Range` for `TUI_DATE_FORMAT`

### ISSUE THREAD

**Issue by hey24sheep** [Tinkoff/taiga-ui#4907]
### Description

Hi, thank you for this wonderful UI kit.

I am using the [Input Date Range](https://taiga-ui.dev/components/input-date-range) but my problem is the label is in `ddmmyyyy` format. My requirement is to make the date look like this `May 12, 2023` to `Jul 12, 2023`. 

If there is already a way to do this, then I was unable to find it. Could you point me in the right direction? Or can you tell me if a workaround exists.

~My issue request is - Can you make a range selection validator? Like my requirement is, when a user is selecting a range, I want to limit that range. A person can only select X amount of dates, example - they can select 365 days in a single range selection, or they can select 30 days max in a single range selection.~

- I found the solution for the second one, min and max length

I am not aware if any of this exists, if there exists something please let me know. Really appreciate it, thank you.

**Comment by hey24sheep** [comment]
Hi, sorry I am bumping but any update regarding this?

**Comment by nsbarsukov** [comment]
@hey24sheep 

> My requirement is to make the date look like this May 12, 2023 to Jul 12, 2023.

Unfortunately, this format is not UX-friendly for typing it via keyboard.
You should take into consideration that user can interact with `InputDateRange` not only via calendar but also via keyboard.

**Comment by hey24sheep** [comment]
@nsbarsukov Hi, I understand what you are saying. But, what I am asking is a little different.

- NOTE : The only thing which will change is the format during rendering. On focus/input, it will still act the same as it is right now with "dd/mm/yyyy" or "mm/dd/yyyy" or other format.
- I want a custom format for view which will be like "May 12, 2023 to Jul 12, 2023" OR any other formatting of the "User's" liking
- Second, the input format which can be in format "dd/mm/yyyy" or as per "User's" liking.
    - Here it should show the input format same as it shows right now. 
- A flag to disable keyboard input via keyboard `InputDateRange`

**Comment by waterplea** [comment]
There will be no flag to disable keyboard input, as for the template for unfocus state, that would be added under this issue, although I cannot give any time estimates as it is not a priority at the moment:
https://github.com/Tinkoff/taiga-ui/issues/4595
