### ISSUE TITLE
🐞 - `BadgedContent` badge misaligned inside flex parent

### ISSUE THREAD

**Issue by vladimirpotekhin** [Tinkoff/taiga-ui#4909]
### Playground Link

https://taiga-ui.dev/components/badged-content/API?contentBottom=5&colorBottom=&sandboxWidth=222&contentTop=5

### Description

<img width="395" alt="Снимок экрана 2023-07-12 в 17 25 12" src="https://github.com/Tinkoff/taiga-ui/assets/46284632/6af25ea1-acd1-441d-a47e-2e84208f1e7f">
<img width="322" alt="Снимок экрана 2023-07-12 в 17 25 24" src="https://github.com/Tinkoff/taiga-ui/assets/46284632/a699abbc-0ea9-4a15-a292-56cc24a07a07">

probably we need to add `height: min-content` to badgedContent

### Angular version

9>

### Taiga UI version

3>

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I think this is expected, we cannot know how to act inside such containers. I don't think it's possible to build into a badged container. Where to align it, top or bottom? Instead we need to fix the stop where it causes issues outside of developers control.
