### ISSUE TITLE
[BUG] Dialog from template or component with autofocus directive in it causes a dialog jump

### ISSUE THREAD

**Issue by MladenSijan** [Tinkoff/taiga-ui#496]
# 🐞 Bug report

### Description
Opening dialog from template or component with autofocus directive in it causes a dialog jump (animation bug).
This happens only in mobile browsers.

### Reproduction

https://stackblitz.com/edit/taiga-starter-scvmsa?file=src%2Fapp%2Fapp.component.html

### Expected behavior
The animation should remain as it was initially.

### Versions

-   Browser [Chrome Mobile, Mozilla Mobile]
-   Angular [11]
-   Package [e.g. @taiga-ui/cdk@2.10.1]

**Comment by waterplea** [comment]
Looks like we need to watch for animation end not only in iOS but everywhere.

**Comment by waterplea** [comment]
Let's bump priority here because we need it fixed. Looks like we need to revisit autofocus directive and refactor it, it's getting pretty messy.
