### ISSUE TITLE
🐞 - [TuiContextDropdown]: Browser native context menu is opened when using standalone components

### ISSUE THREAD

**Issue by Zkaron** [Tinkoff/taiga-ui#5023]
### Playground Link

https://stackblitz.com/edit/stackblitz-starters-xvvb6z?file=src%2Fmain.ts

### Description

While migrating a project to standalone components I noticed that the ContextDropdown directive stopped working. Right clicking on the directive's host only displays the browser native context menu.

I don't think is related to angular nor taiga-ui version because when using the module structure it works properly.

No error messages are displayed.

### Angular version

16.1.0

### Taiga UI version

3.39.1

### Which browsers have you used?

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [X] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
You already have `provideAnimations()` so you do not need to import providers from `BrowserAnimationsModule`, for some reason it breaks adding event plugins. Removing that line fixes the problem on that StackBlitz.
