### ISSUE TITLE
🚀 - Emit column names for server-sorting `Table`

### ISSUE THREAD

**Issue by uberpwner** [Tinkoff/taiga-ui#528]
# 🚀 Feature request

### Is your feature request related to a problem?

Existing sorting comparators are handy, when working with all rows loaded in memory. However, they are not very useful when working with server side sorting. You have to write extra code to map comparators to column names.

### Describe the solution you'd like

It would be more convenient to have some directive made especially for server-side sorting, that would emit column name instead of comparator function.

### Describe alternatives you've considered

An alternative is to create your own function that would convert comparator to column name like it's done in the docs: https://taiga-ui.dev/components/table#server

**Comment by waterplea** [comment]
I believe we can solve this by a directive to encapsulate borderplate of mapping sorters to column names.
