### ISSUE TITLE
[BUG] Rem units issue using 14px font size

### ISSUE THREAD

**Issue by makkaronis4e** [Tinkoff/taiga-ui#579]
# 🐞 Bug report

### Description

Some taiga elements look bad with 14px rem-base.

![image](https://user-images.githubusercontent.com/33792090/126786899-6043bccb-6efd-4345-ab55-5799f0e05b07.png)
![image](https://user-images.githubusercontent.com/33792090/126786932-ffe92e2d-1483-44c3-b05b-d3ea381e2bac.png)

### Reproduction

Set html font size to 14px

### Versions

-   Browser chrome
-   Angular 11
-   Package latest

**Comment by waterplea** [comment]
@makkaronis4e I believe the mentioned issues were resolved, if you still have troubles with different REM sizes feel free to reopen or file a separate issue.
