### ISSUE TITLE
[FEATURE] Ability to set classes on the sidebar

### ISSUE THREAD

**Issue by EricPoul** [Tinkoff/taiga-ui#581]
# 🚀 Feature request

### Is your feature request related to a problem?

 There is no way to add classes to the sidebar thus specific sidebar or its background can't be styled as I'd like to

### Describe the solution you'd like

 I'd like to style directly the sidebar not the inner content e.g. 
`<div *tuiSidebar="open; class: 'custom-class-1 custom-class-2'"></div>`

**Comment by alex-jss** [comment]
@MarsiBarsi , @waterplea I support, the same

**Comment by waterplea** [comment]
This is a duplicate of https://github.com/TinkoffCreditSystems/taiga-ui/issues/553
