### ISSUE TITLE
[BUG] axes bar Tooltip shifts to the side if i change font-size html

### ISSUE THREAD

**Issue by AnteaterKit** [Tinkoff/taiga-ui#584]
# 🐞 Bug report

### Description

axes bar Tooltip shifts to the side if i change font-size html

### Reproduction

1. open https://taiga-ui.dev/components/axes
2. open devtools
3. change html font-size 10px
4. put mouse on the bar

<img width="639" alt="Screenshot 2021-07-27 at 20 36 17" src="https://user-images.githubusercontent.com/5115677/127202863-a0c3550a-e5de-42fb-b67f-2bac6431bd24.png">

If default html font size 16px, it's ok
<img width="572" alt="Screenshot 2021-07-27 at 20 37 48" src="https://user-images.githubusercontent.com/5115677/127203057-cb472319-68d3-4ca3-b195-25aa06685f2e.png">

for one array item look font size 10px :
<img width="414" alt="Screenshot 2021-07-27 at 20 50 30" src="https://user-images.githubusercontent.com/5115677/127203256-fc8f318d-0852-4e8a-a807-3c7ae85795a4.png">

**Comment by AnteaterKit** [comment]
Hello @waterplea, i think it depends of  ARROWHEAD_OFFSET.
The default font-size is 16px, it's ok work with 
const ARROW_SIZE = 8;
const ARROW_OFFSET = 16;

But I got the project where responsive font-size. 
Do you think to create dynamic calc like this for the TuiHintBoxComponent
const fontOffsetPx = document.....fontSize;
        const fontOffset = fontOffsetPx ? +document.documentElement.style.fontSize.replace('px', '') : 16;
        const realOffset = 21 * fontOffset / 16;
        const verticalLeft =  hostRect.left -
              tooltipRect.width +
              hostRect.width / 2 +
              realOffset -
              portalRect.left;
              
  or may by allow make @Input ARROW_OFFSET / ARROW_SIZE for customise

**Comment by waterplea** [comment]
I think the most reasonable fix would be to change `::before` positioning of `tui-hint-box` (the arrow) back to pixels. Shouldn't matter that much visually but it would allow us to keep the same math since positioning is done with `ClientRect` which is in pixels.

**Comment by waterplea** [comment]
@AnteaterKit would you like to contribute?

**Comment by AnteaterKit** [comment]
I'm on vacation now. After rest, i'll return to this issue

**Comment by waterplea** [comment]
@AnteaterKit are you up for a PR? :)

**Comment by waterplea** [comment]
Fixed in 3.0
