### ISSUE TITLE
[FEATURE] Need more info on how to change the taiga ui language

### ISSUE THREAD

**Issue by chetanDhanvij** [Tinkoff/taiga-ui#604]
# 🚀 Feature request

I would like more clear documentation on how to change taiga ui language on the fly. The current readme file at https://github.com/TinkoffCreditSystems/taiga-ui/tree/main/projects/i18n just mention 1 line: 
You can also switch languages on the fly. Use useFactory or useClass with a service to make a stream of dictionaries.

Can it be supplemented with example code please.

**Comment by artemv01** [comment]
https://github.com/TinkoffCreditSystems/taiga-ui/pull/846

**Comment by waterplea** [comment]
It was recently resolved and added to the docs:
https://taiga-ui.dev/i18n/Dynamic_loader
