### ISSUE TITLE
[FEATURE] Make an example for tui-tags with tag removal

### ISSUE THREAD

**Issue by nikitadubinsk** [Tinkoff/taiga-ui#614]
It is not completely clear how to implement tag removal In the current [documentation] (https://taiga-ui.dev/components/tag) only information on customization is provided

**Comment by haroon786** [comment]
HI
can someone please elaborate what exactly we need to implement I am new to the Taiga-UI, I am interested to contribute

**Comment by haroon786** [comment]
![image](https://user-images.githubusercontent.com/20164301/147774895-80e537c3-af9b-4903-91d5-388723026a40.png)

**Comment by splincode** [comment]
I think so)
