### ISSUE TITLE
[BUG] `InputDateRange` displayed value disappears after form value change

### ISSUE THREAD

**Issue by biased-badger** [Tinkoff/taiga-ui#639]
# 🐞 Bug report

### Description

I noticed that after programmatically changing `InputDateRange` control value its display value disappears. It happens when you call reset, patchValue or setValue.

### Reproduction

In demo just press reset button:
https://stackblitz.com/edit/taiga-date-range-reset?file=src/app/app.component.ts

### Expected behavior

After changing control value, display value should be updated accordingly.

### Versions

-   OS: Win 10
-   Browser Chrome 92.0.4515.159
-   Angular 12.1.4
-   Package @taiga-ui/kit@2.13.1

**Comment by uberpwner** [comment]
It looks like problems with ngZone, because if I wrap `this.form.reset(value)` into setTimeout - everything works fine.

**Comment by nsbarsukov** [comment]
Hi, @uberpwner !
You are using
```
<button type="reset">
```
it triggers [native reset event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement/reset_event).
This native event resets range calendar value to default native value after you explicitly change value by `this.form.reset` .

See your modified sandbox (take attention to console.logs' order):
https://stackblitz.com/edit/reset-event-native?file=src/app/app.component.ts

So, if you want replace native reset event with your custom one => try `event.preventDefault()`

**Comment by uberpwner** [comment]
@nsbarsukov You are right, thank you!
That's my final solution: `(reset.prevent)="onReset()"`.
