### ISSUE TITLE
[BUG] Angular 12 build failed (production)

### ISSUE THREAD

**Issue by sunriselink** [Tinkoff/taiga-ui#641]
# 🐞 Bug report

### Description

After setup taiga-ui, production build failed. Development configuration works without errors.

```
√ Browser application bundle generation complete.
√ Copying assets complete.
× Index html generation failed.
undefined:1:111: property missing ':'
```

### Reproduction

```
ng new test-app --defaults
cd test-app

# All prompts selected NO (except "Would you like to proceed")
# Without additional packages
ng add taiga-ui

ng build --configuration production
```

### Expected behavior

`√ Index html generation complete.`

### Versions

-   OS win32 x64
-   Browser chrome
-   Angular 12.2.2
-   Node.js 12.22.3
-   Package taiga-ui@2.14.0

### Additional context
After comment `@import 'theme/fonts.css';` line in `node_modules/@taiga-ui/core/styles/taiga-ui-theme.less` build fixed.

**Comment by waterplea** [comment]
Hey there! It's an Angular issue, you can follow it here:
https://github.com/angular/angular-cli/issues/20760
