### ISSUE TITLE
[BUG] `InputNumber` and extremely large numbers

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#651]
# 🐞 Bug report

### Reproduction
1. Go to [InputNumber page](https://taiga-ui.dev/components/input-number/API).
2. Try type (using keyboard) many digits – you cant type more than 14 digits (for example,`1e13` is possible but `1e14` not).
3. Try paste (ctrl + v) a large number  - you can paste number with more than 14 digits, 18 digits is new max (for example, you can paste `1e17`).

Investigate this difference (between typing and pasting) and make the same behavior for the both cases.

### Versions
@taiga-ui/kit@2.14.0

**Comment by waterplea** [comment]
It would be great to support `BigInt` or find some way to support bigger numbers. It would be helpful for cryptocurrency UI.

**Comment by Goodzonchik** [comment]
@waterplea  I think that `BigInt` its not good choose, because will be new problem big float number.

**Comment by waterplea** [comment]
I believe big float numbers are typically handled by `BigInt` plus exponent. Anyway, just wanted to mention it because it needs further research and huge numbers input is something we need to eventually support.

**Comment by waterplea** [comment]
@nsbarsukov let's fix the discrepancy between typing and pasting and increase limit by one digit to be able to work with biggest integer number from JS. And for `BigInt` we can create a separate task.
