### ISSUE TITLE
Tooltip, hint, and manualHint are not working

### ISSUE THREAD

**Issue by NohaAmin** [Tinkoff/taiga-ui#672]
# 🐞 Bug report

### Reproduction

https://stackblitz.com/edit/taiga-starter?file=src%2Fapp%2Fapp.component.html

### Versions

-   OS: windows 10
-   Browser: Firefox
-   Angular: 12
-   Package: latest package

### Additional context

when i am trying to use "tooltip" , or "hint", or "manual hint", the drop-down body which should show the content of the tooltip is empty, so no data is shown, although I am using the exact code and steps you mentioned in your documentation

the example that I am using is found in the link below:
https://taiga-ui.dev/directives/manual-hint

and below is attached how it appears in browser:
![manual-hint-screenshot](https://user-images.githubusercontent.com/47464476/132075748-c5952e9c-4b4d-406c-9371-77099ec00808.png)

what could be the problem?

**Comment by waterplea** [comment]
Please provide a reproduction. Seem to work fine for me:
https://stackblitz.com/edit/taiga-starter-swg79r?file=src%2Fapp%2Fapp.component.html

Perhaps you forgot some module?

**Comment by waterplea** [comment]
I got it, you are using bootstrap that spoils generic classes, such as `.tooltip`. We need to prefix all our internal classes because of that, unfortunately. You can follow this issue https://github.com/TinkoffCreditSystems/taiga-ui/issues/405
