### ISSUE TITLE
🚀 - Improve "Open on StackBlitz" tech

### ISSUE THREAD

**Issue by waterplea** [Tinkoff/taiga-ui#673]
# 🚀 Feature request

### Is your feature request related to a problem?

Currently we have a very basic feature of opening examples on StackBlitz. It causes multiple issues:
- [x] https://github.com/TinkoffCreditSystems/taiga-ui/issues/166
- [x] https://github.com/TinkoffCreditSystems/taiga-ui/issues/383
- [x] https://github.com/TinkoffCreditSystems/taiga-ui/issues/393

We need to improve it to:
 - [ ] Show the modules that are actually required in the example
 - [x] <s>Be flexible enough for wide area of special cases, like dialog components</s>
 - [x] Fix icons
 - [x] Fix flags images in [InputPhoneInternational](https://taiga-ui.dev/components/input-phone-international)

### Bugs
- [x] https://github.com/Tinkoff/taiga-ui/issues/1890

**Comment by nsbarsukov** [comment]
- [ ] Show the modules that are actually required in the example
- [X] Be flexible enough for wide area of special cases, like dialog components

**Comment by rvalitov** [comment]
Missing dependencies:
![image](https://user-images.githubusercontent.com/16267156/140662948-a613d0a9-fb74-49f9-bd76-5d475f89d34e.png)

**Comment by waterplea** [comment]
Could be related to Angular 13 release? :)

**Comment by rvalitov** [comment]
The problem is that I have a few bugs to report, but I can't copy and run any of the Taiga Stackblitz examples for the last couple of weeks.

And yes, it's Angular 13. But if your examples do not work with Angular 13, why did you set it in your Stackblitz at Taiga dev pages?:) 
Perhaps it would be a good idea to stay with Angular 12 at Stackblitz, so at least your examples would work?

**Comment by waterplea** [comment]
I wonder what makes them not work with Angular 13. I know a couple of projects with Taiga UI that updated to 13 and had no troubles with the library. I guess it's something with StackBlitz. We locked it on 12.x.x for the time being so you can try checking on taiga-ui.dev/next

**Comment by nsbarsukov** [comment]
stackblitz' developers know about angular 13 problem
https://github.com/stackblitz/core/issues/1657

<hr>
Also, something wrong with latest version of angular 12.

It worked few days ago :(
I guess we should we should wait for some time.

**Comment by markwhitfeld** [comment]
@waterplea the issues we are experiencing are with the fact that Angular 13 now has `*.mjs` files and no commonJs files in the package. They also dropped the `main` field from the `package.json` and make heavy use of the relatively new `exports` field.

**Comment by rvalitov** [comment]
> Also, something wrong with latest version of angular 12.
> It worked few days ago :( I guess we should wait for some time.

Indeed, I can't run none of Angular 13 nor 12 examples in Stackblitz anymore. Only old saved Stackblitz projects work, but if I try to fork and modify them - they have missing dependency errors that can't be resolved.

**Comment by markwhitfeld** [comment]
FYI, StackBlitz now supports Angular 13:
> Great news! Support for Angular 13 has finally rolled out.
...
For the next day or two (until 12 December 2021), there is a possibility of an initial slow down in starting up the dev server or running NGCC (or potentially even timeouts) as the packages repopulate into the cache as they are used, but it should come right after a refresh or two if you do have any issues. Anything else should be reported as a new issue.

Related StackBlitz issue comment: https://github.com/stackblitz/core/issues/1657#issuecomment-989779722

**Comment by splincode** [comment]
https://github.com/Tinkoff/taiga-ui/issues/1890

**Comment by splincode** [comment]
https://github.com/Tinkoff/taiga-ui/issues/1945

**Comment by splincode** [comment]
https://github.com/Tinkoff/taiga-ui/issues/3382
