### ISSUE TITLE
🚀 - Allow LineClamp hint to expand to the right

### ISSUE THREAD

**Issue by robertkokoev** [Tinkoff/taiga-ui#699]
Allow `LineClamp` hint to expand to the right for one line by using `minWidth` instead of `width` and setting width to `min-content` and setting `white-space: nowrap` on hint content

**Comment by waterplea** [comment]
As discussed, this seems to be possible but it is not supported by Safari 10 which is the lowest version Taiga UI supports. So I'll keep this issue open until we move the bar up and then we can try to work it out.

**Comment by waterplea** [comment]
Fixed in 3.0
