### ISSUE TITLE
🚀 - Allow change text color of the Avatar Component

### ISSUE THREAD

**Issue by rvalitov** [Tinkoff/taiga-ui#734]
# 🚀 Feature request

### Is your feature request related to a problem?
The problem is that when the [avatar component](https://taiga-ui.dev/components/avatar) is used to display text string, the text is always rendered with standard color. There's an attribute to change the background color, but no attribute to change the text color. I failed to change the text color using CSS.

### Describe the solution you'd like
Add new attribute [textColor] to specify the color of text.

### Describe alternatives you've considered
Tried to achieve with CSS:
```html
<tui-root>

<tui-avatar
    class="avatar"
    text="yuliya tsareva"
></tui-avatar>

</tui-root>
```

```less
.avatar {
  color: white !important;
}
```

### Additional context
Test here https://stackblitz.com/edit/angular-wfbeya?file=src/app/app.component.html

**Comment by splincode** [comment]
https://stackblitz.com/edit/wzyemn--run (( 

![image](https://user-images.githubusercontent.com/12021443/134214820-59a48b90-6621-4367-a5ca-847d2152d9fc.png)

**Comment by waterplea** [comment]
We should probably reimagine this component so it can be configured by just setting CSS `color` and `background`. Right now `color` controls background (in your stackblitz you forgot to link the style file to component 😉 ). In the meantime you can override CSS var `--tui-text-01` on your `.avatar` class.
