### ISSUE TITLE
[BUG] Disabled InputCopy looses copy button

### ISSUE THREAD

**Issue by rvalitov** [Tinkoff/taiga-ui#752]
# 🐞 Bug report

### Description
When InputCopy button is in disabled state, then the copy button disappears:
![image](https://user-images.githubusercontent.com/16267156/134406986-74b033f7-e636-4e7a-8f54-65e2a341ac0d.png)

### Reproduction
Use the API sandbox https://taiga-ui.dev/components/input-copy/API?tuiMode=null&=true

### Expected behavior
The copy button is used to copy the contents from the input. It's very useful in read only mode: easily putting the form into disabled mode should preserve the copy functionality. 

### Versions

-   @taiga-ui/cdk@2.17.0

### Additional context
N/A

**Comment by waterplea** [comment]
That is by design. You are looking for `readOnly`. Disabled fields are completely non-interactive.
