### ISSUE TITLE
🐞 - EventManagerModule must come after BrowserModule in imports when using lazy loaded modules

### ISSUE THREAD

**Issue by VictorienTardif** [Tinkoff/taiga-ui#939]
### Which @taiga-ui/* package(s) are the source of the bug?

Don't known / other

### Description

After setting up server-side rendering (SSR) with Angular Universal, I get the following error in console:  
`EventManagerModule must come after BrowserModule in imports`

I do not import `EventManagerModule` directly, only `@taiga-ui` modules, and I do import them after `BrowserModule` so I'm a bit confused. 

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
@VictorienTardif your issue is that you moved `TuiRootModule` to some `CoreModule` and reused it in a lazy module. `TuiRootModule` must be used only once in the main module to set up app providers. I will update messaging in the warning to reflect that.

**Comment by VictorienTardif** [comment]
🤦 that was obvious sorry

**Comment by waterplea** [comment]
No worries, it helped me figure out the root cause that other people also had and improve the messaging, so thank you for the reproduction!
