### ISSUE TITLE
Clipboard Paste does not work on mobiles

### ISSUE THREAD

**Issue by rvalitov** [Tinkoff/taiga-ui#951]
Clipboard paste does not work on mobiles with all input based components (InputPhone, InputPhoneInternational, Input, etc.)
Tested with Android, iPhone and iPad. Paste only works on desktop PC.
To reproduce try it on samples from the docs.
![image](https://user-images.githubusercontent.com/16267156/139409766-1e0592d6-7315-48da-a526-7915b0597379.png)

**Comment by waterplea** [comment]
It works fine on my Android phone 🤔

**Comment by waterplea** [comment]
https://user-images.githubusercontent.com/11832552/139485950-ffd79633-8e54-4d97-b918-c7e8279846cb.mp4

**Comment by nsbarsukov** [comment]
It works fine on my iphone.

Iphone 7.
Ios 14.8.
Safari

https://user-images.githubusercontent.com/35179038/139634071-78a026ef-0bfd-4266-a42c-8cd31ac53629.MP4

**Comment by nsbarsukov** [comment]
@rvalitov could you please specify OS version and model of device ?

**Comment by rvalitov** [comment]
It seems that was some strange bug. I should have made a video of it. Currently I can't reproduce it. Please, don't close this issue and give me some more time for testing.

**Comment by rvalitov** [comment]
Still can't catch this issue and when it happens. Users still face it sometimes. I continue testing, and will report here when done.

**Comment by waterplea** [comment]
@rvalitov could it be that you are trying to paste a number with unrecognized country code? @vladimirpotekhin can we do something to handle this case better?

**Comment by rvalitov** [comment]
Thank you, I know how this input works. Unfortunately that's not the case. When I faced this problem, the paste did not work on all types of input elements with any text. Currently I can't reproduce it, perhaps it was some strange bug in one of the previous versions of Taiga.

**Comment by waterplea** [comment]
So should we close this issue then?

**Comment by rvalitov** [comment]
Ok, I will reopen if it will happen again.
