### ISSUE TITLE
🚀 - `TUI_DATE_FORMAT` add full support of all `TuiDateMode` ('DMY' | 'MDY' | 'YMD')

### ISSUE THREAD

**Issue by nsbarsukov** [Tinkoff/taiga-ui#954]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

kit

### Description

We have token [TUI_DATE_FORMAT](https://github.com/TinkoffCreditSystems/taiga-ui/blob/main/projects/cdk/date-time/date-format.ts).

It fully supports only `DMY` (dd.mm.yyyy).
We should add support of `MDY` (mm.dd.yyyy) and `YMD`(yyyy.mm.dd).

`InputDate`, `InputDateTime` and `InputDateRange` should be customizable via this token.

**Comment by jonsamwell** [comment]
Can we also get custom seperators i.e. '/' dd/mm/yyyy

**Comment by nsbarsukov** [comment]
> Can we also get custom seperators i.e. '/' dd/mm/yyyy

@jonsamwell 
we will take your proposal into consideration .
Maybe we can create one more token `TUI_DATE_SEPARATOR` or something similar.

**Comment by jonsamwell** [comment]
Sounds good

**Comment by AzatKalim** [comment]
fix [AllureXunitTheory] attribute does not work with MemberData issue
