### ISSUE TITLE
🚀 - TuiPrimitiveTextfieldComponent should allow to pass icons at both sides simultaneously

### ISSUE THREAD

**Issue by EricPoul** [Tinkoff/taiga-ui#978]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

core, kit

### Description

I faced with the problem when I need to pass a left icon to `combo-box` or `select`. My hands are tied because I can pass only the left or right icon to the `TuiPrimitiveTextfieldComponent` simultaneously but `combo-box` and `select` already pass an arrow as `iconContent` to `TuiPrimitiveTextfieldComponent`.

Suggestion: 
Remove the restriction of passing only one icon to the `TuiPrimitiveTextfieldComponent`.

**Comment by waterplea** [comment]
Hi @EricPoul. Do you have a design of the thing you are trying to achieve?

**Comment by EricPoul** [comment]
As an example, I have the next `select` element with an icon in my design. I agree that icon in `select` and `combo-box` is not needed each time but it's sure helpful having this opportunity especially on `combo-box` with strict mode `false`.
![image](https://user-images.githubusercontent.com/31760529/140943229-70190f47-06ba-412a-b800-a5a56a4515a3.png)

**Comment by waterplea** [comment]
I'll resolve this issue as we have released the first RC of 3.0 which got this covered. I'm hoping to have one more RC at most and then 3.0 is out.
