### ISSUE TITLE
🚀 - Update taige-ui to Angular 12 / Ivy compatible to reduce ngcc reliance

### ISSUE THREAD

**Issue by the-ult** [Tinkoff/taiga-ui#980]
### Which @taiga-ui/* package(s) are relevant/releated to the feature request?

ALL

### Description

Update taiga to Angular 13, so we don't have to use/wait for `ngcc` to re-compile to Ivy.

- https://blog.angular.io/upcoming-improvements-to-angular-library-distribution-76c02f782aa4

Related issue(s):
- https://github.com/Tinkoff/taiga-ui/issues/1257
-

**Comment by hheexx** [comment]
Angular 13 started giving warnings about taiga-ui beeing in legacy format.

**Comment by waterplea** [comment]
This would be a breaking change, we cannot bump until all internal projects are bumped and even besides internal projects, it would make Taiga UI incompatible with anything below latest Angular. That's not something we want to do right now. We will keep it in the candidates for the next major version.

**Comment by waterplea** [comment]
Yes, unfortunately, it's too much double work keeping 2 major versions around. We know that first hand since we did that for 0.x to 1.x and have 1.x to 2.x now, everything below 2.x being internal versions before open source release. We are working on updating internal projects, it's not something we passively wait, so I'm gonna have to ask for patience :)

**Comment by hheexx** [comment]
@waterplea As far as I know Ivy distribution can be understood by all angular applications that use Ivy (9+). It's not just for latest Angular version.

Also there should not be a lot of work to have 2 major versions around. Most of libraries do it to support different angular versions. The only difference between versions should be in tsconfig:
  "angularCompilerOptions": {
    "enableIvy": true,
    "compilationMode": "partial"
  }

that should not be big burden to maintain for a limited time.

**Comment by brianpooe** [comment]
I agree with @hheexx our project is up to date and only taiga ui is slowing the build process with ngcc. Would be nice to have v13 branched out at least.

**Comment by hakimio** [comment]
@hheexx That's not true. Ivy partial compilation works only with Angular 12+. Read [the docs](https://angular.io/guide/creating-libraries#publishing-libraries).

**Comment by nsbarsukov** [comment]
In 3.x.x version of our Taiga UI we are going to update our libs to the 12th Angular.

- [X] Angular 10
- [ ] Angular 11
- [ ] Angular 12

___
Also, with 3.x.x we drop legacy `View Engine`-support.

**Comment by the-ult** [comment]
What is the reason the update is until version 12 instead of the current version => 14?
The upgrade process from 12 to 14 is pretty smooth.

**Comment by nsbarsukov** [comment]
@the-ult Hi!
Of course, we also want to use the latest version of Angular.
But there are some restrictions.

Taiga UI is used inside a huge number of our internal projects.
Some of them can still use old versions of Angular.

We believe that Angular 12 can be better for compatibility with old versions of Angular.
Moreover, we've decided that Angular 12 is enough for our purposes for now.
That is why upcoming major release v3.x.x of Taiga UI will introduce only Angular 12.

Of course, in future releases we will update our Angular to more modern version (maybe in v4.x.x or later) !

**Comment by hakimio** [comment]
Are you going to at least drop "View Engine" compatibility?

**Comment by nsbarsukov** [comment]
@hakimio yes

**Comment by waterplea** [comment]
I'll resolve this issue as we have released the first RC of 3.0 which got this covered. I'm hoping to have one more RC at most and then 3.0 is out.
