### ISSUE TITLE
📚 - Invalid base line for postfix

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#989]
### What is the affected URL?

https://taiga-ui.dev/components/primitive-textfield/API?tuiMode=null&postfix=hello

### Description

![image](https://user-images.githubusercontent.com/12021443/141267666-88c8158e-461a-4542-a381-49272dc0d8f0.png)

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by waterplea** [comment]
I don't think there's anything we can do about it. We've been fighting this on and off for quite some time and at different displays, different browsers and different scales there's always a chance of misalignment. We can try making text in the input invisible with `-webkit-text-fill: transparent` and show the underlying "ghost" span, but that seems too extreme in theory.
