### ISSUE TITLE
🤖 - Optimize `taiga-ui.dev` bundle size 

### ISSUE THREAD

**Issue by splincode** [Tinkoff/taiga-ui#999]
### Description

https://pagespeed.web.dev/

Make a detailed analysis of the size of all parts. From the analysis, make a rating of the most frequently used entities with the largest size. Take them one at a time and refactor to reduce the size. During refactoring, notice practices that reduce the weight of the bundle, but do not impair the readability of the code. Collect these practices in one place on a wiki / article and follow them in the future.

### Analytics

<details>
<summary>2021-2022</summary>

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/12021443/225265996-3effde3f-8eee-487b-93de-6c326508070f.png">
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/12021443/225266100-40740068-b738-43b8-887b-70bb195c6148.png">
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/12021443/225266827-ba0bcf87-89f8-488e-9a1e-14bad78d271e.png">

</details>

### Part of

- https://github.com/Tinkoff/taiga-ui/pull/4142
- https://github.com/Tinkoff/taiga-ui/pull/4149
- https://github.com/Tinkoff/taiga-ui/pull/4184
- https://github.com/Tinkoff/taiga-ui/pull/4194

**Comment by splincode** [comment]
https://twitter.com/mgechev/status/1463379373638172676?s=21

**Comment by waterplea** [comment]
> https://twitter.com/mgechev/status/1463379373638172676?s=21

![Screenshot_20211124-125729_Twitter.jpg](https://user-images.githubusercontent.com/11832552/143216437-b331b2f4-3928-42d6-aeef-b44d5538a5fa.jpg)

**Comment by splincode** [comment]
Angular 14 Taiga
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/12021443/187685099-47d01858-bf7a-4464-bf94-6494ffe8f1b7.png">

**Comment by splincode** [comment]
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/12021443/225265996-3effde3f-8eee-487b-93de-6c326508070f.png">
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/12021443/225266100-40740068-b738-43b8-887b-70bb195c6148.png">
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/12021443/225266827-ba0bcf87-89f8-488e-9a1e-14bad78d271e.png">

**Comment by splincode** [comment]
Maybe one day…
